### ISSUE TITLE
Remove `use glib` and `use libc` from autogenerated code

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#1002]
Makes no sense, and we could also remove `use crate::ffi` as that also doesn't improve much.

Related to https://github.com/gtk-rs/gir/pull/996 . Maybe you want to do the `use glib` removal already as part of that PR @GuillaumeGomez

**Comment by sdroege** [comment]
Also `use libc`

**Comment by bilelmoussaoui** [comment]
there are other such as 
```diff
+use cairo;
+use gdk_pixbuf;
```

**Comment by sdroege** [comment]
So somewhere it adds plain crates to `use` still.

**Comment by sdroege** [comment]
And `use std`

**Comment by sdroege** [comment]
As discussed on IRC, we should do this as part of this round already. And `use crate::ffi` is completely unneeded if doing [this](https://github.com/gtk-rs/gtk-rs/pull/161#discussion_r528212927) (which @bilelmoussaoui and I did for our crates already).

**Comment by GuillaumeGomez** [comment]
As for the remaining "use". I don't intend to do it in the same PR either. It requires quite a lot of changes and at this point it's part of improvement rather than mandatory for the switch.

**Comment by bilelmoussaoui** [comment]
This can be closed i guess

**Comment by sdroege** [comment]
Will be closed automatically once the PR is merged :)
