### ISSUE TITLE
Switch to doc cfg instead of feature dox

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#1009]
It was first implemented in https://github.com/gtk-rs/gir/pull/1005 but proved impossible to work when the [PR on gtk-rs](https://github.com/gtk-rs/gtk-rs/pull/177)  was opened.

This is currently not possible because of two things (but only one of them fixed would allow us to make it work):

* https://github.com/rust-lang/cargo/issues/8902
* https://github.com/rust-lang/cargo/issues/8905

**Comment by MarijnS95** [comment]
@GuillaumeGomez Is it time to flip this back on? I read somewhere that `#[cfg]` is now picked up without requiring `#[doc(cfg())]` too? Is the second issue still a problem in practice?

**Comment by GuillaumeGomez** [comment]
It's nightly only for now and requires to enable the feature.

**Comment by MarijnS95** [comment]
@GuillaumeGomez Sure, the "advantage" of the current solution is that you can still build (incomplete) docs on `stable` as long as `dox` is not set. docs.rs already builds with nightly though.

**Comment by bilelmoussaoui** [comment]
Note that our current docs require nightly as well

**Comment by GuillaumeGomez** [comment]
gtk-rs documentation generated on docs.rs is mostly useless unfortunately. Also, we'd need to use `cfg_hide` to not display too many `cfg`s (because we might have some only needed for docs in any case). So not a straightforward conversion.

> Note that our current docs require nightly as well

True, but relying on a very recent nightly feature which is not complete yet (I need to send some follow-ups) is not the best idea here I think.

**Comment by MarijnS95** [comment]
In GStreamer we already have a (by accident, in the GL windowing modules I added probably right during this back-and-forth transition) `#![cfg_attr(all(not(doctest), doc), feature(doc_cfg))]` that doesn't compile on stable rustdoc anyway.

@GuillaumeGomez Yes, we'd have to do the transition atomically. If we just start relying on not needing `doc(cfg())` anymore the `feature="dox"` will show up until we can replace that with `doc` as cfg option.

**Comment by GuillaumeGomez** [comment]
There is `cfg_hide` for that. :3

**Comment by MarijnS95** [comment]
@GuillaumeGomez Sure, but I don't like that :|

**Comment by GuillaumeGomez** [comment]
On one hand, we can remove all `doc(cfg)`, but on the other we have to also use `cfg_hide` globally to avoid having some `cfg`s showing up. For me it seems like a big win. Just that I'd prefer to wait a bit before doing that.

**Comment by MarijnS95** [comment]
@GuillaumeGomez Yes, using `cfg_hide` to just statically hide `doc` is a lot more convenient than having to emit a dynamic `doc(cfg())` that duplicates whatever was written in `#[cfg()]` (minus the things we don't want to show up, but I'd just have liked if `doc` didn't show up at all.

Surely that may confuse something as `--cfg doc` _does_ enable that codepath, so it makes sense to show up without `cfg_hide`.

**Comment by GuillaumeGomez** [comment]
We had issues only relying on `cfg(doc)`, don't remember which but it was quite painful.

**Comment by pentamassiv** [comment]
I think this can be closed now that `#[cfg(docsrs)]` is used and the `dox` feature is gone
