### ISSUE TITLE
Compiler error: comparison operators cannot be chained on `Vec<u8>::uninitialized()`

### ISSUE THREAD

**Issue by abdul-0** [gtk-rs/gir#1030]
I am getting the following error with latest `gir` while generating bindings for libnice:

```rust
error: comparison operators cannot be chained
   --> nice/src/auto/agent.rs:266:30
    |
266 |             let mut buf = Vec<u8>::uninitialized();
    |                              ^  ^
    |
help: use `::<...>` instead of `<...>` to specify type or const arguments
    |
266 |             let mut buf = Vec::<u8>::uninitialized();
```
[libnice-rs](https://github.com/abdul-0/libnice-rs/blob/cb157bc1792778407da13a4db1d35a0071cd7545/nice/Gir.toml#L46)

As a workaround, I am using generated code with  `Vec::<u8>::uninitialized()` change as:

[libnice-rs](https://github.com/abdul-0/libnice-rs/blob/cb157bc1792778407da13a4db1d35a0071cd7545/nice/src/agent.rs#L45)

Using the following versions of the library and tools:
```
libnice commit 804a4c095f
gir commit be0cc8be4438
rust 1.49
```

**Comment by abdul-0** [comment]
Seems similar to https://github.com/gtk-rs/gir/issues/786

**Comment by bilelmoussaoui** [comment]
Indeed, let's keep only one of the issues open
