### ISSUE TITLE
Add link from struct documentation to struct + "Ext"

### ISSUE THREAD

**Issue by tchernobog** [gtk-rs/gir#1059]
Hi, browsing the gtk4-rs documentation, it is a bit hard to discover the documentation of a the "Ext" trait by looking at the documentation of the corresponding struct.

E.g. https://gtk-rs.org/gtk4-rs/gtk4/struct.Button.html doesn't immediately show a link to https://gtk-rs.org/gtk4-rs/gtk4/trait.ButtonExt.html.

I believe this is confusing for newcomers like me, which arrive from the C/C++ GTK API.

Please consider outputting a line for the struct documentation linking to the corresponding trait containing the methods.

I was expecting this to happen around here: https://github.com/gtk-rs/gir/blob/02314d081772fd56d0ec85d72660aaa4df96f074/src/codegen/doc/mod.rs#L247 , but I am not that familiar with the code to be able to patch it myself right now.

**Comment by bilelmoussaoui** [comment]
This is already the case, the issue was with how we built the docs. Should be fixed, see https://gtk-rs.org/gtk4-rs/gtk4/struct.Box.html

**Comment by tchernobog** [comment]
Thanks for the prompt response. Looks fine to me!
