### ISSUE TITLE
Add a builder method to gobjects

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gir#1070]
Adding a builder method to gobjects helps the discoverability of the builder pattern. In my opinion it would also make the usage of the builder pattern a bit more obvious.

For details see https://matklad.github.io/2020/08/12/who-builds-the-builder.html

**Comment by sdroege** [comment]
Indeed, that's something that has to be changed in gir though

**Comment by bilelmoussaoui** [comment]
This one should be pretty easy to do, do you want to tackle it? otherwise I can have a look at it

**Comment by Hofer-Julian** [comment]
Thanks for asking, I'll probably focus on other things this weekend. If you have capacity it would be nice if you look at it 😊
