### ISSUE TITLE
Docs for BindingFlags consts are missing

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gir#1071]
See [here](http://gtk-rs.org/docs/glib/struct.BindingFlags.html)

It is present in the [gir-files](https://github.com/gtk-rs/gir-files/blob/21f76701e9dcc04031240aa9fdcbf8a96bc5b53c/GObject-2.0.gir#L356), so according to @sdroege it is a bug in either the gir tool or rustdoc-stripper

**Comment by bilelmoussaoui** [comment]
Can be closed https://gtk-rs.org/gtk-rs-core/git/docs/glib/struct.BindingFlags.html#associatedconstant.DEFAULT

probably was an issue in the old docs generation way

**Comment by Hofer-Julian** [comment]
Nice!
