### ISSUE TITLE
Add properties to docs

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gir#1076]
Gir currently adds an "Implements" section to the docs (e.g. see [here](https://gtk-rs.org/gtk4-rs/gtk4/struct.Switch.html))

To me it would make sense to add a "Properties" section as well.
After a quick look it seems like most pieces already seem to be in place for that.

Unless anything speaks against it, I'd like to work on it.

**Comment by Hofer-Julian** [comment]
One counter point: GObjects like GtkWindow have many properties
https://gnome.pages.gitlab.gnome.org/gtk/gtk4/class.Window.html#properties

**Comment by ps-19** [comment]
@bilelmoussaoui @Hofer-Julian sir link is broken in first post.

**Comment by ps-19** [comment]
can you please mention steps to remove this issue. I have lot of works related to college, internship.

**Comment by GuillaumeGomez** [comment]
> One counter point: GObjects like GtkWindow have many properties https://gnome.pages.gitlab.gnome.org/gtk/gtk4/class.Window.html#properties

You can always wrap the properties in a `<details>` tag. It would like this:

## Properties

<details>
<summary>Click to see the list of properties</summary>
<ul>
<li>list</li>
<li>of</li>
<li>properties</li>
</ul>
</details>

**Comment by bilelmoussaoui** [comment]
> can you please mention steps to remove this issue. I don't want to take any strain as i have lot of works related to college, internship.

The idea is to modify the generated docs (see src/codgen/docs) to make it generate a list of the properties/signals.
