### ISSUE TITLE
Enum idiosyncrasies

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/gir#108]
I'm going to collect fun enum-related stories here.
- Icon sizes of the supposed [GtkIconSize](https://developer.gnome.org/gtk3/stable/gtk3-Themeable-Stock-Images.html#GtkIconSize) type are passed around as `int`s because that enum isn't exhaustive. https://github.com/GNOME/gtk/commit/0b4af241b60cb63cccc010bc7c94ab2c97134730. The native (i.e. not the FFI one) Rust enum has to account for that. Unfortunately the annotations are attached to function parameters of that type not to the type itself.

**Comment by EPashkin** [comment]
Can we just add to this enum next values: Other(int) and DontScale=-1?

**Comment by gkoz** [comment]
Yes but in the automation context the more interesting question is if it's possible to detect such enums and divine the required additional variants. The "don't scale" case might be better reflected with `Option::<IconSize>::None`.

**Comment by EPashkin** [comment]
After better looking I found that we need find solution only for 3 functions `gtk_icon_set_render_icon`, `gtk_style_real_set_background`, `gtk_widget_create_pango_layout` that accepts -1.
All other function accepts only registered values, so user can just store value returned by `get_icon_register` and use it in function calls.
Only possible problem with IconSize matching but IMHO it mostly unneeded or can be solved direct comparing with stored value.
For 3 problem function we really can use optional size parameter, but it can't be detected automatically and need some config.

**Comment by EPashkin** [comment]
Updated previous comment.

**Comment by EPashkin** [comment]
When checking for `<type name="gint" c:type="GtkIconSize"/>` found many
`<type name="gint" c:type="int"/>`
and only 2 other ginted ctypes: `cairo_format_t` and `pid_t`.
GUinted ctypes `uid_t` with some `unsigned` or `unsigned int`.

**Comment by gkoz** [comment]
So this issue is extremely rare? Good. We could implement the conversions manually and let the generator assume they exist.

It's not clear why `cairo_format_t` is replaced with an `int`. Manually adding conversions to/from `int` would take care of that I expect.

`<type name="gint" c:type="int"/>` is weird but probably harmless.

**Comment by gkoz** [comment]
So, the current assumption in the code that enums are passed directly is problematic in light of these exceptions.

What do we do with `GType`? There's `enum Type` in `glib` so the generator should ideally treat it as a converted enum as well.

**Comment by GuillaumeGomez** [comment]
I think we can close this issue now.
