### ISSUE TITLE
gir confuses the callback definition with params nullability

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gir#1104]
If you take a Callback defined as such
```
pub type GtkShortcutFunc = Option<unsafe extern "C" fn(*mut GtkWidget, *mut glib::GVariant, gpointer) -> gboolean>;
```

Any function that takes that callback as input param, it will have a `Option<Box<F>>` even if the param isn't marked as nullable in the introspection data. see https://github.com/gtk-rs/gtk4-rs/pull/268#discussion_r607078820 for details

**Comment by fengalin** [comment]
I can look into this as part of https://github.com/gtk-rs/gir/pull/1092 which I resumed today. Hopefully, I should to be able to push something before the weekend.

**Comment by fengalin** [comment]
Actually, the callback parameter is marked `nullable = "1"` in `Gtk-4.0.gir`. See line 10 305.
As discussed on IRC, this can be closed.

**Comment by bilelmoussaoui** [comment]
Thanks for checking this one @fengalin
