### ISSUE TITLE
add doc alias for renamed functions

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gir#1105]
Especially after merging the renamed getters, some of the methods have a completely different name. Using doc_alias for that makes sense and would help users figure out the new method names.

cc @fengalin @GuillaumeGomez

**Comment by fengalin** [comment]
I see that you declare this on `gir`. When I checked, doc alias where available in generated code.
I guess you are talking about manual code where there was no doc alias in the first place.

**Comment by bilelmoussaoui** [comment]
What I meant is functions such as https://github.com/gtk-rs/gtk4-rs/blob/master/gtk4/src/auto/widget.rs#L152 would need another doc alias with `get_can_focus`. So every function that has a `rename = "new_method"` would use a `#[doc(alias = "old_method_name")]`. Same thing for methods that are automatically renamed as part of the getter removal

**Comment by fengalin** [comment]
@GuillaumeGomez argued that it would lead to too many common names returned when searching in doc: https://github.com/gtk-rs/gir/pull/1014#discussion_r537558009

**Comment by bilelmoussaoui** [comment]
what would be the difference between before adding the doc aliases & renaming and now? if you search for `get_X` & you get 10 results before, you would still get 10 results now.

**Comment by fengalin** [comment]
@GuillaumeGomez your call :)

It would also be possible to get the `old_method_name` doc alias in manual code since `fix-getters-def` provides this behaviour as an option (no the default due to https://github.com/gtk-rs/gir/pull/1014#discussion_r537558009). I could apply a commit on current `master` based on the diff of a branch that would replace the `fix-getters-def` passes with one with the doc alias option. If we want this, we should do it before those commits are too deep in the commit stack though.

**Comment by GuillaumeGomez** [comment]
No. :)

**Comment by bilelmoussaoui** [comment]
Do you mind providing the reasoning behind ? Imho some function names are completely different from their original ones and the user will have a hard time finding about them.

**Comment by sdroege** [comment]
I also think this would be useful.

**Comment by GuillaumeGomez** [comment]
There are multiple ones:

 * It forces us to add yet another alias information, making the doc search less efficient (result-wise).
 * You can find an item using its C name.
 * It forces us to support yet another feature for only one release. Lot of efforts for close to no gain.

**Comment by bilelmoussaoui** [comment]
Why for only one release? The renames are here to stay.

**Comment by GuillaumeGomez** [comment]
What's the point to keep the doc aliases for more than one release? People will get used to the new naming in the meantime, it's just useless.

**Comment by bilelmoussaoui** [comment]
If we follow the same thinking: What's the point of having the C ones as doc aliases, people will just get used to Rust. They are just useless.

**Comment by GuillaumeGomez** [comment]
Nope, not the same logic. The C functions are there to stay, the old naming of the rust functions is definitely gone, making it pointless. You want a aliases for a migration and compare it to a translation between a C API and a Rust one.

**Comment by bilelmoussaoui** [comment]
> Nope, not the same logic. The C functions are there to stay, the old naming of the rust functions is definitely gone, making it pointless. You want a aliases for a migration and compare it to a translation between a C API and a Rust one.

I see your reasoning but that's not really how GIR works. It provides you with the name of the functions you're supposed to be using, most of people search those functions not the C ones. For example
```
    #[doc(alias = "gtk_widget_get_child_visible")]
    fn is_child_visible(&self) -> bool;
```

How would I know I should search for `is_child_visible` & not `get_child_visible`. The same goes for a bunch of other functions.

**Comment by GuillaumeGomez** [comment]
And you will have `get_child_visible` appear in your search in any case, so not an issue.

**Comment by sdroege** [comment]
Why? Because of subset matching on the C name?

**Comment by bilelmoussaoui** [comment]
I wouldn't have opened an issue if it worked: https://gtk-rs.org/gtk4-rs/git/docs/?search=get_child_visible

**Comment by GuillaumeGomez** [comment]
> Why? Because of subset matching on the C name?

Not sure to understand your message here...

> I wouldn't have opened an issue if it worked: https://gtk-rs.org/gtk4-rs/git/docs/?search=get_child_visible

Hum, interesting. Wonder why levenhstein distance isn't working in this case...

But that remains a big no for me. :)

**Comment by bilelmoussaoui** [comment]
I still don't really see a reasoning behind the big no.

**Comment by GuillaumeGomez** [comment]
More code for very little gain for ONE migration which will need to be removed at the next one. It's far from the first time that we update functions' name, people simply get used to it and move on. I don't want to add more technical debt for a one time thing.

**Comment by bilelmoussaoui** [comment]
Well that's the misunderstanding here: the doc aliases should never be removed. They point to the original function name that GIR based language should be using.

**Comment by GuillaumeGomez** [comment]
Except that there is no such function with the original name anymore and it won't ever be. So it's a one time migration. If the issue is that the name isn't good, then we can simply revert the whole thing.

**Comment by sdroege** [comment]
This is for people searching for a function name they would know from gir or any other gir-based languages. Just like `std` has a doc alias for `memset` on `std::slice::fill`.

**Comment by alatiera** [comment]
Yes, as I understand it to, this has more to do with aliasing the gir provided name, than the old and now renamed name.

**Comment by bilelmoussaoui** [comment]
Is there a chance of getting this re-opened? I still believe this is really important to have before the next release imho.

**Comment by sdroege** [comment]
Yeah I think we should have this too. It's IMHO even more important than having the aliases for the C functions. If the problem is performance then I'm fine with dropping those in exchange.

**Comment by fengalin** [comment]
I think so too. We could at least try it and check if the impact on the index is indeed a concern.

**Comment by GuillaumeGomez** [comment]
I'm opposed to it so I don't see how it can be added. :-/

**Comment by sdroege** [comment]
Let's remove the C aliases then instead? Overall we will have the same number of aliases then and it's useful to more users.

**Comment by GuillaumeGomez** [comment]
The C aliases are useful (at least to me). So I'd rather not. And again: one of the arguments against the renaming was that it'd get harder to find what you're looking for. We decided to move forward with it, but there is no reason to add aliases to previous names.

**Comment by MarijnS95** [comment]
Chiming in without reading the full issue: Isn't a substring of the C alias the original name already? That way it can already be found by the `get_old_method_name`?

**Comment by sdroege** [comment]
> The C aliases are useful (at least to me). So I'd rather not. And again: one of the arguments against the renaming was that it'd get harder to find what you're looking for. We decided to move forward with it, but there is no reason to add aliases to previous names.

That's also not what it is about. It's not about aliases for previous names, it's aliases for the proper gir names. That was a problem before the recent renames already and people asked questions on IRC regularly because they couldn't find functions.

This has all nothing to do with the getter renames.

> Chiming in without reading the full issue: Isn't a substring of the C alias the original name already? That way it can already be found by the `get_old_method_name`?

It's using Levenshtein distance to see if it's close enough. And if the distance is bigger than 5 or so, it simply discards. So `gtk_widget_foo_bar` will never match `foo_bar` because the distance is more than 5 here.

**Comment by GuillaumeGomez** [comment]
To be noted that the aliases are only "exact match". And also that the levenhstein distance is an issue for small items.

**Comment by sdroege** [comment]
Maybe in addition rustdoc should also show items if it's a contiguous substring match of enough characters. So that `gtk_widget_foo_bar` would also match `foo_bar` because that's 7 characters one after another that are in both. But that's a rustdoc concern.

**Comment by GuillaumeGomez** [comment]
I need to improve search overall. There a lot of corner cases which are problematic.

**Comment by MarijnS95** [comment]
> To be noted that the aliases are only "exact match". And also that the levenhstein distance is an issue for small items.

Ah right, so my idea of typing only the right hand (associated member) side of the function, and then picking the one that shows up for the desired type won't work - the C function needs to be copied verbatim. Good to know!

Looks like the rename aliases might address that to some extent, bar the other issues mentioned.

**Comment by bilelmoussaoui** [comment]
This was actually fixed, thanks a lot @fengalin
