### ISSUE TITLE
Builder pattern uses Vec<String>

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gir#1122]
The builder pattern uses `Vec<String>` instead of something a bit nicer to use like `&[&str]`, it could even use `T: AsRef<str>; &[T]` & then take ownership of the strings inside the builder method.

**Comment by bilelmoussaoui** [comment]
Hi @Rakielle, please go ahead :) let me know if you need help figuring this one out.

**Comment by Rakielle** [comment]
Thank you @bilelmoussaoui, I was having an issue joining the Matrix chat. I sent you a mail about it.
Could you please check?

**Comment by bilelmoussaoui** [comment]
Oh sorry, I missed that one. I think you were trying to create an account on the GNOME matrix server which is only open to GNOME contributors/developers (that have a `@gnome` email address). You can create an account on the main matrix homeserver and join the room just fine

**Comment by Rakielle** [comment]
Thanks @bilelmoussaoui, I've been able to join the room

**Comment by Rakielle** [comment]
@bilelmoussaoui I was using the gir book in the repository to learn how gir works but I got stuck at the **Generate the FFI library** tutorial. The tutorial uses the `GtkSource-3.0.gir` file which isn't present in the `https://github.com/gtk-rs/gir-files` repo. I tried using `Gtk-3.0.gir` file which did not work as I keep getting lots of errors.

**Comment by bilelmoussaoui** [comment]
You can grab it from an older version of gir-files, like in https://github.com/gtk-rs/gir-files/tree/8a626fde7528ebb62a4d7902f201e483ca2ae05b

**Comment by Rakielle** [comment]
@bilelmoussaoui I was able to extract the `GtkSource-30.gir` file from the link. I'm till having issues generating FFI library for the `GtkSource-3.0.gir` file though. I'm running into several errors.

Is there a recent documentation that could help me get setup? I'm currently using https://gtk-rs.org/gir/book/tutorial/sys_library.html

**Comment by Segun-Ogundipe** [comment]
Hi @bilelmoussaoui in what files can I find the builder patterns?

**Comment by bilelmoussaoui** [comment]
This got fixed recently and we are using `impl Into<glib::StrV>`
