### ISSUE TITLE
Impl Default trait for all widgets that support the builder pattern

### ISSUE THREAD

**Issue by AaronErhardt** [gtk-rs/gir#1221]
Some widgets like `gtk::Box` or `gtk::ApplicationWindow` don't implement the `Default` trait although you can simple use `Widget::builder().build()` to get a default widget. Currently, this workaround based on the builder pattern is used by Relm4 to get more default configurations for its widget macro with the [`DefaultWidget` trait](https://aaronerhardt.github.io/docs/relm4/relm4/util/default_widgets/trait.DefaultWidget.html).

@Hofer-Julian

**Comment by sdroege** [comment]
This sounds useful. Do you want to provide a PR for this?

**Comment by AaronErhardt** [comment]
I can try to provide a PR. Yet I wonder what's the best approach. I could just copy the code from Relm4 to gtk4-rs but that wouldn't be a really clean solution. Maybe gir is the right place for this but I don't know enough about gir to know where to start.

**Comment by AaronErhardt** [comment]
@sdroege @Hofer-Julian is there any progress on this issue? As I said, I can provide a PR, but I need some guidance because I'm new to gir. And I wonder if this can even be automated or whether I should just implement it manually in gtk4-rs (and libadwaita-rs).

**Comment by Hofer-Julian** [comment]
The Default impl for Button is in the generated gir file so it might be reasonable to autogenerate the missing ones for other widgets as well.

https://github.com/gtk-rs/gtk4-rs/blob/a7b3c61fd95a57a980bf17442e5861f58b32c1ad/gtk4/src/auto/button.rs#L82

Unfortunately I also have no experience with gir and cannot provide guidance

**Comment by AaronErhardt** [comment]
I think gir simply implements `Default` for all types that have a `Self::new()` function without parameters. Like `gtk::Button::new()`.

However types such as Box that use `gtk::Box::new(orientation: Orientation, spacing: i32)` the `Default` trait implementation isn't as simple as calling `new()`. Even the original GTK function for creating a Box takes parameters, in other words, there's no default implementation for a Box in GTK: https://docs.gtk.org/gtk4/ctor.Box.new.html

Is see two options for implementing the `Default` trait:

+ Implement it manually in gtk4-rs
+ Add a trait for the builder pattern and use a generic implementation of `Default` for all types that support the builder pattern.

Maybe there's a hack to get it working with gir. But I don't think so because how would gir choose the default orientation and spacing for constructing a Box?

**Comment by sdroege** [comment]
That's a general problem with the builders. The default values are taken from the default property values of the types.

For implementing `Default` for everything that provides a builder, you could simply let gir generate code that creates the builder and then directly creates the object out of it.

Check in gir where the builders are created. As part of that it should be relatively easy to put a `Default` impl in there too. You just need to be careful to not end up with two (there will already be one if the object has a parameter-less `new()` function).

**Comment by Hofer-Julian** [comment]
@slomo do you agree that if a builder is available, it should always be used for Default over new?

**Comment by sdroege** [comment]
No, I would use the explicit `new()` function if it's available. It might do something more sensible.

**Comment by Hofer-Julian** [comment]
I have to check later, but I was really hoping that builder().build() does exactly the same thing as new() in all instances.

**Comment by sdroege** [comment]
`new()` calls a C function that could do anything to provide a "default" object, `builder().build()` calls `glib::Object::new()` with the default values for each property. Ideally these are the same but that's not necessarily the case, and `new()` would be what the library developer considered a "default" instance.

**Comment by AaronErhardt** [comment]
I wonder if `glib::Object::new()` is acceptable because that would be a pretty simple solution. If `new()` takes no parameters we could use it and otherwise `glib::Object::new()`.

The only other solution would be to use `new(...)` and implement `Default` manually for each widget. Yet, widgets such as ApplicationWindow would be a bit weird to implement because you'd have to create and pass a new application into `new()`.

**Comment by sdroege** [comment]
Yes, calling `glib::Object::new()` with no parameters would initialize all properties to their default values.
