### ISSUE TITLE
Support custom visibility on generated functions

### ISSUE THREAD

**Issue by lucab** [gtk-rs/gir#1238]
This is a new-feature request to support generating specific functions with custom visibility.

Right now auto-generated functions get a `pub` visibility modifier by default. In some cases, it would be useful to auto-generate some entries with `pub(crate)` visibility (for example), so that they can be used to build higher-level ergonomic Rust patterns in the same crate without exposing the low-level primitives in the public API.

For a concrete example, `libostree` has a few `ostree_sysroot_<foo>` [helpers](https://ostreedev.github.io/ostree/reference/reference.html#api-index-full) which rely on state (e.g. loaded, ro-locked, rw-locked, etc.) that could be encoded in a more ergonomic way in the Rust type-system.
The auto-generated functions are useful as building blocks for the higher-level types, but they should not end up in the final public surface of the crate. A `pub(crate)` modifier on those would suit better in this case.

**Comment by bilelmoussaoui** [comment]
That's something I will look into today, so that it unlocks https://github.com/gtk-rs/gtk-rs-core/pull/412
