### ISSUE TITLE
Generate bitfields, enums and consts reexports

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/gir#124]
The best modules organization is not entirely clear now. Possibly add modules `bitfileds`, `enums`, `consts` under `auto`.

Initially this is just a bunch of reexports like this:

``` rust
pub use ffi::GtkAccelFlags as AccelFlags;
```

If #123 is decided in favor of converting enums, the `enums` module will contain the enums definitions and conversion impls.

**Comment by EPashkin** [comment]
This old issue that already done long ago
