### ISSUE TITLE
RFC: generate `NONE` constants as associated constants

### ISSUE THREAD

**Issue by fengalin** [gtk-rs/gir#1252]
## NONE constants

For [non "final types"](https://github.com/gtk-rs/gir/blob/8663b33dd5e8c284013c5ff5d306cc04b578d4d4/src/codegen/object.rs#L275), `gir` generates a constant in the form:

``` rust
pub const NONE_PAD: Option<&Pad> = None;
```

This allows passing `NONE_PAD` as an argument instead of the verbose `Option::<&Pad>::None`.

These constants are explicitly re-exported so that they bubble up to the crate's scope ([see in codegen](https://github.com/gtk-rs/gir/blob/8663b33dd5e8c284013c5ff5d306cc04b578d4d4/src/codegen/object.rs#L568)).

## Proposal

Defining an associated constant such as:

``` rust
impl Pad {
    pub const NONE: Option<&'static Pad> = None;
}
```

... would allow passing `Pad::NONE` as an argument.

- This would be more consistent with Rust usage IMHO (see [`Duration::ZERO`](https://doc.rust-lang.org/std/time/struct.Duration.html#associatedconstant.ZERO)).
- No additional re-export is needed since the constant is referred to direclty from its `struct`.
- This is similar to C constants, at least in `gstreamer` (see [`GST_CLOCK_TIME_NONE`](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/blob/master/gstreamer/sys/src/lib.rs#L432)).

## Options

If we decide to go this route, we could:

1. Generate both `NONE_XXX` and `XXX::NONE`. Existing applications would work unchanged, however this provides two means to achieve the same purpose.
2. Generate both `NONE_XXX` and `XXX::NONE` and add a deprecation attribute to `NONE_XXX`, with a message explaining that `XXX::NONE` should be preferred. Existing applications would compile with warnings. People could migrate their applications when they deem appropriate or silence the compilation warning if they prefer the `NONE_XXX` form. The deprecated form would be kept, just like deprecated items are kept in `std`. I remember we disagreed about deprecation attributes in another proposal.
3. Generate `XXX::NONE` only. Application developers would need to replace all occurrences of `NONE_*` with `*::NONE`, there are probably not many in use though.

**Comment by sdroege** [comment]
I like this and would vote for 3. Personally I think these constants shouldn't really exist anyway but apparently it's making things easier for beginners.

**Comment by sdroege** [comment]
CC @bilelmoussaoui @GuillaumeGomez

**Comment by bilelmoussaoui** [comment]
I would vote for 3 as well, looks way nicer imho.

**Comment by GuillaumeGomez** [comment]
3 as well!

**Comment by fengalin** [comment]
Great! I'll start working on it tomorrow.
