### ISSUE TITLE
generator script should remove src/auto before regen

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gir#1269]
Otherwise removed files (no longer generated ones) are kept there and you might end up forgetting to drop them

**Comment by GuillaumeGomez** [comment]
Good point!

**Comment by sdroege** [comment]
Let's hope nobody puts other files into `src/auto` and expects them to survive :)

**Comment by GuillaumeGomez** [comment]
They'll learn the way. :D
