### ISSUE TITLE
More generic argument in callbacks

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gir#1288]
When you have objects A and B, where B is a subclass of A, the callback functions of A will take `a: &A` as their argument, forcing one to always do `let b = a.downcast::<A>().unwrap()`.

It might be interesting if such callbacks were generated with a `&glib::IsA<A>` instead of `&A`.

**Comment by bilelmoussaoui** [comment]
Mind sharing some examples where such change could be needed?

**Comment by A6GibKm** [comment]
For example https://gtk-rs.org/gtk4-rs/git/docs/gtk4/struct.ListBox.html#method.connect_row_activated, the row parameter is not generic. 

I forgot that indeed the first parameter is always generic, this only applies to the parameter that do not refer to the subclassed class itself.

**Comment by sdroege** [comment]
It can't really. It can't know what type is returned there (and you could even have a mix of different types), so the most generic type (`ListBoxRow`) has to be returned and your code has to check what it actually is and cast accordingly, if needed.
