### ISSUE TITLE
gir v0.15 inserts assertion to check return value even if throw function returns void

### ISSUE THREAD

**Issue by takaswie** [gtk-rs/gir#1331]
In API mode, `assert_eq!()` macro is inserted to evaluate `is_ok` variable
which should have return value of function call even if the function returns
void in C API.

For example of [alsa-gobject](https://github.com/alsa-project/alsa-gobject/blob/master/src/ctl/card.c#L191),

```
/**
 * alsactl_card_open:
 * @self: A #ALSACtlCard.
 * @card_id: The numerical ID of sound card.
 * @open_flag: The flag of open(2) system call. O_RDONLY is forced to fulfil internally.
 * @error: A #GError. Error is generated with two domains; #g_file_error_quark() and
 *         #alsactl_card_error_quark().
 */
void alsactl_card_open(ALSACtlCard *self, guint card_id, gint open_flag,
                       GError **error)
{
    ...
}
```

The generated FFI crate has [below API](https://github.com/alsa-project/alsa-gobject-rs/blob/master/alsactl-sys/src/lib.rs#L356) for the above:

```
    pub fn alsactl_card_open(
        self_: *mut ALSACtlCard,
        card_id: c_uint,
        open_flag: c_int,
        error: *mut *mut glib::GError,
    );
```

The gir v0.15 generates below codes for the above, which includes issued assertion and variable:

```
pub trait CardExt: 'static {
    ...
    #[doc(alias = "alsactl_card_open")]
    fn open(&self, card_id: u32, open_flag: i32) -> Result<(), glib::Error>;
    ...
}
...
impl<O: IsA<Card>> CardExt for O {
    ...
    fn open(&self, card_id: u32, open_flag: i32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let is_ok = ffi::alsactl_card_open(
                self.as_ref().to_glib_none().0,
                card_id,
                open_flag,
                &mut error,
            );
            assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }
...
```

The assertion brings compilation error:

```
$ cargo build -p alsactl
   Compiling alsactl-sys v0.2.0 (/home/mocchi/git/alsa-gobject-rs/alsactl-sys)
   Compiling alsactl v0.2.0 (/home/mocchi/git/alsa-gobject-rs/alsactl)
...
error[E0308]: mismatched types
   --> alsactl/src/auto/card.rs:107:33
    |
107 |             assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
    |                                 ^^^^^^^^^^^^^^^^^ expected `()`, found `i32`
```

I had a discussion with @sdroege in Matrix service and got an advice that
in GNOME convention when function has argument for GError, it should return
gboolean to notify error generation or not. However it is likely that some
libraries don't follow to the convention yet. It takes a bit time for developers to
rewrite such libraries since it requires to update signature of exposed C function
and easily lose backward compatibility.

In fact, gir v0.14 or before generates codes without the assertion, like:

```
    fn open(&self, card_id: u32, open_flag: i32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::alsactl_card_open(
                self.as_ref().to_glib_none().0,
                card_id,
                open_flag,
                &mut error,
            );
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }
```

I think it worth considering to keep backward compatibility for such libraries.

For discussion, I prepare some patches to suppress the behaviour. I'd like
you to check it:
https://github.com/takaswie/gir/tree/topic/suppress-assertion-for-return-void

I note that in this trial I don't use new configuration option and simply check
return value of c_type for the function.

Regards

**Comment by sdroege** [comment]
> For discussion, I prepare some patches to suppress the behaviour. I'd like
> you to check it:
> https://github.com/takaswie/gir/tree/topic/suppress-assertion-for-return-void

This looks like the correct solution to me. There's no need for configuration here IMHO.

However I would change to be the other way around. Only don't insert the assertion if `void` is returned. In all other cases it's good if the generated code fails to compile because it's unclear what the semantics of the function is and it will have to be manually bound.

**Comment by takaswie** [comment]
> > For discussion, I prepare some patches to suppress the behaviour. I'd like
> > you to check it:
> > https://github.com/takaswie/gir/tree/topic/suppress-assertion-for-return-void
> 
> This looks like the correct solution to me. There's no need for configuration here IMHO.
> 
> However I would change to be the other way around. Only don't insert the assertion if `void` is returned. In all other cases it's good if the generated code fails to compile because it's unclear what the semantics of the function is and it will have to be manually bound.

It makes sense. But I think we can output comment lines for the unclear cases as for unclear function arguments.

I have another idea to use enumeration item tuple of Mode::Throws instead of evaluation in codegen module.
At present it's `bool` but additional enumeration with three cases for the tuple makes it possible to evaluate inner analysis.

For example,

```
(src/analysis/out_parameters.rs)
pub enum ThrowFunctionReturnStrategy {
  SimplyReturn, // Simply return the value.
  ConditionCheck, // Check the return value for error condition.
  Unuse, // Don't use it.
}

pub enum Mode {
  ...
  Throws(ThrowFunctionReturnStrategy), // Instead of bool.
  ...
}

(src/codegen/function_body_chunk.rs)
fn apply_outs_mode(...) -> (Chunk, Option<Chunk>) {
  ...
  Throw(func_return_strategy) => {
    ...
    match func_return_strategy {
      ThrowFunctionReturnStrategy::SimplyReturn => ...,
      ThrowFunctionReturnStrategy::ConditionCheck => ...,
      ThrowFunctionReturnStrategy::Unuse => ...,
    }
    ...
  }
  ...
}
```

But tonight and tomorrow I have no time to work for it since I decide to follow to Japanese goverment request to save electric power consumption against power shortage brought last week's earthquake:

 * https://www.reuters.com/world/asia-pacific/japan-sees-partial-blackout-after-first-ever-power-supply-warning-2022-03-22/

Anyway thanks for your reaction for the issue.

Cheers.

**Comment by takaswie** [comment]
I filed merge request at #1333 for the issue. I'm happy if you progress it.

**Comment by takaswie** [comment]
Fix merged. Let's close the issue. Thanks for your reviewing.
