### ISSUE TITLE
Remove is_windows_utf8 configuration

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#1343]
See https://github.com/gtk-rs/gir/issues/375 for background.

This change is not needed anymore since GLib 2.54, see https://bugzilla.gnome.org/show_bug.cgi?id=780634 . The `_utf8()` and non-`_utf8()` versions of the code are doing the same thing on Windows and are just staying around for binary compatibility.

Previously on Windows (more than 20 years ago!) there were no `_utf8()` versions on Windows. At some point those mapped (at compile-time) to the `_utf8()` versions on Windows (20 years ago or so), so even from a C point of view everything compiled in the last two decades was always using the UTF-8 variants.

We should update to GLib 2.54 as the minimum supported version (and update everything else to the corresponding versions), and then get rid of this useless complication.

CC @bilelmoussaoui @GuillaumeGomez

**Comment by jim4067** [comment]
Hello @sdroege I'd love to look into this. 

Since `is_windows_utf8` function is no longer required, I'll mostly be removing the function from the codebase? and making sure not to break anything?

**Comment by sdroege** [comment]
You'd remove it from here and then update `gtk-rs-core` and `gtk3-rs` to not make use of it anymore

**Comment by jim4067** [comment]
I haven't seen any `is_windows_utf8` in the gtk3-rs

**Comment by sdroege** [comment]
Indeed, it's only used in gtk-rs-core. Thanks for checking!
