### ISSUE TITLE
Some generated parse functions do not pass clippy

### ISSUE THREAD

**Issue by filnet** [gtk-rs/gir#1356]
This generated code:

```
    #[doc(alias = "gst_play_message_parse_buffering_percent")]
    pub fn parse_buffering_percent(msg: &gst::Message) -> u32 {
        assert_initialized_main_thread!();
        unsafe {
            let mut percent = mem::MaybeUninit::uninit();
            ffi::gst_play_message_parse_buffering_percent(
                msg.to_glib_none().0,
                percent.as_mut_ptr(),
            );
            let percent = percent.assume_init();
            percent
        }
    }
```

Generates this clippy error:

```
error: returning the result of a `let` binding from a block
   --> gstreamer-play/src/auto/enums.rs:282:13
    |
281 |             let percent = percent.assume_init();
    |             ------------------------------------ unnecessary `let` binding
282 |             percent
    |             ^^^^^^^
    |
    = note: `-D clippy::let-and-return` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return
help: return the expression directly
    |
281 ~             
282 ~             percent.assume_init()
```

**Comment by filnet** [comment]
This issue blocks https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/1036

**Comment by bilelmoussaoui** [comment]
I don't think it is a blocker, you could `#[allow(clippy::let_and_return)]` before your `mod auto;`. Fixing that would be great though

**Comment by filnet** [comment]
It is not simple to fix as the code handles a lot of situations (need_from_glib, tuples, ...).

**Comment by sdroege** [comment]
> This issue blocks https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/1036

@filnet FWIW, I'm fine with adding `#![allow(clippy::let_and_return)]` in gstreamer-rs for that for the time being. Fixing this doesn't seem to be too simple so let's not block on that.

**Comment by filnet** [comment]
> @filnet FWIW, I'm fine with adding `#![allow(clippy::let_and_return)]` in gstreamer-rs for that for the time being. Fixing this doesn't seem to be too simple so let's not block on that.

I am working on fix and it looks promising. I was able to fold the rhs of the `Let` into the `Tuple`.
Works for the new gstreamer-play project. I need to test on the whole gstreamer-rs now.

**Comment by filnet** [comment]
The fix looks good too when applied to the whole gstreamer-rs repo.
Here is what the changes look like : https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/1040

Many less changes than I was expected.

But net result is quite good:
- less code
- more correct `MaybeUninit` usage (?)
- fixes the clippy warning (not shown in the gstreamer-rs MR but works on my PC)

**Comment by filnet** [comment]
Down side is that gstreamer-rs does seem to use all supported function return types.
One missing case is functions returning Arrays.

**Comment by bilelmoussaoui** [comment]
Looks promising, thanks for taking care of that!
