### ISSUE TITLE
Activate the dox feature wherever it is available

### ISSUE THREAD

**Issue by pentamassiv** [gtk-rs/gir#1381]
I wanted to activate the dox feature for all gtk-core-rs, gtk3 and gtk4 crates so the docs build on docs.rs. I edited the `Cargo.toml` files. Unfortunately gir messes with them and reverts the changes.
These are the three pull requests I opened for the issue:
https://github.com/gtk-rs/gtk-rs-core/pull/778
https://github.com/gtk-rs/gtk3-rs/pull/775
https://github.com/gtk-rs/gtk4-rs/pull/1135

**Comment by pentamassiv** [comment]
I'll have a look at this later today. If it is easy enough for me, I'll fix it myself.

**Comment by bilelmoussaoui** [comment]
The change should be done somewhere in https://github.com/gtk-rs/gir/blob/master/src/codegen/sys/cargo_toml.rs btw

**Comment by pentamassiv** [comment]
Fixed (PR https://github.com/gtk-rs/gir/pull/1388)
