### ISSUE TITLE
Avoid generating a method if a parent already has it

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/gir#139]
For instance, `gtk_widget_activate` vs `gtk_menu_item_activate`.
Emit a warning -- in cases I've seen so far they're essentially duplicate, but who knows.
Bonus points for comparing the signatures.

**Comment by EPashkin** [comment]
IMHO some function names will be good in description.

**Comment by gkoz** [comment]
Yes, for an example see https://github.com/gtk-rs/gtk/issues/168, also `gtk_tree_view_get_n_columns` vs `gtk_tree_model_get_n_columns`.

**Comment by gkoz** [comment]
This turns out not so easy. Currently analysis results aren't stored so you can't just pass over them again marking the duplicates. Looks like this will have to wait for #136

**Comment by EPashkin** [comment]
Agree :cry:

**Comment by EPashkin** [comment]
For current attempt I found that these methods is duplicated (by name)
Button (parent Widget has methods with "v3_20")
fn get_focus_on_click(&self) -> bool;
fn set_focus_on_click(&self, focus_on_click: bool);
CellAreaBox (parent CellLayout has different number of arguments):
pub fn pack_end<T: IsA<CellRenderer>>(&self, renderer: &T, expand: bool, align: bool, fixed: bool)
pub fn pack_start<T: IsA<CellRenderer>>(&self, renderer: &T, expand: bool, align: bool, fixed: bool)
ComboBox (same as Button)
fn get_focus_on_click(&self) -> bool;
fn set_focus_on_click(&self, focus_on_click: bool);
ComboBoxText (parent Container has `fn remove<T: IsA<Widget>>(&self, widget: &T)`)
pub fn remove(&self, position: i32)
Container (parent Widget has different number of arguments):
fn child_notify<T: IsA<Widget>>(&self, child: &T, child_property: &str);
FileChooserButton (same as Button)
pub fn get_focus_on_click(&self) -> bool
pub fn set_focus_on_click(&self, focus_on_click: bool)
Menu (parent Widget has different number of arguments):
pub fn set_accel_path(&self, accel_path: Option<&str>)
MenuButton (parent Widget has `fn get_direction(&self) -> TextDirection`
#[cfg(feature = "v3_6")]
pub fn get_direction(&self) -> ArrowType
#[cfg(feature = "v3_6")]
pub fn set_direction(&self, direction: ArrowType)
MenuItem (same as Menu):
fn set_accel_path(&self, accel_path: Option<&str>);
StatusBar (parent Container has different number of arguments)
pub fn remove(&self, context_id: u32, message_id: u32)
TextView (parent Widget has different number of arguments)
pub fn get_window(&self, win: TextWindowType) -> Option<gdk::Window>
ToolItem (parent Widget has same function with Option(&str) so it good to hide)
fn set_tooltip_markup(&self, markup: &str);
fn set_tooltip_text(&self, text: &str);
Toolbar (Parent ToolShell only differ `fn get_icon_size(&self) -> i32`)
pub fn get_icon_size(&self) -> IconSize
pub fn get_relief_style(&self) -> ReliefStyle
pub fn get_style(&self) -> ToolbarStyle
TreeViewColumn (Parent CellLayout has same function)
pub fn add_attribute<T: IsA<CellRenderer>>(&self, cell_renderer: &T, attribute: &str, column: i32)
pub fn clear(&self)
pub fn clear_attributes<T: IsA<CellRenderer>>(&self, cell_renderer: &T)
pub fn pack_end<T: IsA<CellRenderer>>(&self, cell: &T, expand: bool)
pub fn pack_start<T: IsA<CellRenderer>>(&self, cell: &T, expand: bool)
Window (Parent Widget has "v3_8" on opacity)
fn get_opacity(&self) -> f64;
fn get_screen(&self) -> Option<gdk::Screen>;
fn mnemonic_activate(&self, keyval: u32, modifier: gdk::ModifierType) -> bool;
fn set_opacity(&self, opacity: f64);

**Comment by EPashkin** [comment]
@GuillaumeGomez, I can "fix" wrong duplicate if it has different signature (currently fixed by different number arguments),
but no idea what do with same methods with different version.

**Comment by GuillaumeGomez** [comment]
If you have the version, then why not having both methods and then add a conditional compilation?

```rust
#[cfg(gtk = "3.2")]
fn foo() {}

#[cfg(not(gtk = 3.2")]
fn foo() -> i32 {}
```

**Comment by EPashkin** [comment]
You mean that
Widget has 
```
#[cfg(feature = "v3_20")]
fn get_focus_on_click(&self) -> bool;
```
and Button and others
```
#[cfg(not(feature = "v3_20"))]
fn get_focus_on_click(&self) -> bool;
```
It right way, but not sure that can be normally realized.
Currently I just compare current method signature with all parents and ignore method if found.

**Comment by GuillaumeGomez** [comment]
I guess we can try to add another step. But if the parent has the exact same method, I'm not sure this will be an issue... I guess it'll call the same one as the child.

**Comment by EPashkin** [comment]
@GuillaumeGomez, problem is harder that I though: rust don't separate functions with same name even if it in different traits (ComboBoxText::remove overrides Container::remove)
```
let cbtext: &ComboBoxText = unimplemented!();
//cbtext.remove(1);
cbtext.remove(&window);
```
it works normal if ComboBoxText::remove commented.

**Comment by GuillaumeGomez** [comment]
Is it possible to make a workaround with default implementations by any chance?

**Comment by EPashkin** [comment]
Not sure. `Container` not parent of `ComboBoxText`.
Containers `remove` visible with `cbtext.upcast::<Container>().remove(&window);`
If we do autoignore methods with totally equal parameters then latest (childs) method will be available as default and parent method with different parameters will be accesible with `upcast` (maybe with cloning as it consuming self)

**Comment by EPashkin** [comment]
Hm, after I do checking parameters and return types, I realized that `gtk_widget_activate` and `gtk_menu_item_activate` has different signatures: widget's version return `bool`, so `gtk_menu_item_activate` seems stays ignored by config.

**Comment by EPashkin** [comment]
Despite `gtk_menu_item_activate` still ignored manually due different signature,
I think the issue solved,

**Comment by GuillaumeGomez** [comment]
@EPashkin: And thanks a lot of fixing it!
