### ISSUE TITLE
Builders should store a SmallVec<[(&'static str, Value)]>

### ISSUE THREAD

**Issue by jf2048** [gtk-rs/gir#1391]
This would significantly reduce the stack size of the builder, and would not cause any extra overhead since `Object::new_internal` has to do this anyway. The builders can also unsafely call `new_internal` to avoid checks, since we know they only use valid properties.

After that, the builders could be made generic and the property setters could be moved into extension traits, which would cut down on a lot of the duplicated generated code.

**Comment by sdroege** [comment]
> The builders can also unsafely call `new_internal` to avoid checks, since we know they only use valid properties.

That's not actually what it does. The only thing it doesn't do is checking whether the type implements `GInitable` or `GAsyncInitable`.

> This would significantly reduce the stack size of the builder

It would actually increase the stack size or not? Right now it's just allocated on the heap in a `Vec`. But it gets rid of a useless heap allocation in many cases.

Actually, I was thinking that we could make use of the generic `ObjectBuilder` for the specific builders. But that would go against your idea of omitting the property validity checks as that one always would have to do that.
