### ISSUE TITLE
generated code broken

### ISSUE THREAD

**Issue by ttys3** [gtk-rs/gir#1440]
https://gitlab.gnome.org/World/Rust/webkit2gtk5-rs generated with 952ff416b5997f50b9261c62c7589100e35a1459 it is OK.

but update to 047f55810b96f41d9956b11244dcbb8a1510c85a, the result code not compile.

for example: `WebViewBuilder::new()` should be public, but the new is not:

```
522 |     let webview = WebViewBuilder::new()
    |                                   ^^^ private associated function
```

and also:

    ```
    error[E0034]: multiple applicable items in scope
       --> webkit2gtk/src/auto/web_resource.rs:139:17
        |
    139 |             obj.data(Some(cancellable), move |res| {
        |                 ^^^^ multiple `data` found
        |
        = note: candidate #1 is defined in an impl of the trait `glib::ObjectExt` for the type `T`
    note: candidate #2 is defined in an impl of the trait `WebResourceExt` for the type `O`
       --> webkit2gtk/src/auto/web_resource.rs:81:5
        |
    81  | /     fn data<P: FnOnce(Result<Vec<u8>, glib::Error>) + 'static>(
    82  | |         &self,
    83  | |         cancellable: Option<&impl IsA<gio::Cancellable>>,
    84  | |         callback: P,
    85  | |     ) {
        | |_____^
    help: disambiguate the associated function for candidate #1
        |
    139 ~             glib::ObjectExt::data(&obj, Some(cancellable), move |res| {
    140 +                 send.resolve(res);
    141 ~             });
        |
    help: disambiguate the associated function for candidate #2
        |
    139 ~             WebResourceExt::data(&obj, Some(cancellable), move |res| {
    140 +                 send.resolve(res);
    141 ~             });
    ```

**Comment by sdroege** [comment]
> for example: `WebViewBuilder::new()` should be public, but the new is not:

Why should it be public? You usually use it via `WebView::builder()`.

> ```
> error[E0034]: multiple applicable items in scope
>    --> webkit2gtk/src/auto/web_resource.rs:139:17
>     |
> 139 |             obj.data(Some(cancellable), move |res| {
>     |                 ^^^^ multiple `data` found

Here the problem is a name conflict with `WebResourceExt` API. The most sensible thing to do here would probably be to rename the `WebResource` `data` function to something else via `Gir.toml` as otherwise your users will have exactly the same problem.

**Comment by ttys3** [comment]
Oops, did not noticed there's `WebView::builder()`, since prev used `WebViewBuilder::new()` . thanks for the tip.

the second issue has been fixed via Gir.toml rename
