### ISSUE TITLE
Suggestion: Remove dox feature in favor of rustc args

### ISSUE THREAD

**Issue by AaronErhardt** [gtk-rs/gir#1454]
Cargo features are supposed to be additive, but the "dox" feature isn't. Compiling with "dox" skips compile time checks for the underlying C libraries and therefore should not be enabled during normal development.

A better solution would be to use a "docsrs" or "dox" config argument for rustc directly. This seems to be what most crates do and it's also what [docs.rs recommends](https://docs.rs/about/builds#cross-compiling). This would make possible to use `--all-features` again and removes the need to pass the "dox" feature to the dependencies.

The code for conditional compilation would only change from `#[cfg(feature = "dox")]` to `#[cfg(dox)]`.

This doesn't only affect the gtk4 crate, so feel free to move the issue if there's a better repo for this topic.

**Comment by sdroege** [comment]
@AaronErhardt Do you want to work on adding this?

**Comment by AaronErhardt** [comment]
Yes, I think I should have some time to come up with a PR in the next few days.
