### ISSUE TITLE
Introduce code chunks

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#150]
Possible preparation for #136.

Code chunks is objects that can convert yourself into code and forms treelike hierarchy.
For example `Block` contains list of other chunks, `Function definition` contains list of argument chunks and return value.
Distant goal: generate `function definition` and `ffi_function_definition` on analyze, do some transformation on them (ex. move output parameters to return values, group functions to `Impl` or `Trait` chunks).
On code generation phase generate function description (based on `function definition`) and body chunks (based on `function definition` and `ffi_function_definition`) and write them to file.

Nearest goal: make `function_body::Builder` generate body chunks and write them without change resulting code.

Tasks for nearest goal
- [x] Silly(just text) chunks for commented function body
- [x] Silly chunks for body with direct call with fallback to current Builder for 
more advanced cases.
- [x] Chunks with `name`, `TypeId` e.t.c. for direct call.
- [x] Chunks for other body cases and remove current Builder.

Next can be done realization throws and other out cases on chunks (#130, #144)
After this need check and remove formatters that can be replaced with use `rustfmt`.

**Comment by gkoz** [comment]
Not sure what "sully" means here.

**Comment by gkoz** [comment]
`rustfmt` is more mature now but it chronically can't deal with lines that are too long. We might forgo any attempts at formatting, make sure each line is below 100 and let rustfmt do the rest.

**Comment by EPashkin** [comment]
At first Parameters chunk for calling FFI just be `CallParam(String)` and call `translate_to_glib` made by chunk creator (same as current Builder).
Next chunk will be changed to `CallParam{name: String, typ: TypeId, ...}` and call `translate_to_glib` yourself on writing chunk code.

**Comment by EPashkin** [comment]
I forgot about `rustfmt`, will try it after nearest goal, as IMHO all needed formating already present.

**Comment by EPashkin** [comment]
Checked `rustfmt`. Now it builds for me (with some failing self-tests). Bad that it only nightly, so it will only external tools until `libsyntax` stabilized.
As it formats entire project from start file it good as external tool.

**Comment by gkoz** [comment]
> Checked rustfmt. Now it builds for me (with some failing self-tests). Bad that it only nightly, so it will only external tools until libsyntax stabilized.

They've just merged a PR to make it work on stable.
