### ISSUE TITLE
Bug : wrong type conversions making compilation on poppler-rs fail on windows

### ISSUE THREAD

**Issue by Doublonmousse** [gtk-rs/gir#1605]
Copy of https://gitlab.gnome.org/World/Rust/poppler-rs/-/issues/1

Downstream `poppler_rs` cannot compile because of a type mismatch on windows (on one side a `libc::clong` that is i32 on windows and on the other side the type of `time_t` that is seen as i64).

According to bilelmoussaoui the type issue comes from this repo and types conversions :  https://gitlab.gnome.org/World/Rust/poppler-rs/-/issues/1#note_2242804

> The issue comes from the conversion from `time_t` which is platform dependent (can be i32 or i64) and the code generator always generates it as `c_long` which is wrong.

**Comment by sdroege** [comment]
The code generator is generating it as `libc::time_t` nowadays. See https://github.com/gtk-rs/gir/pull/1562. Sounds like you'll have to update gir :) If it shows up as `ulong` in the .gir file, you probably have to update gobject-introspection and get a new .gir file.

**Comment by bilelmoussaoui** [comment]
No, this is a gir bug. The gir was updated to contain the commit you mentioned and if you check the ffi function below
```rust
    pub fn poppler_document_set_modification_date(
        document: *mut PopplerDocument,
        modification_date: time_t,
    );
```
it is generated correctly. Although, the safe wrapper is generated using
```rust
    #[doc(alias = "poppler_document_set_modification_date")]
    pub fn set_modification_date(&self, modification_date: libc::c_long) {
        unsafe {
            ffi::poppler_document_set_modification_date(self.to_glib_none().0, modification_date);
        }
    }
```

**Comment by bilelmoussaoui** [comment]
never mind, it was actually the gir file that was outdated.
