### ISSUE TITLE
Formatting documentation

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#203]
For now, here is the list of things we need to update inside the parsed documentation:

- [x] Transform code blocks "|[&lt;!-- language="C" --&gt; // some code ]|" into "```C // some code ```".
- [x] C-types should be replaced by their rust equivalent (example "GtkWindow" into "Window").
- [x] Replace "@%s" values by "`%s`" (example "@accel_mods" into "`accel_mods`").

The following one will be done later:
- [x] Replace objects' properties by their rust equivalent (enums certainly) (example "#GtkAboutDialog:license-type"). -> it has been partially done

**Comment by gkoz** [comment]
I wonder if it's feasible to parse the docs as markdown. And then output rustddoc-friendly markdown again.

**Comment by GuillaumeGomez** [comment]
We won't know until we try unfortunately. :-/

**Comment by gkoz** [comment]
This page seems to describe the syntax best: https://wiki.gnome.org/Projects/GTK%2B/DocumentationSyntax/Markdown
There's also https://developer.gnome.org/gtk-doc-manual/stable/documenting_syntax.html.en

**Comment by gkoz** [comment]
Alright parsing markdown is probably pointless. Rustdoc understands it. It's the "extensions" that need to be handled. So the list can just be updated with this new information about the extensions syntax.

**Comment by gkoz** [comment]
Okay so the custom syntax list is:

>    Use `function()` to refer to functions or macros which take arguments.
    Use `@param` to refer to parameters. Also use this when referring to parameters of other functions, related to the one being described.
    Use `%constant` to refer to a constant, e.g. `%G_TRAVERSE_LEAFS`.
    Use `#symbol` to refer to other types of symbol, e.g. structs and enums and macros which don't take arguments.
    Use `#Object::signal` to refer to a GObject signal.
    Use `#Object:property` to refer to a GObject property.
    Use `#Struct.field` to refer to a field inside a structure and `#GObjectClass.foo_bar()` to refer to a vmethod.
