### ISSUE TITLE
Provide TreeSortable

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#223]

**Comment by gkoz** [comment]
Specifics?

**Comment by GuillaumeGomez** [comment]
It's just a reminder for me. However, I think I'll do like you said: provide a hand written file.

**Comment by EPashkin** [comment]
This fixed by https://github.com/gtk-rs/gtk/pull/261 ?

**Comment by EPashkin** [comment]
@GuillaumeGomez, IMHO this issue was solved?

**Comment by GuillaumeGomez** [comment]
Wo indeed. Let's burry it definitely. ;)
