### ISSUE TITLE
Override parameter direction

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/gir#225]
[gtk_text_iter_attributes](https://developer.gnome.org/gtk3/stable/GtkTextIter.html#gtk-text-iter-get-attributes) looks like it doesn't just overwrite `values` but modifies it. It should probably be `inout` yet we get

``` xml
          <parameter name="values"
                     direction="out"
                     caller-allocates="1"
                     transfer-ownership="none">
            <doc xml:space="preserve">a #GtkTextAttributes to be filled in</doc>
            <type name="TextAttributes" c:type="GtkTextAttributes*"/>
          </parameter>
```

This isn't particularly high priority as `TextAttributes` seem pretty obscure.

**Comment by EPashkin** [comment]
Found only one case for this so far, seems its very rare and unneeded.
Function was implemented manually in same time.
I close issue
