### ISSUE TITLE
Signal trampolines returning string.

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#233]
In gtk some callback return `utf8` (`gchar*`), current trampolines format don't support it.

Found two of these:
`GtkComboBox`: `format-entry-text`
`GtkScale`: `format-value`

May be problem with other pointer returning signals.

**Comment by gkoz** [comment]
I'm not seeing a problem yet. They seem to have transfer annotations and `to_glib_full` should work on `String`.

**Comment by EPashkin** [comment]
Oh, then good.
