### ISSUE TITLE
Signals with 'out' parameters

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#234]
2 of these in gtk:
- [x] https://developer.gnome.org/gtk3/stable/GtkOverlay.html#GtkOverlay-get-child-position
- [x] https://developer.gnome.org/gtk3/stable/GtkSpinButton.html#GtkSpinButton-input

and one `inout`:
- [x] https://developer.gnome.org/gtk3/stable/GtkEditable.html#GtkEditable-insert-text

IMHO it just stay manual for now.

**Comment by gkoz** [comment]
Seems reasonable.

**Comment by vhakulinen** [comment]
Any plans for the "get-child-position" signal?

**Comment by EPashkin** [comment]
@vhakulinen Thanks for reminder.

**Comment by EPashkin** [comment]
Ok. this done now
