### ISSUE TITLE
Signals returning Inhibit as gboolean

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#244]
# Closures for these must return `Inhibit` not `bool`.

RangeExt::change-value

gkoz: It appears a significant number of signals need Inhibit, with varying degrees of certainty:
- `EntryCompletion`
- `Label::activate-link` (?)
- `LinkButton::activate-link`
- `MenuShell::move-selected`
- `Notebook::change-current-page` and others (??)
- `Paned` (?)
- `SpinButton::output` (?)
- `StatusIcon::size-changed`
- `Switch::state-set`
- `ToolItem::create-menu-proxy`
- `Toolbar`

Signals with `Inhibit` detected by `_gtk_boolean_handled_accumulator` in `gtk` sources
~~`AboutDialog`: activate-link~~
`AccelGroup`: accel-activate (not meant to be used by applications)
~~`EntryCompletion`
insert-prefix
match-selected
cursor-on-match
`GLArea`: render (already manual with Inhibit)~~
`IMContext`
retrieve-surrounding
delete-surrounding
~~`Label`: activate-link
`LinkButton`: activate-link
`MenuShell`: move-selected~~
`Overlay`: get-child-position (output)
`PrintOperation`
paginate (?)
preview
~~`Range`: change-value (already manual with Inhibit)~~
`Socket`: plug-removed
`SpinButton`: output (already manual with Inhibit)
~~`Switch`: state-set
`TextTag`: event
`TextView`: extend-selection
`Toolbar`: popup-context-menu
`ToolItem`: create-menu-proxy
`TreeView` all already manual but not Inhibit
test-expand-row
test-collapse-row~~
`Widget` (+ already manual with Inhibit, - not added, some added but return `bool`)
~~draw +
mnemonic-activate +
focus +
keynav-failed +
event +
button-press-event +
button-release-event +
touch-event + (?)
scroll-event +
motion-notify-event +
delete-event +
destroy-event +
key-press-event +
key-release-event +
enter-notify-event +
leave-notify-event +
configure-event +
focus-in-event +
focus-out-event +
map-event +
unmap-event +
property-notify-event +
selection-clear-event - (+)
selection-request-event - (+)
selection-notify-event - (+)
proximity-in-event +
proximity-out-event +
drag-failed - (+)
drag-motion - (-)
drag-drop - (-)
visibility-notify-event - (+)
window-state-event +
damage-event +
grab-broken-event +
query-tooltip currently not Inhibit
popup-menu currently not Inhibit
show-help currently not Inhibit (+)
can-activate-accel currently not Inhibit~~

UPDATE: Issue fixed but in temporary way.
Not all Inhibit functions generated.

**Comment by EPashkin** [comment]
Not sure if we need add `Inhibit` to `library::Fundamental` it depends has any function incoming `bool` that works as `Inhibit`, I don't know any.

**Comment by EPashkin** [comment]
Updated signal list from `gtk` sources (only by accumulator type, not checked signal descriptions)

**Comment by EPashkin** [comment]
@gkoz, checked `Inhibit` by docs.
Found possible mistake `Widget::show-help` IMHO its `Inhibit`.
Not sure about `PrintOperation::paginate` but seems its just `bool`
`Widget::touch-event` has no doc

**Comment by gkoz** [comment]
Yeah I think for signals we can just look at source for clarification and if the accumulator is `_gtk_boolean_handled_accumulator` use `Inhibit`.

**Comment by GuillaumeGomez** [comment]
I think we can close this issue now.
