### ISSUE TITLE
Cannot regenerate gtk files

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#259]
I updated gir to last master branch update. When I run:

```shell
cargo run --release -- -c ../gtk/Gir.toml -d ../gir-files -o gtk
```

I get the following error:

```shell
"../gtk/Gir.toml": 452:6-452:6 error: expected a newline after table definition
```

Any idea?

PS: I also had to change the line 63 in `src/statistics.rs` because Duration doesn't implement `Display` trait (so I added `.as_secs()`).

**Comment by EPashkin** [comment]
Can you push your gtk master?

**Comment by GuillaumeGomez** [comment]
It's the same than gtk-rs/gtk. That's why I'm surprised.

**Comment by EPashkin** [comment]
Confirmed that after `cargo update` `std::time::Duration: std::fmt::Display` don't have display

**Comment by GuillaumeGomez** [comment]
Do you want me to open a PR for this change?

**Comment by EPashkin** [comment]
If you can.
Seems toml also changed parser, so comment need moved
```
 [[object]]
 name = "Gtk.Editable"
 status = "generate"
-    [[object.signal]] #out #manual
-    pattern = ".+"
-    ignore = true
+[[object.signal]]
+pattern = ".+"
+ignore = true #out #manual
```

**Comment by GuillaumeGomez** [comment]
Ok, I'll open a PR for gtk as well.

**Comment by EPashkin** [comment]
Whitespace change in my diff was mistake.
