### ISSUE TITLE
Unexpected element <doc-version>

### ISSUE THREAD

**Issue by esfomeado** [gtk-rs/gir#268]
```
 Running `target/release/gir -c Gir_Gtk.toml -d ../gir -o gtk`
```

thread 'main' panicked at 'src/parser.rs:740 Unexpected element doc-version in ../gir/Gdk-3.0.gir:20712:9', src/parser.rs:53
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/release/gir -c Gir_Gtk.toml -d ../gir -o gtk` (exit code: 101)

**Comment by gkoz** [comment]
Sorry about that it should be pretty easy to fix but for now we're sticking to [this set of girs](https://github.com/gtk-rs/gir-files) and supplying newer ones isn't guaranteed to work.
