### ISSUE TITLE
version::Version fail with single digit version

### ISSUE THREAD

**Issue by hfiguiere** [gtk-rs/gir#269]
If you have this in the Gir.toml
````
min_cfg_version = "230"
````

The build.rs generated contain:
````
let version = {
        "230.0"
};
````

Which in the end fails with pkg-config.
````
$ pkg-config --modversion gudev-1.0
230
````

The build output is:
````
error: failed to run custom build command for `gudev-sys v0.1.0 (file:///home/hub/source/gudev-rs/gudev-sys)`
process didn't exit successfully: `/home/hub/source/gudev-rs/gudev-sys/target/debug/build/gudev-sys-ed1f2ccef31fd523/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gudev-1.0 >= 230.0"` did not exit successfully: exit code: 1
--- stdout
Requested 'gudev-1.0 >= 230.0' but version of gudev-1.0 is 230
````

I tracked it all down to ````src/version.rs````.

This is the sample repository:
https://github.com/hfiguiere/gudev-rs

**Comment by hfiguiere** [comment]
Note: I manually fixed the file in the repository above to make it work. "cd gudev-sys && make gir" will reset it.

**Comment by gkoz** [comment]
I guess there might be no harm in chopping off the minor `.0`. This could also be necessary in the `cfg` directives though.

**Comment by EPashkin** [comment]
Added option to `Gir.toml` for single digit version. Not checked building `gudev-rs`.

**Comment by hfiguiere** [comment]
I'll try that tonight.
