### ISSUE TITLE
Gir generate &mut instead of &

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gir#277]
Hello.
I found a new bug in the generation of the `webkit2gtk` binding.
As you can see [there](https://github.com/antoyo/webkit2gtk-rs/blob/master/src/auto/navigation_action.rs#L23-L55), `gir` sometimes generate methods with `&mut` instead of `&`.
Could you please fix this?
Thanks.

**Comment by EPashkin** [comment]
.gir file don't says that this parameter not changed by lib (no `const` in type), so it generated &mut.
You can override parameter constness in config: https://github.com/gtk-rs/gtk/blob/master/Gir.toml#L329-L331

**Comment by antoyo** [comment]
Thanks.
