### ISSUE TITLE
ULong is unimplemented

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gir#283]
Hello.
I have many functions having a `ULong` type that could be implemented with the `c_ulong` (aka `u64`) type instead of being left unimplemented.
For instance:

``` xml
      <method name="get_length"
              c:identifier="webkit_dom_html_collection_get_length">
        <return-value transfer-ownership="none">
          <doc xml:space="preserve">A #gulong</doc>
          <type name="gulong" c:type="gulong"/>
        </return-value>
        <parameters>
          <instance-parameter name="self" transfer-ownership="none">
            <doc xml:space="preserve">A #WebKitDOMHTMLCollection</doc>
            <type name="DOMHTMLCollection" c:type="WebKitDOMHTMLCollection*"/>
          </instance-parameter>
        </parameters>
      </method>
```

should generate [this method](https://github.com/antoyo/webkit2gtk-webextension-rs/blob/2a91ddb9b5e5122c274cb460afd439056bbb9499/src/auto/dom_html_collection.rs#L27) instead of being left unimplemented.

Thanks.

**Comment by EPashkin** [comment]
@antoyo, seems it missed here: https://github.com/gtk-rs/gir/blob/master/src/analysis/rust_type.rs#L83
I don't remember, why it not added.
Can you add PR yourself (with `//maybe dependent on target system`)?

**Comment by antoyo** [comment]
I added the pull request #284.

**Comment by EPashkin** [comment]
Thanks

**Comment by gkoz** [comment]
The problem with `long` is that it's not consistent with either `i32`, `i64`, or `size` across platforms. Whatever native Rust type we pick it has to be cast back and forth. I intended to either handle this under #264, or handle integer range conversions (that includes `long` <-> `u64` and `int` <-> `u32` and so on) separately.

**Comment by gkoz** [comment]
This particular class actually shows why I'd like to handle `long`s on a case-by-case basis: the `length` and `item` methods [actually use `unsigned int`](https://github.com/WebKit/webkit/blob/1d8aaac1499167a5a7ebe7bbf436761831e03e69/Source/WebCore/dom/NodeList.h#L40-L41). Something went wrong in their generator and a `gulong` appeared. Naturally we'd want to use `u32` there right?

**Comment by antoyo** [comment]
We also need to implement `UShort`.

As far as I know, `short` <= `int` <= `long` so I am not sure which types to use in Rust.

**Comment by EPashkin** [comment]
@GuillaumeGomez, @gkoz 
May be we just use `libc::c_short`, `libc::c_long`, or reexport its as `gshort` and `gint` in every crate that need?
Wrong type in [NodeList](https://github.com/WebKit/webkit/blob/1d8aaac1499167a5a7ebe7bbf436761831e03e69/Source/WebCore/dom/NodeList.h#L40-L41) we need add manually anyway (or path .gir file)

**Comment by GuillaumeGomez** [comment]
Or make a PR to libc? I don't like creating our own types. `libc` ensures C types correspond correctly and I think we should try to remain in its scope for such things.

**Comment by EPashkin** [comment]
Don't understand what PR to libc might like :(
Using `libc::c_long` and other 3 types can be done easily. Almost same as #284.
I make PR as it need slightly more changes.

**Comment by GuillaumeGomez** [comment]
I did one recently to add some type for fd passing. The CI is so well done
that you just have to check it to know what's missing.

Le 18 déc. 2016 9:09 PM, "Evgenii Pashkin" <notifications@github.com> a
écrit :

**Comment by GuillaumeGomez** [comment]
Actually, `libc::c_ulong` is already implemented.

**Comment by GuillaumeGomez** [comment]
Seems like it's fixed so I'll close it.
