### ISSUE TITLE
How to generate unstable functions?

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gir#285]
Hello.
In webkitdom, there are many unstable functions: these are in the files ending with `Unstable.h` and they are not listed in the `.gir` file.
So, I wonder how to generate these functions.
For instance, [here](https://github.com/antoyo/webkit2gtk-webextension-rs/blob/master/src/dom_dom_window.rs#L20) is an unstable function that I manually implemented.
Thanks for your help.

**Comment by EPashkin** [comment]
IMHO manual write both sys and functions is only way to go.

**Comment by gkoz** [comment]
If there are many such functions it might be most efficient to find out (ask someone at that project) how to generate a gir which would include the unstable parts.
