### ISSUE TITLE
Child properties

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#287]
There is any reason for not generate for child properties get/set-ers?
Ex. for `Grid` function like `set_child_height<T: IsA<Widget>>(&self, child:&T, value: i32)` and implementing it with `gtk_container_child_set_property`

**Comment by EPashkin** [comment]
Seems no info about child properties in `Gtk-3.0.gir` file 😭

**Comment by gkoz** [comment]
We don't handle any properties yet, implementing usual properties feels like a logical first step and they are defined in girs.

**Comment by EPashkin** [comment]
IMHO its different issues and this better handled first by these reasons:
Child properties can't be generated by girs and need be done manually, so it will be good test for properties itself;
For normal properties we need solve https://github.com/gtk-rs/gir/issues/139 first as many classes  already has get/set as functions with same names (and doing same work);
If for properties used different method (not adding `get_<prop_name>`), then we need invent it first.

**Comment by gkoz** [comment]
Yeah, that should work too.

**Comment by EPashkin** [comment]
Closing this issue in favor of GTKs.
