### ISSUE TITLE
Use a real Volatile struct

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/gir#288]
We might want to import `Volatile` from the [`volatile` crate](https://crates.io/crates/volatile) in the sys crates. It doesn't have a constructor though, so @antoyo you might still not be entirely happy with it.
https://github.com/gtk-rs/sys/issues/25#issuecomment-252539171

**Comment by antoyo** [comment]
I am not sure why we need a wrapper for the `ref_count` volatile fields.
Could you please explain me why?

I believe most of the time, the user of the API will not change this value directly: it will be updated by the `g_object_ref` function.
And if an update is needed, perhaps [`write_volatile`](https://doc.rust-lang.org/std/ptr/fn.write_volatile.html) from the standard library could be used.

Moreover, it seems to be used only in the `sys` crates, right?

Am I missing something?

**Comment by gkoz** [comment]
Generally, it seemed a good idea to statically prevent inappropriate accesses to volatile fields at the sys crates level. The higher level crates so far haven't touched such fields because the API functions take care of that indeed.

I suspect `mem::swap` can subvert that restriction anyway so it may be a bit pointless. Still, like in the privacy issue it seems wrong to just ignore the `volatile` thing. Do you think we can find some middle ground here?

**Comment by gkoz** [comment]
I guess changing `Volatile` to be a transparent wrapper could provide some notice while leaving the users with responsibility to actually do the right thing. Something like

```rust
#[repr(C)]
pub struct Volatile<T> {
    pub volatile: T,
}

impl<T> Volatile<T> {
    // these would provide pointers to supply into read/write_volatile
    pub fn as_ptr(&self) -> *const T { &self.volatile }
    pub fn as_mut_ptr(&mut self) -> *mut T { &mut self.volatile }
}
```

**Comment by antoyo** [comment]
Having a public field would help me.

I have another idea, but I am not sure if it is good thought and it only works for the `ref_count` field.

My issue is that I want to create a const struct with a `ref_count` of `-1` (meaning not ref counted).
So perhaps we could create an enum like the following:

```rust
enum RefCount {
    NoRefCount,
    RefCount(Volatile),
}
```

I don't think creating a const struct with a ref count make sense, so the `Volatile` field could stay abstract.

**Comment by gkoz** [comment]
Eh, I don't think this kind of special treatment for some fields in the sys crates is going to work.

**Comment by antoyo** [comment]
Ok, then if we could make the field public, [this code](https://github.com/antoyo/gdbus-rs/blob/master/src/macros.rs#L343) would work.

**Comment by EPashkin** [comment]
`Volatible` break ABI on at minimum on Windows 32, so it was removed in #579 completely.
