### ISSUE TITLE
Some trampoline parameter can be null

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gir#291]
Hello.
There are some parameters of trampoline that can be null (like the `redirected_response` parameter of the [`send-request` signal](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebPage.html#WebKitWebPage-send-request)) so the use of `from_glib_none()` causes a panic when the parameter is null.
[See generated code here.](https://github.com/antoyo/webkit2gtk-webextension-rs/blob/master/src/auto/web_page.rs#L123)
Thanks to fix this issue.

**Comment by EPashkin** [comment]
I added non finally solution https://github.com/EPashkin/gir/tree/nullable_signal_parameters.
@antoyo check it please.
Config change:
```diff
--- a/Gir.toml
+++ b/Gir.toml
@@ -16,7 +16,6 @@ generate = [
     "WebKit2WebExtension.WebEditor",
     "WebKit2WebExtension.WebExtension",
     "WebKit2WebExtension.WebHitTestResult",
-    "WebKit2WebExtension.WebPage",
 ]
 
 manual = [
@@ -517,3 +516,12 @@ module_name = "uri_request"
 name = "WebKit2WebExtension.URIResponse"
 status = "generate"
 module_name = "uri_response"
+
+[[object]]
+name = "WebKit2WebExtension.WebPage"
+status = "generate"
+    [[object.signal]]
+    name = "send-request"
+        [[object.signal.parameter]]
+        name = "redirected_response"
+        nullable = true
```

**Comment by antoyo** [comment]
That's perfect.
Thanks.
