### ISSUE TITLE
Generate functions

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gir#295]
Hello.
Is there a way to generate a wrapper for functions (not methods)?
For instance, in gnome-keyring, there are [many functions](https://developer.gnome.org/gnome-keyring/stable/gnome-keyring-Simple-Password-Storage.html).
Is there a way to tell `gir` to generate a wrapper for these functions?
Thanks.

**Comment by EPashkin** [comment]
Currently `git` can generate only object methods.
I will think way to do it for functions

**Comment by EPashkin** [comment]
But it won't help you much with `gnome-keyring`, as almost all functions in `Simple Password Storage` has variable parameters (`...`), `Keyrings` has callbacks, e.t.c.

**Comment by EPashkin** [comment]
Also `gnome-keyring` it deprecated in favor of `libsecret`

**Comment by sdroege** [comment]
How this is handled in the C# bindings code generator (and IIRC also in Vala), is that all the free functions are placed inside the main namespace or similar (i.e. a static class with static methods in C#, named after the namespace).

For here, maybe they can just be placed as free functions in src/auto/mod.rs? Then they would be available as $crate_name::$function_name by default.

If you agree with that, or have other suggestions, I could work on that. I know more or less what needs to be done code-wise here.

**Comment by sdroege** [comment]
@EPashkin Functions for interfaces seems slightly different though. Shouldn't those be just mapped to impls of the same functions in the interface traits? Functions for interfaces have some kind of "owner" (the interface), while free functions don't really.

**Comment by EPashkin** [comment]
@sdroege Interfaces functions handled already in #309.
As for free functions we IMHO need `src/auto/functions.rs` that will be reexpored in main module.
In gtk we already exported [gtk_drag_finish](https://github.com/gtk-rs/gtk/blob/master/src/drag_context.rs) as part of trait for `gdk::DragContext` may be others too.
Also we need way to control generation, maybe with fictive object like "Gtk.*"

**Comment by sdroege** [comment]
Why src/auto/functions.rs instead of directly src/auto/mod.rs? I don't mind either way in any case

For overriding, "Gtk.drag_finish" would work. In the GIR it's organized the same way. It's under the Gtk namespace, and a XML node with the name drag_finish.

**Comment by EPashkin** [comment]
I prefer `auto/mod.rs` contains only reexports.
As these function will need manual reexport on crate level it all same where to put them

**Comment by sdroege** [comment]
OK, let's go with that then :)

**Comment by EPashkin** [comment]
@antoyo  There something need be done for this issue?

**Comment by antoyo** [comment]
I think we can close this issue.
