### ISSUE TITLE
Generate getters and setters for properties

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#304]
As shown in https://github.com/gtk-rs/gtk/issues/423 is better generate getters/setters for object properties.
Don't generate function for parent properties and if these functions already implemented directly.
IMHO blocked by #139.
Related to #136

**Comment by EPashkin** [comment]
@GuillaumeGomez, here some problem with generating:
`Widget` have property "expand" that converted to 2 functions:
```
    fn get_expand(&self) -> bool {
        let mut value = Value::from(&false);
        unsafe {
            gobject_ffi::g_object_get_property(self.to_glib_none().0, "expand".to_glib_none().0, value.to_glib_none_mut().0);
        }
        value.get().unwrap()
    }

    fn set_expand(&self, expand: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "expand".to_glib_none().0, Value::from(&expand).to_glib_none().0);
        }
    }
```
`ToolItem` (child of `Widget`) have same (but direct) functions and its will be hidden as parent already has it.
It's normal?
```
    fn get_expand(&self) -> bool {
        unsafe {
            from_glib(ffi::gtk_tool_item_get_expand(self.to_glib_none().0))
        }
    }
    fn set_expand(&self, expand: bool) {
        unsafe {
            ffi::gtk_tool_item_set_expand(self.to_glib_none().0, expand.to_glib());
        }
    }
```

**Comment by GuillaumeGomez** [comment]
`ToolItem` has [both functions](https://developer.gnome.org/gtk3/stable/GtkToolItem.html#gtk-tool-item-set-expand). So I wonder: should we use specialization over this? Or maybe put the properties into a trait?

**Comment by EPashkin** [comment]
It was that I saying :wink:
My questing was: can we hide direct functions if parent has equivalent property?
Sorry, don't understand your comment about specialization and trait.

**Comment by EPashkin** [comment]
I can change properties functions to "get_property_expand" but IMHO it will be too long

**Comment by GuillaumeGomez** [comment]
Ah my bad. 😱 

So specialization:

```rust
#![feature(specialization)]

use std::fmt;

struct Foo;

trait Bar1<T> {
    fn bar(t: T);
}

impl<T> Bar1<T> for Foo {
    default fn bar(t: T) {
        println!("Foo");
    }
}

impl<T: fmt::Debug> Bar1<T> for Foo {
    fn bar(t: T) {
        println!("Foo({:?}", t);
    }
}
```

And trait: just create a trait where you put properties.

We could even mix both solution and create `PropertyTrait` (or whatever for the name) and set all methods as default for the higher level.

**Comment by EPashkin** [comment]
As your traits don't implemented on direct object IMHO we can use specialization directly.
Also we need know that function was implemented in parent and re-implement parent trait.

If we add `PropertyTrait` with same constrains as `*Ext`, and both of then has same function (or one of it and any "parent" of other) then user that tried use function get error.

**Comment by GuillaumeGomez** [comment]
Don't you already have some kind of hierarchy system in gir? It would be very useful and would make such a thing very easy.

**Comment by EPashkin** [comment]
Sorry, I still don't understand your idea, can you give example with `get_expand` and `WidgetExt` vs `ToolItemExt`?

**Comment by GuillaumeGomez** [comment]
You set `get_expand` and `set_expand` as default in `WidgetExt` and the equivalent ones in `ToolItemExt` would "overwrite" them. However, I'm not sure if specialization works on methods from different traits...

Otherwise, if we know that the same method is implemented in a child widget, we can try to downgrade the current object and then call the method. However I don't like this idea since you *might* want to call the `WidgetExt` function and not `ToolItemExt` one.

Not an easy problem... :-/

**Comment by EPashkin** [comment]
As far I know, specialization don't work on different trait.
If you wan't your can call any of trait function like that `WidgetExt::get_expand(&toolItem)` (this way used it examples to remove duplicate function error).
I also don't see reason to calling parent function if child has it, but I hope that both function go to one place it C code.
Currently I don't see possibility keep `get_expand` in `ToolItemExt` if I add `get_expand` to `WidgetExt`

**Comment by EPashkin** [comment]
[Test program](https://gist.github.com/EPashkin/61d755e00638eac9555329baed9b9b9a) shows that `expand`'s don't equivalent 😭 I hope that error in my test code.
Also [test](https://gist.github.com/EPashkin/7427f96e9cb490689a556828bea0ec60) shows that property much slower:
```
10000000 repeats
Timing information for Test:
  Direct - 1 * 148.7ms = 148.7ms (0.3%)
  Property - 1 * 53.0s = 53.0s (99.7%)
```
May be we really need change naming to `set_property_expand`

**Comment by GuillaumeGomez** [comment]
It's too bad but I think too...

**Comment by EPashkin** [comment]
@GuillaumeGomez, when checking if trait has both property and direct functions,
I found cases when property was added sooner that direct function. Currently I add `#[cfg(not(feature = "v3_6"))]` (see https://github.com/gtk-rs/gtk/pull/428/commits/d62b584460fa766ae1b4b0361c8d0db77e60dfeb).
May be it was wrong and I need only restore property without `not` as user program may work under different version of gtk?

**Comment by GuillaumeGomez** [comment]
I'm not sure this is a good idea... I think that in this case, we should maybe add documentation that warns user that the method is also implemented in the parent scope so they should call it like:

```rust
ToolItemExt::the_common_method(&tool);
```

**Comment by EPashkin** [comment]
It not related to parent. As example Application has
```
impl Application {
     #[cfg(feature = "v3_6")]
    pub fn get_active_window(&self) -> Option<Window> {
        unsafe {
            from_glib_none(ffi::gtk_application_get_active_window(self.to_glib_none().0))
        }
    }

    #[cfg(not(feature = "v3_6"))]
    pub fn get_property_active_window(&self) -> Option<Window> {
        let mut value = Value::from(None::<&Window>);
        unsafe {
            gobject_ffi::g_object_get_property(self.to_glib_none().0, "active-window".to_glib_none().0, value.to_glib_none_mut().0);
        }
        value.get()
    }
}
```
property func don't conflict with direct due renaming, but currently property function unavailable on v3_6 or greater, so client program, that need active window must use `get_active_window` or `get_property_active_window` depending current version.
If I remove `not` then `get_property_active_window` will be always visible and client program can use it if program minimum version 3.4 without versioned logic

**Comment by GuillaumeGomez** [comment]
Oh I see, my bad! Then yes, I think this is the better choice.

**Comment by EPashkin** [comment]
Sorry, what better `not` or without `not` ?

**Comment by GuillaumeGomez** [comment]
With `not`.

**Comment by GuillaumeGomez** [comment]
Arf... I actually don't know. >< Both suggestions seem good to me. `not` can induce potential future errors and `get_property_active_window` could lose people looking for the function... I actually think the second might be better.

**Comment by EPashkin** [comment]
Ok, then I stay with current version.

**Comment by EPashkin** [comment]
Almost all part merged, so I close this issue.
