### ISSUE TITLE
Allow override nullable return value when the return type is Result<T, Error>

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gir#306]
Hello.
It seems that it is not possible to use `nullable = true` for a return value when its type is `Result<T, Error>`.
For instance, I would like [this method](https://github.com/antoyo/webkit2gtk-webextension-rs/blob/master/src/auto/dom_element.rs#L116) to be able to return `None`.
So, using `nullable = true` should generate the type `Result<Option<DOMElement>, Error>`, but `gir` currently generates the type `Result<DOMElement, Error>`.
Could you please fix this issue?
Thanks.

**Comment by EPashkin** [comment]
Hm, seems it don't work on `Result`'s.  I fix it.
```
[[object]]
name = "WebKit2WebExtension.DOMElement"
status = "generate"
module_name = "dom_element"
    [[object.function]]
    name = "query_selector"
        [object.function.return]
        nullable = true
    [[object.function]]
    name = "has_attributes"
         [object.function.return]
         nullable = true
```

**Comment by EPashkin** [comment]
@antoyo, I done fix, but when I think more about your problem, I don't understand why you need this.
Normally in glib, functions, that can fails, return NULL only if error occurs.

**Comment by EPashkin** [comment]
Confirmed by source code that `webkit_dom_element_query_selector` also return NULL only for errors.

**Comment by antoyo** [comment]
From my tests, `NULL` is returned when querying something that is not in the document.
I had a `panic`, so I debugged the generated code.
I printed both the value and the error and both were set at 0.
Can you show me the source code you found?
[From this](https://github.com/WebKit/webkit/blob/a8ed961453afd0aad57ab4ed07b1249230fc7f2a/Source/WebCore/dom/SelectorQuery.cpp#L192) I can see that there is the possibility that `NULL` is returned (if `execute` does not write to the `output`, for instance).

**Comment by EPashkin** [comment]
From [same repo](https://github.com/WebKit/webkit/blob/d4bc8ca7f16396d3983fe4e80674c528dbf202ec/Source/WebKit2/WebProcess/InjectedBundle/API/gtk/DOM/WebKitDOMElement.cpp#L993).
Currently don't see how it get to your function

**Comment by antoyo** [comment]
I am not sure if I used the right path (I only searched function names on GitHub), but here is the path I followed:

* https://github.com/WebKit/webkit/blob/d4bc8ca7f16396d3983fe4e80674c528dbf202ec/Source/WebKit2/WebProcess/InjectedBundle/API/gtk/DOM/WebKitDOMElement.cpp#L1001
* https://github.com/WebKit/webkit/blob/556602b330b32a87e5decc257fd1ba5d2463a4dd/Source/WebCore/dom/ContainerNode.cpp#L865
* https://github.com/WebKit/webkit/blob/a8ed961453afd0aad57ab4ed07b1249230fc7f2a/Source/WebCore/dom/SelectorQuery.cpp#L192

**Comment by EPashkin** [comment]
@antoyo, then you really need Result<Option<>>, I merge PR after your confirm that it works.
