### ISSUE TITLE
Don't generate call to to_glib_none() for RGBA

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gir#355]
Currently, `gir` generates calls to `to_glib_none()` for `gdk::RGBA`.
However, `gdk::RGBA` is a synonym for `gdk_sys::GdkRGBA` so that does not make sense: it should not call this translate method.

There's also the issue with `Option<gdk::RGBA>`: how do you convert this to a `*const GdkRGBA`?
I used this function:
```rust
fn option_to_ptr<T>(value: Option<&T>) -> *const T {
    match value {
        Some(value) => value as *const _,
        None => ptr::null(),
    }
}
```
But surely there's a better way?

Thanks to fix this isuse.

**Comment by EPashkin** [comment]
`to_glib_none` works on `Option<&T>` too

**Comment by antoyo** [comment]
Epashkin: only if `T` implements `ToGlibPtr` which is not the case here.

**Comment by EPashkin** [comment]
And [`gdk::RGBA`](https://github.com/gtk-rs/gdk/blob/master/src/rgba.rs) now not synonym and implemented `ToGlibPtr` for both const and mut pointers

**Comment by antoyo** [comment]
Ah ok, so I believe this is not an issue anymore.
