### ISSUE TITLE
Add config options to hide function doc

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#356]
Gir should generate `#[doc(hidden)]` for functions marked with it.
- [ ] Child property ([main reason](https://github.com/gtk-rs/gtk/pull/496#issuecomment-298170503))
- [ ] Normal function
- [ ] Trampoline  ??

Proposed option example `hide_doc = true`

**Comment by GuillaumeGomez** [comment]
`hide_doc` seems like we're only hiding the doc and not the function *in* the docs. I propose `doc_hidden`. :)

**Comment by EPashkin** [comment]
Ok

**Comment by GuillaumeGomez** [comment]
Well, it's up to debate. If you don't like the idea or if you have a better one, don't hesitate to propose it. 😉

**Comment by EPashkin** [comment]
Your reason valid, so `doc_hidden` better. We can change it later if there better name appeared

**Comment by EPashkin** [comment]
Also maybe need add these option to properties added in https://github.com/gtk-rs/gtk/pull/481

**Comment by EPashkin** [comment]
Now I think that hiding function not best idea and better use some manual deprecation after #357 fixed.
But since this will require a lot of work this PR still actual as can be easily implemented and can work as mark to future deprecation.

**Comment by EPashkin** [comment]
I will work on this PR tomorrow, if you won't start first 😉

**Comment by GuillaumeGomez** [comment]
I don't plan to, I need to catch up on my missing sleep. But I'll work on it monday if you didn't do it before! :p
