### ISSUE TITLE
Add configuration for marking bool-returning functions as error indication

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#368]
There are many functions all over the place that return a boolean, and this being true/false indicates whether the function was successful or not. Not all of them are also returning an actual value via out-parameter, but instead have their side-effects as only result.

I'd suggest adding a configuration for the .toml file for these functions ("bool_return_is_error"?), and converting them into Result<(), E> to be able to use try! and the ? operator.

Question now is what to put into the E. We don't have anything meaningful to put there as the C library does not give any further information. But using () is also not very satisfying. As such I would suggest passing a type to "bool_return_is_error".

Just what to pass to the constructor? Nothing? Or we could pass file name, line number of where it happens. We could pass a &'static str for the (C or Rust) function name.

Any comments, ideas, ...?

**Comment by EPashkin** [comment]
We can add `glib::BoolError(pub &'static str)` and create it with `"type::name"` or `"trait::name"`.
As alternative we can define error type in manual way and write it name in `bool_return_is_error`.
But IMHO it is not worth the effort.
Anyway not need bother with file name and line number as standard backtrace contains both.

**Comment by EPashkin** [comment]
By backtrace I mean https://github.com/brson/error-chain

**Comment by sdroege** [comment]
That would also work and seem simpler, yes. Let's go with glib::BoolError(pub &'static str) for the time being.

I'll work on this after the other pull requests and the free functions.

**Comment by EPashkin** [comment]
Thank you in advance.

**Comment by sdroege** [comment]
> By backtrace I mean https://github.com/brson/error-chain

You would like glib to depend on error-chain? I would just implement Debug, Display and Error for the new glib::BoolError type to keep dependencies small.

**Comment by EPashkin** [comment]
User can use this crate for error processing and it collect stacktrace on initial error conversion.
We need implement these trait for `glib::BoolError` but IMHO currently don't need use error_chain in your crates

**Comment by sdroege** [comment]
Right, but for error-chain to produce a backtrace that starts in our bool-returning function, glib::BoolError would have to use error-chain, or not?

**Comment by sdroege** [comment]
Anyway, we seem to be on the same page here then. I'll implement that tomorrow or so, and then we can discuss about the details with actual code :)

**Comment by EPashkin** [comment]
As generated function only has one error return IMHO user only need know place in his code.

**Comment by EPashkin** [comment]
@sdroege Seems this done and can be closed?
