### ISSUE TITLE
GClosure

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gir#372]
I talked about `GClosure` with @GuillaumeGomez today and while I looked at its [documentation](https://developer.gnome.org/gobject/unstable/gobject-Closures.html), I found out it might be interesting to use:
> Closures allow the callee to get the types of the callback parameters, which means that language bindings don't have to write individual glue for each callback type.

I understand that we might not want to change `gir` to use that since what we have currently works (and might be even more efficient than using `GClosure`).

However, supporting `GClosure` will be useful to generate functions that has a parameter of this type.

**Comment by GuillaumeGomez** [comment]
For context, I suggested to let the `GClosure` to be a closure taking no arguments. I think this is the easiest way for now. We'll need a few code examples using this type to see if there are some corner cases which might make the binding more difficult than expected.

**Comment by antoyo** [comment]
As far as I understand, you send a `GCallback` or `GClosure` as a parameter to a function so that it can get called later.
However, the number and type of parameters is arbitrary, so I'm not sure we can do something safe and convenient for that.
One idea that I have is to only accept `Closure` with one parameter of type `Vec<Value>` and returning one `Value`. I think that will be safe this way.

**Comment by sdroege** [comment]
GClosure bindings are there now, only have to be used for signal connectors now. Which is handled by https://github.com/gtk-rs/gir/issues/474

**Comment by sdroege** [comment]
Can this be closed?
