### ISSUE TITLE
Process windows specific functions, ending with _utf8

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#375]
Some functions like `g_getenv` on Windows reexported as `g_getenv_utf8`.
We need generate right functions for windows in both sys and normal mode

```
g_filename_to_utf8_utf8
g_filename_from_utf8_utf8
g_filename_from_uri_utf8
g_filename_to_uri_utf8
g_dir_open_utf8
g_dir_read_name_utf8
g_getenv_utf8
g_setenv_utf8
g_unsetenv_utf8
g_file_test_utf8
g_file_get_contents_utf8
g_mkstemp_utf8
g_file_open_tmp_utf8
g_get_current_dir_utf8
g_io_channel_new_file_utf8
g_spawn_async_utf8
g_spawn_async_with_pipes_utf8
g_spawn_sync_utf8
g_spawn_command_line_sync_utf8
g_spawn_command_line_async_utf8
g_get_user_name_utf8
g_get_real_name_utf8
g_get_home_dir_utf8
g_get_tmp_dir_utf8
g_find_program_in_path_utf8
//Not in unix gir
g_win32_get_package_installation_directory_utf8
g_win32_get_package_installation_subdirectory_utf8

GModule:
g_module_open_utf8
g_module_name_utf8

GdkPixbuf"
gdk_pixbuf_animation_new_from_file_utf8
gdk_pixbuf_new_from_file_utf8
gdk_pixbuf_new_from_file_at_size_utf8
gdk_pixbuf_new_from_file_at_scale_utf8
gdk_pixbuf_save_utf8 (not in .c but in header)
gdk_pixbuf_savev_utf8
```

PS.
While it currently removed from headers in https://github.com/GNOME/glib/commit/b67d071321264cc4a7bb9df47a4381918232279a it still present in libs for compatibility (https://github.com/GNOME/glib/blob/master/glib/genviron.c#L636-L666). Also see https://github.com/gtk-rs/glib/pull/169#issuecomment-302944244

PPS. Functions is found in glib by this prefix
```
#ifdef G_OS_WIN32

/* Binary compatibility versions. Not for newly compiled code. */
```

PPPS. Long ago in https://github.com/gtk-rs/gir/issues/29#issuecomment-130653059 proposed adding `windows_utf8_shims` array for that, but now IMHO function option like `is_windows_utf8` is better

**Comment by EPashkin** [comment]
Gdk_pixbuf IMHO have good example for normal code https://github.com/gtk-rs/gdk-pixbuf/blob/master/src/pixbuf.rs#L53-L68

**Comment by EPashkin** [comment]
it also has hard coded names in sys generation https://github.com/gtk-rs/gir/blob/master/src/codegen/sys/functions.rs#L108-L121.

**Comment by EPashkin** [comment]
@GuillaumeGomez @sdroege
In sys maybe we need just add new `_utf8` function for windows without adding `cfg(not(windows))` for current?

**Comment by GuillaumeGomez** [comment]
It'd be way simpler/better!

**Comment by EPashkin** [comment]
Done.

**Comment by sdroege** [comment]
How would you add them if they don't appear in the GIR?

**Comment by EPashkin** [comment]
Sorry, don't understand, what you mean.

**Comment by sdroege** [comment]
You want to add them all to the code generator, a hardcoded list of functions? Would you accept patches for every single library to add their own functions there? :)

I don't think adding them to the code generator is a good idea for anything outside GLib/GObject itself, otherwise you'll have to add functions for arbitrary other libraries in the end.

**Comment by EPashkin** [comment]
I added config options to Gir, look linked PR.

**Comment by sdroege** [comment]
Ah, I missed that there was a pull request. That sounds indeed like a good idea 👍

**Comment by EPashkin** [comment]
There was 2 PRs, second is partial regen of sys crate to show what will be changed.

**Comment by EPashkin** [comment]
IMHO adding support for this function in Gir's normal mode unneeded (unlike in sys mode, we can always add it manually).
So I close this PR.
