### ISSUE TITLE
Add support for non-pointer arrays/containers

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#388]
Related to https://github.com/gtk-rs/gir/issues/376

Currently only pointer types are supported, i.e. FromGlibPtrContainer. All kinds of integer types would be useful too, including bytes for byte arrays.

**Comment by sdroege** [comment]
I would suggest making a `FromGlibContainer` that has the `from_*_num()` functions, and a `FromGlibPtrContainer` that inherits from that and only has the non-`_num()` functions.

Once that is done, support for that can be added to gir.

The former would then be implemented for `*const T` and `*mut T` for `Vec<T>` where `T` is some suitable type. Now what is a suitable type? `T: Copy` unfortunately not because pointers also seem to be `Copy`. I could add manual implementations (via macro) for u/i 8/16/32/64, GType, and others though.

Any suggestions?

**Comment by sdroege** [comment]
Similarly we need some trait impl for the other way around.

**Comment by EPashkin** [comment]
IMHO better don't mix FromGlibContainer and FromGlibPtrContainer as it have different trait constraints

**Comment by sdroege** [comment]
You mean I should just add a new FromGlibContainer (with the non-`_num()` functions only) and keep FromGlibPtrContainer as is?

What would you suggest for the other way around, ToGlib*?

**Comment by EPashkin** [comment]
Checked `FromGlibPtrContainer` definition. Your idea seems doable, at minimum for concrete types like Vec<u8>

**Comment by sdroege** [comment]
It will only work for `*const T` and `*const glib_ffi::GArray` to `Vec<T>, and the other way around (plus `&[T]` for that direction). Unfortunately this all involves copying for now with how the traits are defined (see https://github.com/gtk-rs/glib/issues/174), but better than not working at all.

**Comment by sdroege** [comment]
For the other way around, ToGlibPtr / ToGlibPtrMut seems to be sufficient. Just needs to be implemented for [T] / Vec<T> where T: Copy and T: ToGlib. Which should cover all basic fundamental types and enums/flags at least.

Generally the main question now is how to implement all this generically in a coherent way, because the trait impl selection detects overlapping impls in these cases. At least for the From* traits. I'll try to figure something useful out.

**Comment by EPashkin** [comment]
Overlapping impls is big problem in glib. I failed even adding GValue conversion for boxed types :(

**Comment by sdroege** [comment]
Maybe the traits should be independent then. FromGlibContainer and FromGlibPtrContainer. And instead of just ToGlibPtr/ToGlibPtrMut (I think the Mut one is also only a workaround for overlapping impls?) there could be new ToGlibContainer/ToGlibPtrContainer

**Comment by sdroege** [comment]
I would suggest that maybe all the traits in glib/src/translate.rs should be implemented for explicit types instead of doing it via trait bounds. This could be done via the type definition macros and for enums/flags with the code generator. This way we should prevent all these overlapping instances cases because there simply won't be any `impl<T> ... for T` (or similar) left. All the overlapping instances seem to come from generic trait impls, and those could be done un-generically.

**Comment by EPashkin** [comment]
Maybe it good idea, but not sure that it worked with current `IsA`.

**Comment by sdroege** [comment]
Why do you think it causes problems with IsA?

**Comment by EPashkin** [comment]
Thought, that mostly widgets define traits on `IsA`, and use `XXXGlibPtrXX` functions that generalized over it.
Was wrong, `XXGlibPtrXX` and others implemented for concrete class,
Anyway ungeneralizing is worth to try.

**Comment by sdroege** [comment]
Looking into that after the send/sync trait corrections then.

**Comment by sdroege** [comment]
Ok, now all basics are there and only support in GIR is missing. I'm only going to implement that for basic types for now (i8/16/32/64, u8/16/32/64 and f32/64), which should cover most useful cases for now. Enums/flags could relatively easily be added if needed.
