### ISSUE TITLE
Add keywords to the repository

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#396]
Currently searching the internet for GObject, GObject-Introspection, etc. and Rust does not find this one here but the old abandoned grust.

**Comment by sdroege** [comment]
Also a description of the repository would probably help :)

**Comment by Luke-Nukem** [comment]
Adding `topics` to the header under "description" would help a lot also.

**Comment by ford-prefect** [comment]
I also do think it might make sense to ask @mzabaluev to point to this from the `grust` repos

**Comment by EPashkin** [comment]
You all right.
I primary though about published crates, that have keywords https://github.com/gtk-rs/gtk/blob/master/Cargo.toml#L14, maybe missed some.
This crate not published and currently no plan of doing it.

What do you suggest?

**Comment by sdroege** [comment]
GTK, GObject, GLib, GNOME, GObject-Introspection, Rust, bindings, bindings generator

**Comment by Luke-Nukem** [comment]
and "rust bindgen", "bindgen"

**Comment by EPashkin** [comment]
And description be something like
"Tool to generate rust bindings and user API for glib-based libraries"?

@GuillaumeGomez, can you apply these?

**Comment by GuillaumeGomez** [comment]
Sure.

**Comment by GuillaumeGomez** [comment]
So I added the description for the gir repository; however you want me to add which keywords to which `Cargo.toml` exactly?

**Comment by EPashkin** [comment]
Not keywords, topics. IMHO all suggested is good, not sure that it not too many.

**Comment by EPashkin** [comment]
Maybe without `bindings generator` as it contains spaces.

**Comment by GuillaumeGomez** [comment]
Done as well.

**Comment by EPashkin** [comment]
Thanks

**Comment by sdroege** [comment]
👍
