### ISSUE TITLE
"Simple" sys types should implement copy/clone

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#399]
A few types are only composed of simple types (integers and so on...). They could be bound as is and implement the copy/clone traits automatically.

In this case, I'm thinking about [Pango.LogAttr](https://developer.gnome.org/pango/stable/pango-Text-Processing.html#PangoLogAttr) mainly.

**Comment by EPashkin** [comment]
Yes, seems we need split `RecordType::Direct` to 2 cases: simple types without pointers (Direct) and others (Unknown or Default).
Then we can safe implement Copy\Clone for these records in syses.

Problem with `PangoLogAttr` that is bit struct and need lot more changes in gir.

**Comment by GuillaumeGomez** [comment]
Unfortunately yes... :-/

**Comment by tmiasko** [comment]
Derivation of copy and clone traits is already implemented, and for bitfields we have another issue #465.
