### ISSUE TITLE
Required cfg(feature) missing

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#403]
In gio:

https://github.com/gtk-rs/gio/blob/master/src/auto/enums.rs#L57-L66

https://github.com/gtk-rs/gio/blob/master/src/auto/notification.rs#L6
https://github.com/gtk-rs/gio/blob/master/src/auto/notification.rs#L55

The feature should be everywhere this enum is used.

**Comment by EPashkin** [comment]
It just missed version on functions.
Theoretically we can callculate it from all function parameters.
But currently we just set version for function.

**Comment by GuillaumeGomez** [comment]
No, on the import as well.

**Comment by EPashkin** [comment]
Import depends only on function that it used

**Comment by EPashkin** [comment]
Problem with this type of errors, that instead fixing it on Gir better report it upstream, but it too bothersome.
And this error is small subset of other errors: missing consts etc.

**Comment by GuillaumeGomez** [comment]
No, I mean that the function should be under the feature corresponding to the type with the highest feature. Like this, we could avoid this error easily in case no version is specified.

**Comment by EPashkin** [comment]
I understand that, IMHO it just need extra pass on all parameters and I prefer do it with showing warnings about missing or too low version.
But currently I don't want do this due low frequency for this error type 😉

**Comment by GuillaumeGomez** [comment]
No problem, I'll. ;)

**Comment by GuillaumeGomez** [comment]
Fixed it has been.
