### ISSUE TITLE
Add manual part for generated sys crates

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#417]
Currently crate generated in sys mode contains only these files
```
.
├── Cargo.toml
├── build.rs
└── src
    └── lib.rs
```
`Cargo.toml` updated and can contains manual lines, but both `*.rs` is completely overridden on regeneration, so there no way add some manual code.
We don't need this for gtk-rs crates but maybe needed for others.
I propose always add `src/manual.rs` if it don't exists and include + reexport it in `lib.rs`.

**Comment by sdroege** [comment]
That seems useful, and I would already have some use for it if it existed. Should maybe come together with a way for disabling autogeneration of a function (not needed for my case though).

**Comment by EPashkin** [comment]
Ignoring function already done via "ignore=true"

**Comment by sdroege** [comment]
Ah, I didn't realize that this also works for -sys

**Comment by EPashkin** [comment]
Was reissued as #512 and fixed in #514
