### ISSUE TITLE
Should probably ignore items with introspectable="0" in the .gir

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#431]
These are the items that are marked as `(skip)` in the in-code annotations, meant to be not used by bindings. Those should probably be omitted from the non-sys bindings.

The annotation can be on objects and functions at least.

**Comment by EPashkin** [comment]
IMHO some usable also has this flag

**Comment by sdroege** [comment]
Which for example? That would be a bug in the .gir file then

**Comment by sdroege** [comment]
Let's close this, there are too many things marked as not introspectable that we can handle just fine.
