### ISSUE TITLE
Properties with getter/setter functions are not ignored if name mangling is needed

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#438]
See summary.

**Comment by EPashkin** [comment]
Can you give example?

**Comment by sdroege** [comment]
Hrm no, different problem actually. I run into this case
```rust
if has && (env.is_totally_deprecated(version) || version <= prop_version)
```

version is `Some((1,4,0))`, prop_version is `None`. Which is a missing version marker for the property, it should also be the same.


I guess not a bug here then and I should manually hide those properties?

**Comment by EPashkin** [comment]
I usually add a version for the property instead ignoring, so it ignored by this line.
