### ISSUE TITLE
Traits url are badly generated

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#463]
For example, [`ApplicationExt`](http://gtk-rs.org/docs/gtk/trait.GtkApplicationExt.html) on [`Application`](http://gtk-rs.org/docs/gtk/struct.Application.html) doesn't send to the correct page.

**Comment by EPashkin** [comment]
Strange, it have prefix `Gtk` in doc

**Comment by GuillaumeGomez** [comment]
Right?

**Comment by EPashkin** [comment]
I meant http://gtk-rs.org/docs/gtk/trait.GtkApplicationExt.html

**Comment by GuillaumeGomez** [comment]
Yes yes, that's also what I've put in the link I wrote.

**Comment by GuillaumeGomez** [comment]
It seems like it's working as expected now.
