### ISSUE TITLE
Some traits are showed twice on the "implements" part

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#464]
Example on the [`Application`](http://gtk-rs.org/docs/gtk/struct.Application.html) page.

**Comment by EPashkin** [comment]
This fixed by renaming traits, Ex. gtk's `ApplicationExt` trait to `GtkApplicationExt`.

**Comment by bilelmoussaoui** [comment]
@GuillaumeGomez this can be closed btw

**Comment by GuillaumeGomez** [comment]
Ok!
