### ISSUE TITLE
Update to bitflags 1.0

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#468]
This has some API changes, most importantly all the flags are now under the namespace of the type. That is, we will have `gst::BufferFlags::LIVE` instead of `gst::BUFFER_FLAG_LIVE`. A very nice change IMHO!

This should block the next gtk-rs release round.

@GuillaumeGomez @EPashkin

**Comment by GuillaumeGomez** [comment]
Sounds nice. And I propose that once this change and the `gio::run` update (to be done) are merged, we make a new release.

**Comment by sdroege** [comment]
I'd like to solve https://github.com/gtk-rs/gir/issues/446 https://github.com/gtk-rs/gir/issues/443 https://github.com/gtk-rs/glib/issues/228 https://github.com/gtk-rs/glib/issues/223 for this release. What timeline did you have in mind approximately?

**Comment by GuillaumeGomez** [comment]
Before mid-october if possible. However I just had a small release in mind, it seems to get bigger so I prefer to delay if needed.

**Comment by sdroege** [comment]
I should be able to do all that before mid-October, we'll see. Each of them is rather small, especially if someone wants to help.

I wouldn't get the class struct stuff of Federico in yet but keep that for the next release, to give it some more time to mature.


Do we have a tracker ticket somewhere for the things that should be solved before the next release?

**Comment by GuillaumeGomez** [comment]
Nothing like that. We generally have a set of features we'd like to have in the next release, but besides it, nothing. No need to put pressure on yourself or whatever, if the release happens in november or later, then so be it! :)

**Comment by EPashkin** [comment]
👍 for update bitflags too, while not sure that it will be good with current enums.
Also possible addition to this release is https://github.com/gtk-rs/gir/pull/459 and https://github.com/gtk-rs/glib/issues/233 (I prefer merge last as is to lock macro syntax)

**Comment by sdroege** [comment]
> 👍 for update bitflags too, while not sure that it will be good with current enums.

What do you mean?

**Comment by EPashkin** [comment]
I was mistaken `c:identifier` with `name` and thought that no way to extract short name. Ex. `LOGOUT` from `GTK_APPLICATION_INHIBIT_LOGOUT`

**Comment by sdroege** [comment]
Working on this now btw
