### ISSUE TITLE
Add support for manually implementing "alias" types

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#476]
I have an "alias" type in GStreamer (`type ClockTime = u64`) and would like to implement it manually as a newtype `struct ClockTime(Option<u64)` (`u64::MAX` has a special meaning).

For that it needs to be possible to override the conversion, i.e. GIR needs to generate code that calls `from_glib` and `to_glib` instead of taking the value as-is. I would add a configuration option for that.

**Comment by EPashkin** [comment]
IMHO this options need be almost same or convertible to `ConversionType`

**Comment by sdroege** [comment]
Yeah, that was the idea :)
