### ISSUE TITLE
Represent enums as constants instead of enums

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#480]
From the bindgen 0.31.0 release notes

> C/C++ enums are now translated into constants by default, rather than Rust enums. The old behavior was a big footgun because rustc assumes that the only values of an enum are its variants, whereas a lot of C/C++ code uses random values as enums. Put these two things and it leads to undefined behavior. Translating C/C++ enums into Rust enums is still available with the --rustified-enum <regex> CLI flag and bindgen::Builder::rustified_enum("<regex>") builder method. https://github.com/rust-lang-nursery/rust-bindgen/issues/758

**Comment by EPashkin** [comment]
@sdroege  You don't understand, how it solves problem with function accepts enum values? Now it accept any int?

**Comment by sdroege** [comment]
Basically what has to be done to make this safe is that the sys bindings use integers and constants. And the non-sys bindings use enums with the `Unknown` variant we have already, and convert from/to integers with the conversion traits.

The important part is that we should never have an out of range value anywhere, currently we can at the sys layer.

We should try to fix that before the next release. We already have the constants in the sys bindings, just the enums would go away.

**Comment by EPashkin** [comment]
If it only for sys, then IMHO this good, while slightly loss in declarability it removes UB

**Comment by sdroege** [comment]
OK, I'll prepare a PR :)

**Comment by EPashkin** [comment]
As pangocairo don't contains enums, seems gtk last PR.
