### ISSUE TITLE
dox feature and duplicated functions

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#484]
When generating dox conditional feature, if a method/function/type is present multiple times with different representation following the version, it'll fail when trying to generate the doc because it'll be defined multiple time.

Only the latest version should therefore have the dox feature.

**Comment by EPashkin** [comment]
@GuillaumeGomez can you give example?
I remember only one such function `Application::new`, but it manual and don't have `dox`

**Comment by GuillaumeGomez** [comment]
In `sourceview`. Try to build it with `cargo doc --features dox` and you'll see. :)

**Comment by GuillaumeGomez** [comment]
Actually, I completely failed to judge correctly what the failure was:

```
error[E0428]: the name `NONE` is defined multiple times
   --> src/auto/flags.rs:11:1
    |
11  | / bitflags! {
12  | |     pub struct CompletionActivation: u32 {
13  | |         const NONE = 0;
14  | |         const INTERACTIVE = 1;
15  | |         const USER_REQUESTED = 2;
16  | |     }
17  | | }
    | |_^ `NONE` redefined here
...
218 | / bitflags! {
219 | |     pub struct SortFlags: u32 {
220 | |         const NONE = 0;
221 | |         const CASE_SENSITIVE = 1;
...   |
224 | |     }
225 | | }
    | |_- previous definition of the value `NONE` here
    |
    = note: `NONE` must be defined only once in the value namespace of this module
    = note: this error originates in a macro outside of the current crate
```

It's not because of the `dox` features but because of name conflicts when the version feature >= 3.14. Any idea on how it could be fixed @EPashkin? (maybe adding the type name before?)

**Comment by EPashkin** [comment]
IMHO we can add `new_name` for enum. I try add it.

**Comment by EPashkin** [comment]
Strange that it give error in `enums.rs` not in sys's 'lib.rs`

**Comment by GuillaumeGomez** [comment]
Yep...

**Comment by EPashkin** [comment]
Actually non sys just have old bitflags :wink:

**Comment by GuillaumeGomez** [comment]
Oh so easy fix. Such a relief... Wanna fix it or should I?

**Comment by EPashkin** [comment]
Better you

**Comment by GuillaumeGomez** [comment]
Ok!

**Comment by GuillaumeGomez** [comment]
https://github.com/gtk-rs/sourceview/pull/21 fixed this. Thanks for help @EPashkin!
