### ISSUE TITLE
#[derive(Debug)] for all types in -sys crates

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#486]
This would also allow to derive debug of types containing them, and generally does not hurt.

@EPashkin @GuillaumeGomez What do you think?

**Comment by GuillaumeGomez** [comment]
I strongly approve. That's something I've been thinking about a long time ago.

**Comment by sdroege** [comment]
Great, I'll add that to gir then later. Not having that is causing some annoyances here right now :)

**Comment by EPashkin** [comment]
We already agreed to deriving debug ;) but not remember where.

**Comment by sdroege** [comment]
Problem with that will be unions once we merge the PR. I doubt Debug can be derived for structs with unions :)
