### ISSUE TITLE
Generated doc for Gtk.Application "Implements" section link to wrong Ext trait

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#500]
so result http://gtk-rs.org/docs/gtk/struct.Application.html links to ApplicationExt instead GtkApplicationExt,
and repeated it 2 times.

**Comment by EPashkin** [comment]
http://gtk-rs.org/docs/gtk/struct.Window.html also shows old trait.

@GuillaumeGomez I try to fix it tomorrow

**Comment by GuillaumeGomez** [comment]
Thanks! :)

**Comment by EPashkin** [comment]
Both test cases is fine, so I close this
