### ISSUE TITLE
GIO-style async functions should take FnOnce closures

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#508]
They're called at most once. Unfortunately FnOnce can't be boxed right now in stable Rust, we have to wait until that is stabilized.

In addition, the closures can also get the Sync requirement dropped for the very same reason.

**Comment by sdroege** [comment]
CC @antoyo

**Comment by antoyo** [comment]
Is there something we can do now and should we wait?

**Comment by sdroege** [comment]
We can remove the Sync requirement now already, and could in theory make them all FnMut at least

**Comment by sdroege** [comment]
Also I just noticed that we're leaking all closures currently. I'll paste a link to a commit that does it correctly in a few minutes.

**Comment by sdroege** [comment]
Here https://github.com/sdroege/gio-rs/commit/10dd01f30809cc72f768dc70bb3c8bed9b4e3f88

**Comment by sdroege** [comment]
Sorry for not noticing that before!

**Comment by sdroege** [comment]
Also they could be FnOnce now already if we use the concrete types for the Boxes instead of trait objects. This requires that the trampolines get a generic parameter, but otherwise would improve usability a lot.

**Comment by antoyo** [comment]
I agree.
I'll work on this in 1 or 2 week.

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gir/pull/509
