### ISSUE TITLE
Don't generate connect_xxx_notify for Read or ConstructOnly properties

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#510]
Example: `gio::IOStream`, `gio::FilterInputStream::base-stream`, `gio::FilterOutputStream::base-stream`

**Comment by sdroege** [comment]
There are cases where read-only properties are changing from inside the object, and you want to be notified of those changes from the outside. If that also exists for construct-only properties, I don't know.

**Comment by EPashkin** [comment]
Bad, then this need be done manually.
There way to check is readonly property can be changed from inside the object?

**Comment by sdroege** [comment]
Only by checking its code (or the documentation) :)

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege 
I tried to add warning in https://github.com/gtk-rs/gir/compare/master...EPashkin:partial_properties_warn_construct_only?expand=1, checked some in gtk, seems usable `notify` is rare case (still don't found any).
Sometimes (Gtk.MessageDialog.buttons) notify [fired](https://github.com/GNOME/gtk/blob/master/gtk/gtkmessagedialog.c#L843), but property not readable,
so I don't see any reason to fire as `gtk_message_dialog_add_buttons` is private, so will be fired only once before object returned to user.

Maybe we better just don't generate notify by default without warning,
but allow generation if needed.

**Comment by sdroege** [comment]
What do you mean with "usable notify" being rare? It's a bug if they the property can change but notify is not triggering.

Do you mean not generating notify by default only for construct-only/read-only properties, or in general?

**Comment by EPashkin** [comment]
Yes, I propose don't generate connect_xxx_notify for ConstructOnly properties by default.

**Comment by sdroege** [comment]
That seems fine to me

**Comment by EPashkin** [comment]
All PR in gtk-rs done and linked to this issue
