### ISSUE TITLE
Allow use custom modules in sys mode

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#512]
Currently `sys` module contains only `lib.rs` that always recreated.
This will broke gtk-sys after rebuild as it need manual module `xlib` added in https://github.com/gtk-rs/sys/pull/76.

cc @GuillaumeGomez, @sdroege

**Comment by EPashkin** [comment]
I see at minimum 2 way to fix this:
1. Add array parameter to `Gir.toml` with list of modules,
2. When generating `lib.rs` check folder and add `pub use ` for all found *.rs files.

**Comment by GuillaumeGomez** [comment]
I prefer the most automated way if possible but otherwise, I don't really have an opinion in here...

**Comment by EPashkin** [comment]
Ok, I do 2,
we can add 1 to it, if needed
