### ISSUE TITLE
Add support for async functions that have a non-trivial return type of the finish() function

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#535]
Lots of GIO functions actually return the result instead of having it as an out parameter. Fixing this would remove the need of lots of manual implementations.

**Comment by sdroege** [comment]
@antoyo Do you remember why you didn't implement this?

**Comment by antoyo** [comment]
I thought it would make more sense to return tuples with the out parameters than using out parameters in Rust.

**Comment by sdroege** [comment]
That's not the point. Currently async functions ignore the return value of the finish() function, requiring a lot of custom code like https://github.com/gtk-rs/gio/pull/78/files#diff-89402946f108bf676d0bda0a8dbf07b0R36

**Comment by antoyo** [comment]
Oh, I think I didn't have the time to add this (not sure I remember why :) ).

**Comment by sdroege** [comment]
Ok, I guess for someone to try again then :) I was wondering if there were maybe any problems with that

**Comment by antoyo** [comment]
Do you need help to work on this?

**Comment by sdroege** [comment]
I have it on my todo list, but quite busy with other things currently. Will take a while, so if you can spend some time on that it would be great :)
