### ISSUE TITLE
Extend not_bound report to include methods / signals / etc..

### ISSUE THREAD

**Issue by MathieuDuponchelle** [gtk-rs/gir#543]
It would be quite helpful to get information on bindings coverage, both for the generated types and overall.

**Comment by EPashkin** [comment]
We have `not_bound` mode to show not generated types, IMHO this is enough

**Comment by MathieuDuponchelle** [comment]
Ah, didn't know about not_bound, ideally it could be extended to list unbound methods / signals / etc.. :)

**Comment by EPashkin** [comment]
It will be too long and partially wrong list, as gir know nothing about functions that generated manually

**Comment by GuillaumeGomez** [comment]
There is not much point into generating it for methods and signals since they're generated as commented. You just need to grep on the source files to see what remains. We don't do it for "general functions" though. I'll add and then close this issue.

**Comment by GuillaumeGomez** [comment]
We already report general functions, therefore I close this issue.
