### ISSUE TITLE
Don't print the hashes of the submodules at the top of the generated files

### ISSUE THREAD

**Issue by MathieuDuponchelle** [gtk-rs/gir#556]
This is a minor annoyance, but it does make version control a bit annoying.

The use-case that needs to be preserved is, as @EPashkin [mentioned](https://github.com/gtk-rs/gio/pull/87#issuecomment-368108422), making sure when reviewing a PR that all the auto files have been regenerated  appropriately.

I think a solution to this would be:

* PR is proposed against eg gio
* Travis builds gir at the version of the gir submodule
* Travis generates the automatic files against the gir-files at the version of the gir-files submodules
* It then simply errors out if there are differences between the files it has generated and the automatic files as proposed in the PR

Thoughts?

**Comment by EPashkin** [comment]
IMHO good idea. We already do it for docs
Only cons is CI build time increase.

**Comment by EPashkin** [comment]
We can minimize CI build time by make check only for one case (first for example).

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege What do you think?

**Comment by GuillaumeGomez** [comment]
To sum up my answer when we talked about it on IRC: "as long as it's easy to see which version is currently used and if it doesn't increase support for us, I'm fine with it".

**Comment by EPashkin** [comment]
gio crate will be a test subject

**Comment by GuillaumeGomez** [comment]
I approve the "on test" period. :)

**Comment by MathieuDuponchelle** [comment]
@EPashkin , why did you opt against the CI solution ooc?

**Comment by EPashkin** [comment]
@MathieuDuponchelle Sorry, I don't understand your question.
CI checks difference on nightly/3.4 build: https://github.com/gtk-rs/gio/blob/master/.travis.yml#L15-L17
https://travis-ci.org/gtk-rs/gio/jobs/348980233#L608-L736

**Comment by MathieuDuponchelle** [comment]
@EPashkin ah, didn't know you had implemented that! Then I'm not sure what you need the `versions.txt` file for :)

**Comment by GuillaumeGomez** [comment]
To be able to track `gir*` version.

**Comment by MathieuDuponchelle** [comment]
But we've already got this information with the git submodules don't we? I might be missing something here :)

**Comment by GuillaumeGomez** [comment]
It's easier to track. And submodules are completely optionals.

**Comment by MathieuDuponchelle** [comment]
OK :)

**Comment by GuillaumeGomez** [comment]
Can be closed now (since a while actually...).
