### ISSUE TITLE
Name of currently generated sys crate.

### ISSUE THREAD

**Issue by tmiasko** [gtk-rs/gir#567]
When generating integration tests for sys crate I need to generate `extern crate ...` declaration to actually use it. Is there an existing mechanism that can handle situation when crate is renamed? For external dependencies there is `[external_libraries]`, but what about crate currently being generated?

**Comment by sdroege** [comment]
I would also like to have that for gstreamer-sys

**Comment by EPashkin** [comment]
IMHO currently generated crate can be get from path, or better by reading `Cargo.toml`

**Comment by EPashkin** [comment]
In sys mode we always read it so we can just return crate name from [generate](https://github.com/gtk-rs/gir/blob/master/src/codegen/sys/cargo_toml.rs#L12)

**Comment by tmiasko** [comment]
Reading from Cargo.toml should work: try lib.name first, then package.name. In
case Cargo.toml does not exists yet, use config.libary_name. I would store
it somewhere it config, and use from there. OK?

**Comment by EPashkin** [comment]
You meant other scenario that test for sys generation?
For test you can just pass it to next function.

**Comment by tmiasko** [comment]
Yes, that would work for tests, though I would rather make it available in general. I wonder, what do you need it for @sdroege?

**Comment by sdroege** [comment]
@tmiasko The .gir files/namespace/etc for gstreamer-sys are `GstXXX`, but the crates are called `gstreamer-XXX-sys` (instead of `gst-XXX-sys`).

**Comment by EPashkin** [comment]
@sdroege You only worry about new ABI tests or need actual crate for something other?

**Comment by sdroege** [comment]
Yes only that

**Comment by tmiasko** [comment]
In that case #569 should be enough.
