### ISSUE TITLE
Generating constants for bitfields works only with types from the same crate.

### ISSUE THREAD

**Issue by tmiasko** [gtk-rs/gir#575]
The bits field in structure generated by bitflags! macro is not public, and thus when generating a constant using a type from other sys crate, the code will fail to compile. For example, when generating code for libdazzle one currently gets following error at build time:

```
error[E0451]: field `bits` of struct `glib::GLogLevelFlags` is private
  --> src/lib.rs:78:78
   |
78 | pub const DZL_LOG_LEVEL_TRACE: glib::GLogLevelFlags = glib::GLogLevelFlags { bits: 1 };
   |                                                                              ^^^^^^^ field `bits` is private
```

I don't really care about DZL_LOG_LEVEL_TRACE in particular, but it would be nice to handle this in general, if possible.

cc: @alatiera

**Comment by EPashkin** [comment]
Usually you can rexport sys's DZL_LOG_LEVEL_TRACE, it must be public

**Comment by EPashkin** [comment]
Oh, gir really generate `{ bits: }` on some cases, but not one of these in gtk-rs.
cc @sdroege

**Comment by EPashkin** [comment]
Hm, Seems I still don't understand problem:
`{ bits: 1 }` generated only in sys crate,
how you get it generated in normal crate (I think it normal as it use `glib::`)?,
also in normal mode IMHO we currently generate only string constants.

**Comment by tmiasko** [comment]
It is a sys crate for libdazzle, `extern crate glib_sys as glib;` :-).

The bitflags crate don't support public bits field unfortunately.

**Comment by EPashkin** [comment]
Why you don't use `glib::GLogLevelFlags::FLAG_RECURSION`  or `G_LOG_FLAG_RECURSION` ?

**Comment by EPashkin** [comment]
I still can't find repo, so I don't understand why this const attempts to use `bits` as base const don't use it.

**Comment by sdroege** [comment]
This is in a -sys crate, and the problem here is that dazzle has a bitflags constant that is of a type from another crate (glib-sys). I'm not sure how to generate a correct constant for that until we have stable const_fn, or we don't generate an actual constant but something in lazy_static.

**Comment by EPashkin** [comment]
From Dazzle-1.0.gir
```xml
    <constant name="LOG_LEVEL_TRACE"
              value="1"
              c:type="DZL_LOG_LEVEL_TRACE"
              introspectable="0">
      <type name="GLib.LogLevelFlags" c:type="GLogLevelFlags"/>
    </constant>
```
Seems this only one constant form other crate.
So I see solutions:
make this const manual,
fix gir to generate with `from_bits_truncate` or `from_bits` instead current code (IMHO don't need separate current or external crate)

**Comment by EPashkin** [comment]
As @sdroege last solution currently unawailable :sob:

**Comment by tmiasko** [comment]
Now that I think about it, my impression is that using bitflags for this is
might be a wrong choice. First, types generated by bitflags! macro are intended
to only represent values that can be combinations or declared flags, which is
obviously not the case for C. Second, it may change the ABI by wrapping the
value in struct. In fact it *does* change the ABI, for example on 32-bit Linux
systems.

**Comment by EPashkin** [comment]
@tmiasko 
As I know wrapping #[repr(C)] type in single field struct don't change it size\alignment.
Only problem it if we use wrong base type.
Can you explain why you think that ABI changed?

**Comment by tmiasko** [comment]
In System V i386 calling convention, the integer will be returned in %eax, but
structure will be returned through space reserved by the caller.

**Comment by EPashkin** [comment]
Thanks for explanation.

**Comment by EPashkin** [comment]
On Win64 rustc always use %eax in all 3 calls, struct's functions only has extra stack allocation :
```rust
fn call1() -> i32 {
    4
}

#[derive(Debug)]
struct S1 {
    f: i32,
}

fn call2() -> S1 {
    S1 { f: 5 }
}

#[repr(C)]
#[derive(Debug)]
struct S2 {
    f: i32,
}

fn call3() -> S2 {
    S2 { f: 6 }
}

fn main() {
    let a = call1();
    let b = call2();
    let c = call3();
}
```

```asm
	.def	 _ZN3lib5call117h40770e0705094003E;
	.scl	3;
	.type	32;
	.endef
	.p2align	4, 0x90
_ZN3lib5call117h40770e0705094003E:
	movl	$4, %eax
	retq

	.def	 _ZN3lib5call217h5a962ac1e4848dd9E;
	.scl	3;
	.type	32;
	.endef
	.p2align	4, 0x90
_ZN3lib5call217h5a962ac1e4848dd9E:
.seh_proc _ZN3lib5call217h5a962ac1e4848dd9E
	pushq	%rax
	.seh_stackalloc 8
	.seh_endprologue
	movl	$5, 4(%rsp)
	movl	4(%rsp), %eax
	popq	%rcx
	retq
	.seh_handlerdata
	.text
	.seh_endproc

	.def	 _ZN3lib5call317h1b6201b0d5a5c98bE;
	.scl	3;
	.type	32;
	.endef
	.p2align	4, 0x90
_ZN3lib5call317h1b6201b0d5a5c98bE:
.seh_proc _ZN3lib5call317h1b6201b0d5a5c98bE
	pushq	%rax
	.seh_stackalloc 8
	.seh_endprologue
	movl	$6, (%rsp)
	movl	(%rsp), %eax
	popq	%rcx
	retq
	.seh_handlerdata
	.text
	.seh_endproc

	.def	 _ZN3lib4main17hd5ade585b8b31345E;
	.scl	3;
	.type	32;
	.endef
	.p2align	4, 0x90
_ZN3lib4main17hd5ade585b8b31345E:
.seh_proc _ZN3lib4main17hd5ade585b8b31345E
	subq	$56, %rsp
	.seh_stackalloc 56
	.seh_endprologue
	callq	_ZN3lib5call117h40770e0705094003E
	movl	%eax, 44(%rsp)
	callq	_ZN3lib5call217h5a962ac1e4848dd9E
	movl	%eax, 40(%rsp)
	callq	_ZN3lib5call317h1b6201b0d5a5c98bE
	movl	%eax, 52(%rsp)
	movl	52(%rsp), %eax
	movl	%eax, 48(%rsp)
	addq	$56, %rsp
	retq
	.seh_handlerdata
	.text
	.seh_endproc
```

**Comment by tmiasko** [comment]
I am not sure what Rust uses as default calling convention, so to ensure that C calling convention is used, a slightly modified example with target i686-unknown-linux-gnu:
```
$ cat a.rs
```
```rust
#[no_mangle]
pub extern "C" fn call1() -> i32 {
    4
}

pub struct S1 {
    pub f: i32,
}

#[no_mangle]
pub extern "C" fn call2() -> S1 {
    S1 { f: 5 }
}

#[repr(C)]
pub struct S2 {
    pub f: i32,
}

#[no_mangle]
pub extern "C" fn call3() -> S2 {
    S2 { f: 6 }
}
```
```
$ rustc --crate-type lib -O --target i686-unknown-linux-gnu --emit asm a.rs
$ cat a.s 
```
```asm
	.text
	.file	"a0-8787f43e282added376259c1adb08b80.rs"
	.section	.text.call1,"ax",@progbits
	.globl	call1
	.p2align	4, 0x90
	.type	call1,@function
call1:
	.cfi_startproc
	movl	$4, %eax
	retl
.Lfunc_end0:
	.size	call1, .Lfunc_end0-call1
	.cfi_endproc

	.section	.text.call2,"ax",@progbits
	.globl	call2
	.p2align	4, 0x90
	.type	call2,@function
call2:
	.cfi_startproc
	movl	$5, %eax
	retl
.Lfunc_end1:
	.size	call2, .Lfunc_end1-call2
	.cfi_endproc

	.section	.text.call3,"ax",@progbits
	.globl	call3
	.p2align	4, 0x90
	.type	call3,@function
call3:
	.cfi_startproc
	movl	4(%esp), %eax
	movl	$6, (%eax)
	retl	$4
.Lfunc_end2:
	.size	call3, .Lfunc_end2-call3
	.cfi_endproc


	.section	".note.GNU-stack","",@progbits
```

call1 and call2 use register directly, and call3 stores result in address provided on stack.

**Comment by EPashkin** [comment]
Yes, I tried extern "C" too with no_mangle, it produces same result as before for Win64.
Can you check this for 64 bit linux?

**Comment by sdroege** [comment]
Maybe let's just make bitfields integers in -sys, like enums. Plus constants.

And use the from/to bits conversions in the non-sys crate

**Comment by EPashkin** [comment]
We can implement `FromGlib`  for `type FlagType=c_int;` ? IMHO usually not.
Then we lost range check.

**Comment by tmiasko** [comment]
The 64-bit Linux is unaffected by ABI issue.

**Comment by sdroege** [comment]
> We can implement FromGlib for type FlagType=c_int; ? IMHO usually not.

That's how we do enums

**Comment by EPashkin** [comment]
Oh, forgot that we create enum/bitflags in normal crate too.
Then IMHO this doable.

**Comment by EPashkin** [comment]
Only possible problem with doc, it will not be grouped, but we don't generate doc for sys anyway.

**Comment by EPashkin** [comment]
@GuillaumeGomez All linked PR except gtk's ready for merge.
Sourceview even have CI passed.
I will update gtk after all merged to get good CI.

**Comment by GuillaumeGomez** [comment]
Ok, all merged except gtk. I let you do whatever you do on it. :p Ping me once done!

**Comment by tmiasko** [comment]
@EPashkin I just retested with libdazzle, it works fine. Thanks.

**Comment by EPashkin** [comment]
@tmiasko Can you link libdazzle here just in case

**Comment by EPashkin** [comment]
Now I understand why I can't find it on github 😉
