### ISSUE TITLE
Filename type in GObject Introspection vs Path and OsStr in Rust.

### ISSUE THREAD

**Issue by tmiasko** [gtk-rs/gir#592]
GLib now uses filename types not only for passing filenames, but also for
environment variables and process arguments:

> The filename type represents an utf-8 string on Windows and a zero terminated
> guint8 array on Unix. It should be used for filenames, environment variables
> and process arguments.

This doesn't match exactly types used in Rust which makes more nuanced
distinction and uses Path for filenames and OsStr for environment variables and
process arguments.

It would be nice to have possibility to select desired interpretation for
given parameter / return type.

**Comment by EPashkin** [comment]
Related to #264

**Comment by tmiasko** [comment]
I was of the impression that intention of the filename type now is to represent
what we call OsString in Rust. Some of those are also paths, but not all of
them, so I would consider this change to be correct but quite unsatisfactory
from Rust perspective which does make the disticion between the two.

Depending on your priorities the current outcome might be worse, or an
improvement, say in the case that you care about non-UTF-8 arguments (note that
there is 1-to-1 mapping between OsStrings and PathBufs in Rust).

**Comment by sdroege** [comment]
That seems to be the intention but it's a backwards incompatible change and breaks bindings as-such. GLib has to add a new type annotation for this or at least intentionally break API and document this properly.

**Comment by tmiasko** [comment]
Given that we agree about os string as optimal solution for those new cases,
are paths actually that different? They all have no-op from / into conversions
and AsRef implementations. Consider following example, you can replace paths
with os strings, and everything will continue to work. The most problematic
cases are arrays.

```rust
use std::ffi::*;
use std::path::*;

// With Path
fn arg<P: AsRef<Path>>(_: P) {}
fn ret() -> PathBuf { PathBuf::new() }

// With OsStr
// fn arg<P: AsRef<OsStr>>(_: P) {}
// fn ret() -> OsString { OsString::new() }

fn as_argument() {
        let string = String::new();
        let osstring = OsString::new();
        let str: &str = string.as_ref();
        let osstr: &OsStr = osstring.as_ref();

        arg(str);
        arg(osstr);
        arg(&string);
        arg(&osstring);
}

fn as_return_value() {
    let _: OsString = ret().into();
    let _: String = ret().to_string_lossy().into_owned();
}

fn main() {
    as_argument();
    as_return_value();
}
```

**Comment by sdroege** [comment]
They would work exactly like paths, yes. Just a different pair of types

**Comment by tmiasko** [comment]
IMHO the String is much worse than PathBuf, given that latter is able to
represent everything that OsString can, so trying to revert changes in GLib
is unnecessary (maybe I should have commented in bugzilla, not here).

**Comment by EPashkin** [comment]
Good thing that it don't affected sys mode.
On this week I will add fix for this through function parameter and return config `isOsString=true`.
it progress I plan to add fake type to `library::Fundamental`, so if glib-team decided add type we can just rename it to right name and remove config.

**Comment by sdroege** [comment]
IMHO we should just add a config for distinguishing between String, OsString and PathBuf. They all have a different meaning even if the last two can have the same representation.

String instead of PathBuf in the past was less bad IMHO as it would fail cleanly for invalid cases, and for working cases you at least have the correct semantics: it's a string, not a path :)

**Comment by EPashkin** [comment]
@sdroege You think that sometimes we need way change current String to PathBuf (ex for `utf8` type instead real `filename`)? I doubt that there cases for this.
About current case: change PathBuf to OsString, you prefer use String instead?

**Comment by sdroege** [comment]
No, current case should be OsString. But what I'm saying is that the previous situation with String was better than the current situation with PathBuf for those APIs :)

I'd prefer to have a configuration option to override the type in general. So that we can also change utf8 strings to filename or OsString if the annotation in GIR is wrong. Let's keep it generic.

**Comment by EPashkin** [comment]
Overriding for parameter/return type in general is part #264, but currently I don't ready to do it,
that why I plan only add config for single conversion (PathBuf -> OsString).

**Comment by sdroege** [comment]
I would've thought String<->PathBuf<->OsString to all basically require the same change in the same code. If that's not the case feel free to ignore me :)
