### ISSUE TITLE
Enum generation error for GstMpegts

### ISSUE THREAD

**Issue by russel** [gtk-rs/gir#600]
In the file GstMpegts-1.0.gir there is an enum with specification starting:
```xml
    <enumeration name="DVBCodeRate" c:type="GstMpegtsDVBCodeRate">
      <member name="none" value="0" c:identifier="GST_MPEGTS_FEC_NONE">
      </member>
      <member name="1_2" value="1" c:identifier="GST_MPEGTS_FEC_1_2">
      </member>
      <member name="2_3" value="2" c:identifier="GST_MPEGTS_FEC_2_3">
      </member>
      <member name="3_4" value="3" c:identifier="GST_MPEGTS_FEC_3_4">
      </member>
      <member name="4_5" value="4" c:identifier="GST_MPEGTS_FEC_4_5">
      </member>
```
this generates the output starting:
```rust
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub enum DVBCodeRate {
    None,
    12,
    23,
    34,
    45,
```
which isn't valid Rust code. :-(

Am I just missing an option in using `gir`:
```
gir -d ../gir-files -o . -c ../Gir_GstMpegts.toml
```

**Comment by EPashkin** [comment]
We don't support enum member renaming now.
Currently is solution for normal mode:
mark it manual https://github.com/gtk-rs/glib/blob/master/Gir.toml#L35,
and implement it manually https://github.com/gtk-rs/glib/blob/master/src/enums.rs#L13-L44
Note: My type don't contains `FromGlib` as it only passed as parameter,
in your case just copy and fix all generated code from `auto/enums.rs`

**Comment by russel** [comment]
I am wondering though if the Gir code generator should just use the `c:identifier` in these situations when `name` is not a valid Rust identifier.

**Comment by russel** [comment]
Is it possibly arguable that the Gir file is wrong to have enum members with names like 1_2, and that the Gir file should change?

I am guessing that it is only required to do the one enum manually just now, that all the others can be left as auto? Thus there will be src/enum.rs and src/auto/enum.rs

**Comment by EPashkin** [comment]
Changing GstMpegts-1.0.gir file is also options, then you need maintain changes.
but doing it will also solve problem with docs if you plan use doc strings for .gir.

Yes, on manual case, only one enum need be manual, and will be two `enum.rs` files.

**Comment by russel** [comment]
I have got round the two enums that have "illegal" member names by doing the manual thing. It works but isn't ideal – it is a maintenance problem in the case the GIR file changes.

How are the GIR files generated, are they automatically generated from the C library or are they hand generated? If the latter then amending is feasible.

**Comment by sdroege** [comment]
Autogenerated

**Comment by russel** [comment]
@sdroege I had thought so and yet some of the names in the XML are not legal symbols for C code. I shall have a delve and see what I can find.

**Comment by russel** [comment]
I wonder if the GIR name generation could be seen to be at fault here, resulting in labels that are not valid symbols in most programming languages, and thus stopping autogeneration of bindings.

Take `GstMpegtsModulationType` it has members such as `GST_MPEGTS_MODULATION_QAM_256` which gets truncated to `Qam246`. It seems the `GST_MPEGTS` is stripped because it is the library name, entirely reasonable since autogeneration can either add it back if need be or allow the module system naming to add it implicitly. Then the `MODULATION` gets removed. If this is because the string is part of the type name, that is fine, if it is because it is not the last two components of the name that is wrong (at least in my view).

Now take `GstMpegtsDVBCodeRate` one of its members is `GST_MPEGTS_FEC_1_2`. Strip the library name as per usual, fine, but now it strips the `FEC`, which is not mentioned in the type name so should be kept, but it is stripped, leaving `12` which is not a valid name in almost all programming languages, including C.

Thus I would argue this is actually a problem in the GIR XML generation. However I guess this is not going to be fixed there. I suspect it is not really a problem for GStreamer since the original symbols are perfectly valid C member symbols, and I suspect the GStreamer community will not accept a breaking change to fit the GIR generation algorithm, and why should they?

So we end up with a requirement for not using autogeneration of bindings. :-(

**Comment by tmiasko** [comment]
AFAIK for unregistered enums, which I presume is the case here, the
g-ir-scanner when forming the names removes the longest common prefix computed
at underscore boundaries. In this case the end result is not particularly good. 

As a workaround one can a) change the enumerators to get something more
reasonable, b) register the enum and customize the names, c) provide manual
implementation in Rust as suggested by EPashkin in comment https://github.com/gtk-rs/gir/issues/600#issuecomment-388878538
d) change algorithm gobject-introspection or add some for of rename annotations.

Variant c) is probably the easiest way to solve it. a), b) and c) would be
potentially useful more generally, but also introduce breaking changes.

**Comment by sdroege** [comment]
> So we end up with a requirement for not using autogeneration of bindings. :-(

You only need that for the enums for now. I'm sure there are more things that need manual work though, gobject-introspection is far from perfect.

**Comment by sdroege** [comment]
How does it handle these enums in D?

**Comment by russel** [comment]
The generated code for `DVBCodeRate` is:
```d
public enum GstMpegtsDVBCodeRate
{
	NONE = 0,
	_1_2 = 1,
	_2_3 = 2,
	_3_4 = 3,
	_4_5 = 4,
	_5_6 = 5,
	_6_7 = 6,
	_7_8 = 7,
	_8_9 = 8,
	AUTO = 9,
	_3_5 = 10,
	_9_10 = 11,
	_2_5 = 12,
}
alias GstMpegtsDVBCodeRate DVBCodeRate;
```

**Comment by sdroege** [comment]
That seems like a potential workaround for us too, if `name` starts with a number, we let it start with an underscore instead.

**Comment by russel** [comment]
Also don't remove the _ from the names during Rust generation? In GstMpegts-1.0.gir things like name="1_2" result in 12 instead of _1_2. And name="qam_64" results in Qam64 instead of QAM_64, thugh maybe this needs to be Qam_64.

**Comment by sdroege** [comment]
No idea what the idiomatic Rust version of an enum with multiple number components would be, someone should check that first and then implement conversion accordingly.

**Comment by russel** [comment]
@sdroege It is not clear that anyone has thought about Rust enum variants with names like 1_2 at all,all the material out there assumes variant names such as V_1_2.

**Comment by sdroege** [comment]
`_1_2` should be fine then I guess

**Comment by ceyusa** [comment]
I have other examples of enums which auto-generated rust symbols are not valid

For example, [GstGLVersion](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gst-plugins-base-libs-GstGLSL.html#GstGLSLVersion):

GST_GLSL_VERSION_100 will generate an enum symbol named 100, which is not valid

Another example is [GstGLTextureTarget](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gst-plugins-base-libs-OpenGL-Formats.html#GstGLTextureTarget)

GST_GL_TEXTURE_TARGET_2D is generated as 2D, which isn't valid either.

**Comment by russel** [comment]
@EPashkin It seems the new gir solves the original problem, thanks for doing this.
