### ISSUE TITLE
Type inconsistency during generation

### ISSUE THREAD

**Issue by russel** [gtk-rs/gir#605]
Here is an example (one of many) of a generated function:
```rust
impl Descriptor {
    pub fn parse_ca(&mut self) -> Option<(u16, u16, u8, usize)> {
        unsafe {
            let mut ca_system_id = mem::uninitialized();
            let mut ca_pid = mem::uninitialized();
            let mut private_data = mem::uninitialized();
            let mut private_data_size = mem::uninitialized();
            let ret = from_glib(ffi::gst_mpegts_descriptor_parse_ca(self.to_glib_none_mut().0, &mut ca_system_id, &mut ca_pid, &mut private_data, &mut private_data_size));
            if ret { Some((ca_system_id, ca_pid, private_data, private_data_size)) } else { None }
        }
    }
```
Unfortunately at compile time this results in:
```
error[E0308]: mismatched types
  --> gstreamer-mpegts/src/auto/descriptor.rs:39:50
   |
39 |             if ret { Some((ca_system_id, ca_pid, private_data, private_data_size)) } else { None }
   |                                                  ^^^^^^^^^^^^ expected u8, found *-ptr
   |
   = note: expected type `u8`
              found type `*const u8`
```

**Comment by EPashkin** [comment]
Not enough info to say anything, at minimum needed sys function, even better with method .gir fragment.

**Comment by sdroege** [comment]
Missing annotation in GStreamer for marking the `private_data` as array with length `private_data_size`.

**Comment by sdroege** [comment]
I expect there to be more missing annotations like this in the mpegts library

**Comment by russel** [comment]
@sdroege This makes it sound as though the next step is to work on the problem as an MPEG-TS error, rather than progress this as a gir issue.

**Comment by sdroege** [comment]
One could add some more heuristics to gir to automatically detect this case, there are other cases already that look for variables with `_length` and `_len` as suffix IIRC. But yes, this should be fixed on the GStreamer side in any case.

**Comment by sdroege** [comment]
As I said, you can also implement heuristics for that and there are already some. Nonetheless the annotation is missing, and the D people should've filed a bug against GStreamer instead of just silently ignoring that issue.

**Comment by russel** [comment]
I'll get the Gtk-D people to do that. So I should shift working, at least temporarily, to getting MPEG-TS properly marked up for GIR production.

**Comment by russel** [comment]
GtkD person has a manual exceptions file that creates the correct types. I have asked for some bug reports, but maybe we can just make use of their exceptions file to drive correctly annotating the C code?

**Comment by russel** [comment]
cf. https://bugzilla.gnome.org/show_bug.cgi?id=796221

**Comment by GuillaumeGomez** [comment]
I guess it can be closed then? If not, don't hesitate to reopen!
