### ISSUE TITLE
Many warnings from external libraries

### ISSUE THREAD

**Issue by jsparber** [gtk-rs/gir#608]
I'm creating [libhandy rust bindings](https://gitlab.gnome.org/jsparber/libhandy-rs). I use gtk as external library therefore gir shows many warnings.
` WARN 2018-06-07T10:20:04Z: libgir::analysis::functions: Function gtk_widget_get_allocated_size has unsupported outs
 WARN 2018-06-07T10:20:04Z: libgir::analysis::functions: Function gtk_widget_get_allocation has unsupported outs
 WARN 2018-06-07T10:20:04Z: libgir::analysis::functions: Function gtk_widget_get_child_requisition has unsupported outs
 WARN 2018-06-07T10:20:04Z: libgir::analysis::functions: Function gtk_widget_get_clip has unsupported outs
 WARN 2018-06-07T10:20:04Z: libgir::analysis::functions: Function gtk_widget_get_preferred_size has unsupported outs
 WARN 2018-06-07T10:20:04Z: libgir::analysis::functions: Function gtk_widget_get_requisition has unsupported outs
 WARN 2018-06-07T10:20:04Z: libgir::analysis::functions: Function gtk_widget_intersect has unsupported outs
 WARN 2018-06-07T10:20:04Z: libgir::analysis::functions: Function gtk_widget_size_request has unsupported outs
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'button-press-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'button-release-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'child-notify'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'configure-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'damage-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'delete-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'destroy-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'direction-changed'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'drag-begin'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'drag-data-delete'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'drag-data-get'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'drag-data-received'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'drag-drop'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'drag-end'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'drag-failed'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'drag-leave'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'drag-motion'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'draw'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'enter-notify-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'event-after'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'focus'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'focus-in-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'focus-out-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'grab-broken-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'key-press-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'key-release-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'keynav-failed'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'leave-notify-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'map-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'motion-notify-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'move-focus'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'property-notify-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'proximity-in-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'proximity-out-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'query-tooltip'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'screen-changed'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'scroll-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'selection-clear-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'selection-get'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'selection-notify-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'selection-received'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'selection-request-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'show-help'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'size-allocate'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'state-changed'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'state-flags-changed'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'style-set'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'touch-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'unmap-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'visibility-notify-event'
 WARN 2018-06-07T10:20:04Z: libgir::analysis::trampolines: Can't generate Gtk.Widget trampoline for signal 'window-state-event'
`

**Comment by EPashkin** [comment]
@jsparber You right, we better don't warn if not in main namespace.
