### ISSUE TITLE
Trim in get_c_value causes gstreamer-sys-rs tests to fail.

### ISSUE THREAD

**Issue by alatiera** [gtk-rs/gir#644]
While running the [gstreamer-rs-sys][1] tests, we stumbled in an issue with the `get_c_value` function which is auto generated in `tests/abi.rs`. In the log below, there an assertion of 2 Strings that is failing cause the leading space is [being trimmed][2]. The space exists in both the `.gir` file, the C headers and the generated C test file.

```
running 2 tests
test cross_validate_layout_with_c ... ok
test cross_validate_constants_with_c ... FAILED

failures:

---- cross_validate_constants_with_c stdout ----
constants ... 25 passed; 0 failed (compilation errors: 0)
constants ... 50 passed; 0 failed (compilation errors: 0)
constants ... 75 passed; 0 failed (compilation errors: 0)
Constant value mismatch for GST_AUDIO_FORMATS_ALL
Rust: " { S8, U8, S16LE, S16BE, U16LE, U16BE, S24_32LE, S24_32BE, U24_32LE, U24_32BE, S32LE, S32BE, U32LE, U32BE, S24LE, S24BE, U24LE, U24BE, S20LE, S20BE, U20LE, U20BE, S18LE, S18BE, U18LE, U18BE, F32LE, F32BE, F64LE, F64BE }"
C:    "{ S8, U8, S16LE, S16BE, U16LE, U16BE, S24_32LE, S24_32BE, U24_32LE, U24_32BE, S32LE, S32BE, U32LE, U32BE, S24LE, S24BE, U24LE, U24BE, S20LE, S20BE, U20LE, U20BE, S18LE, S18BE, U18LE, U18BE, F32LE, F32BE, F64LE, F64BE }"
constants ... 99 passed; 1 failed (compilation errors: 0)
constants ... 124 passed; 1 failed (compilation errors: 0)
constants ... 149 passed; 1 failed (compilation errors: 0)
constants ... 174 passed; 1 failed (compilation errors: 0)
thread 'cross_validate_constants_with_c' panicked at 'FAILED: 192 passed; 1 failed (compilation errors: 0)', gstreamer-audio-sys/tests/abi.rs:126:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    cross_validate_constants_with_c

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p gstreamer-audio-sys --test abi'
```

[1]: https://github.com/sdroege/gstreamer-sys/issues/16#issue-370295579
[2]: https://github.com/sdroege/gstreamer-sys/blob/a4113052f298e0d7b1d1111bb057fab2de12ed37/gstreamer-audio-sys/tests/abi.rs#L230

**Comment by sdroege** [comment]
The `trim()` in question is this one here: https://github.com/gtk-rs/gir/blob/ffda6f9b6917f92f6b25f593bc59513c1a5ee82d/src/codegen/sys/tests.rs#L450

@EPashkin do you remember why this is there? And same question for the other trims. We control what we output to stdout, so it should always be exactly what we expect or not?

**Comment by EPashkin** [comment]
@sdroege To remove '\r', see https://github.com/gtk-rs/gir/commit/ccc39034795e1710ce10ee87a1db16b30508d35e 😉

**Comment by sdroege** [comment]
I guess we should remove less then. Also: string constants could contain a valid `\r` at the end.

**Comment by EPashkin** [comment]
You added it 😉 .
IMHO this just some typo in .gir, Ex. GST_VIDEO_FORMATS_ALL don't have spaces before,
Seems string constants need different test, Ex. "\"{}"\"", maybe it can be applied to all

**Comment by sdroege** [comment]
It's in the C header with the space. It is a typo there but that shouldn't matter :) There might be valid string constants with whitespace at the front or end.

Maybe we could just use printf without a newline?

**Comment by sdroege** [comment]
Or alternatively as you say, with some marker at the front and the end
