### ISSUE TITLE
gir does not generate mutable arrays in some cases

### ISSUE THREAD

**Issue by alatiera** [gtk-rs/gir#648]
Running the `gstreamer-sys` abi tests hit the following Layout missmatch.

**From the `gstreamer-sdp-sys` tests**

```
Layout mismatch for GstMIKEYPayloadKeyData
Rust: Layout { size: 112, alignment: 8 }
C:    Layout { size: 128, alignment: 8 }
```
Here is the C definition:

```
typedef struct {
  [...]
  guint8   kv_len[2];
  guint8  *kv_data[2];
} GstMIKEYPayloadKeyData;
```
and the currently generated Rust one

```rust
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GstMIKEYPayloadKeyData {                                                                              
    [...]
    pub kv_len: [u8; 2], 
    pub kv_data: [u8; 2],
}
```

@sdroege's comment:
> `kv_data` should be a `[*mut u8; 2]` instead. In the .gir file it looks correct, compare with the e.g. salt_data field (which is a `*mut u8`, not as an array).

**From the `gstreamer-mpegts-sys` tests**

```
Layout mismatch for GstMpegtsISO639LanguageDescriptor
Rust: Layout { size: 324, alignment: 4 }
C:    Layout { size: 776, alignment: 8 }
```

Here is the C definition

```c
typedef struct _GstMpegtsISO639LanguageDescriptor GstMpegtsISO639LanguageDescriptor;
struct _GstMpegtsISO639LanguageDescriptor                                                                        
{
  guint                    nb_language;
  gchar                    *language[64];
  GstMpegtsIso639AudioType audio_type[64];
};
```
and the currently generated Rust one

```rust
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GstMpegtsISO639LanguageDescriptor {                                                                   
    pub nb_language: c_uint,
    pub language: [c_char; 64],
    pub audio_type: [GstMpegtsIso639AudioType; 64],
}
```

@sdroege's comment:
> Basically the same things as in the SDP library. The language field should be a `[*mut c_char; 64]`.

**Comment by sdroege** [comment]
@EPashkin any ideas why this happens?

**Comment by EPashkin** [comment]
Seems we lose inner c_type in https://github.com/gtk-rs/gir/blob/master/src/library.rs#L608

**Comment by sdroege** [comment]
This is solved now, and also in gstreamer-rs-sys: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs-sys/commit/75cda423fed2e58b41ca5d955ac870bd13ef3d82

@GuillaumeGomez please close :)

**Comment by GuillaumeGomez** [comment]
@EPashkin could as well. :p
