### ISSUE TITLE
Misgenerates arrays as scalar u8 in sys-mode

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#654]
.gir file change is the following

```diff
@@ -5714,7 +5714,7 @@ and will be packed into @data.</doc>
         </parameter>
         <parameter name="src" transfer-ownership="none">
           <doc xml:space="preserve">a source array</doc>
-          <array zero-terminated="0" c:type="gpointer">
+          <array zero-terminated="0" c:type="const gpointer">
             <type name="guint8"/>
           </array>
         </parameter>
```

and it causes this

```diff
@@ -249,8 +249,8 @@ pub const GST_AUDIO_RESAMPLER_FLAG_VARIABLE_RATE: GstAudioResamplerFlags = 4;
 // Callbacks
 pub type GstAudioBaseSinkCustomSlavingCallback = Option<unsafe extern "C" fn(*mut GstAudioBaseSink, gst::GstClockTime, gst::GstClockTime, *mut gst::GstClockTimeDiff, GstAudioBaseSinkDiscontReason, gpointer)>;
 pub type GstAudioClockGetTimeFunc = Option<unsafe extern "C" fn(*mut gst::GstClock, gpointer) -> gst::GstClockTime>;
-pub type GstAudioFormatPack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, gpointer, gpointer, c_int)>;
-pub type GstAudioFormatUnpack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, gpointer, gpointer, c_int)>;
+pub type GstAudioFormatPack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, u8, gpointer, c_int)>;
+pub type GstAudioFormatUnpack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, gpointer, u8, c_int)>;
 pub type GstAudioRingBufferCallback = Option<unsafe extern "C" fn(*mut GstAudioRingBuffer, *mut u8, c_uint, gpointer)>;
 
 // Records
```

**Comment by sdroege** [comment]
Not sure why the `const` would confuse it, any guess @EPashkin? :)

**Comment by EPashkin** [comment]
"gpointer" has special fix in https://github.com/gtk-rs/gir/blob/master/src/codegen/sys/ffi_type.rs#L32
So maybe it reason

**Comment by sdroege** [comment]
Also adding `const gpointer` there makes no difference

**Comment by sdroege** [comment]
Can't find the culprit and have to leave for a while now. It's definitely the additional `const` though, removing that from the .gir file makes it generate the right thing again

**Comment by EPashkin** [comment]
Seems problem in parser and base types:

Changing `const gpointer` to `gconstpointer` will produce normal diff
```diff
--- a/gstreamer-audio-sys/src/lib.rs
+++ b/gstreamer-audio-sys/src/lib.rs
@@ -249,8 +249,8 @@ pub const GST_AUDIO_RESAMPLER_FLAG_VARIABLE_RATE: GstAudioResamplerFlags = 4;
 // Callbacks
 pub type GstAudioBaseSinkCustomSlavingCallback = Option<unsafe extern "C" fn(*mut GstAudioBaseSink, gst::GstClockTime, gst::GstClockTime, *mut gst::GstClockTimeDiff, GstAudioBaseSinkDiscontReason, gpointer)>;
 pub type GstAudioClockGetTimeFunc = Option<unsafe extern "C" fn(*mut gst::GstClock, gpointer) -> gst::GstClockTime>;
-pub type GstAudioFormatPack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, gpointer, gpointer, c_int)>;
-pub type GstAudioFormatUnpack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, gpointer, gpointer, c_int)>;
+pub type GstAudioFormatPack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, gconstpointer, gpointer, c_int)>;
+pub type GstAudioFormatUnpack = Option<unsafe extern "C" fn(*const GstAudioFormatInfo, GstAudioPackFlags, gpointer, gconstpointer, c_int)>;
 pub type GstAudioRingBufferCallback = Option<unsafe extern "C" fn(*mut GstAudioRingBuffer, *mut u8, c_uint, gpointer)>;
 
 // Records
```

**Comment by EPashkin** [comment]
Maybe problem lies in gstreamer or introspection

**Comment by sdroege** [comment]
It always was `const gpointer` there but gobject-introspection seemed to have ignored that for now. Now it's correct.

IMHO this is a bug in gir somewhere. It should treat `const gpointer` the same as `gconstpointer`. Just like it treats `const guint8 *` as the const variant of `guint8 *`.

**Comment by EPashkin** [comment]
IMHO as `const void *` already have name `gconstpointer`,
using `const gpointer` for it is slightly wrong even if C type is same.

**Comment by EPashkin** [comment]
From gir side problem that "const gpointer" don't contains "*" (as in `const gunin*`) so `rustify_pointers` and others process it wrong,
and as "gtk" use only `gconstpointer` I still think that adding hacked fix in parser for accept `const gpointer` is not right and better fixed in gstreamer.

**Comment by sdroege** [comment]
Similar problems with `const gpointer foo[]` but this one can't actually be changed and is correct. Without the const it becomes `*mut gpointer`, with the const it becomes `gpointer` but should be `*const gpointer`

So something to fix on our side. `gpointer` should be handled as if it contained an `*` :)

**Comment by EPashkin** [comment]
@sdroege Can you give real usage Ex. in gsteamer?

**Comment by sdroege** [comment]
Nevermind, those cases actually are correct for whatever reason :) Sorry for the noise
