### ISSUE TITLE
Use quote crate instead of string interpolation to generate code

### ISSUE THREAD

**Issue by meh** [gtk-rs/gir#661]

**Comment by sdroege** [comment]
@meh what's the status of this? :)

**Comment by sdroege** [comment]
@meh any updates?

**Comment by bilelmoussaoui** [comment]
As per #919, this doesn't sound like a viable approach. Maybe the issue should be closed?

**Comment by sdroege** [comment]
IIRC we use quote in a few places. Let's just do that where it's useful.
