### ISSUE TITLE
Should split ext traits based on requirements, or remove requirements

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#670]
Example:

`impl<O: IsA<Window> + IsA<glib::object::Object> + glib::object::ObjectExt> GtkWindowExt for O {}`

This means that just doing `fn my_function<T: IsA<Window>>(window: &T)` is not enough to get access to the trait functions but all requirements would have to be added.

Maybe the clean solution would be to remove all requirements apart from `IsA<Window>` and get to the other ones via unsafe code (`IsA<Window>` is already implying them after all!).

**Comment by EPashkin** [comment]
It will be good.
Extra requirements seems added only in https://github.com/gtk-rs/gir/blob/master/src/codegen/object.rs#L217-L232.
For splitting at first glance problem will be only docs and naming (Ex. `+ IsA<glib::object::Object>` added for 3 separate cases)
for removing: `+ Clone + 'static` not implied by `IsA<Window>`.

**Comment by EPashkin** [comment]
As third alternative:
We can define new trait (name can be changed: Ex. `IsWindow`):
```
//in auto/window.rs
trait WindowImpl: IsA<Window> + IsA<glib::object::Object> + glib::object::ObjectExt {}

impl<O: IsA<Window> + IsA<glib::object::Object> + glib::object::ObjectExt> WindowImpl for O {}


//in user code:
fn my_function<T: WindowImpl>(window: &T) {
  let b = window.activate_default();
  let b2 = GtkWindowExt::activate_focus(window);
}
```

**Comment by sdroege** [comment]
`WindowImpl` will be the name of the trait that is used for subclassing :)

Personally I'd prefer going with doing this with unsafe code if we can't get rid of the duplicate requirements otherwise.

**Comment by EPashkin** [comment]
By way: can you give example of unsafe code (only `glib::object::ObjectExt` needed)?
```
fn emit_activate_focus(&self) {
    let _ = self.emit("activate-focus", &[]).unwrap();
}
```

**Comment by sdroege** [comment]
FWIW, I started working on this yesterday and as part of this work we'll also get https://github.com/gtk-rs/glib/issues/222 . Lots of untangling of traits necessary

**Comment by sdroege** [comment]
I've a WIP branch for this at https://github.com/gtk-rs/gir/pull/672. It works for the crates I tried, produces some new unused use statements currently and needs some cleanup (I also found some optimizations we can do on the way in the generated code).

Can you review this already to see if the approach taken makes sense to you? Among other things this also makes the extension traits object-safe
