### ISSUE TITLE
Incorrect generated code for multi-dimensional arrays

### ISSUE THREAD

**Issue by bochecha** [gtk-rs/gir#682]
IBus has the following `struct` in `ibus-1.0/ibuskeymap.h`:

```c
struct _IBusKeymap {
    /*< private >*/
    IBusObject parent;
    /* members */
    /*< public >*/
    gchar *name;
    guint keymap[256][7];
};
```

The corresponding generated sys crate is:

```rust
pub struct IBusKeymap {
    pub parent: IBusObject,
    pub name: *mut c_char,
    pub keymap: [c_uint; 256],
}
```

The problem is that `keymap` is originally a double array (256x7), but in Rust that second dimension is completely lost.

This causes the sys tests to fail:

```
---- cross_validate_layout_with_c stdout ----
layout    ... 25 passed; 0 failed (compilation errors: 0)
Layout mismatch for IBusKeymap
Rust: Layout { size: 1072, alignment: 8 }
C:    Layout { size: 7216, alignment: 8 }
layout    ... 49 passed; 1 failed (compilation errors: 0)
layout    ... 74 passed; 1 failed (compilation errors: 0)
thread 'cross_validate_layout_with_c' panicked at 'FAILED: 76 passed; 1 failed (compilation errors: 0)', ibus-sys/tests/abi.rs:126:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by EPashkin** [comment]
This is problem field:
```
      <field name="keymap">
        <doc xml:space="preserve">Keymap table. IME developers normally don have to touch this.</doc>
        <array zero-terminated="0" c:type="guint" fixed-size="256">
          <type name="guint" c:type="guint"/>
        </array>
      </field>
```
Not sure that Gir can generate it right even if IBus-1.0.gir fixed,
also this class can't be generated in normal mode and need be written manually.

**Comment by EPashkin** [comment]
So there next possible solutions:
1) Attempt to add inner array in field,
2) Make `IBusKeymap` ignored and write it right (maybe with all its functions) in other file near `lib.rs` (like https://github.com/gtk-rs/sys/blob/master/glib-sys/src/manual.rs), Gir will add `mod manual.rs; use pub use manual::*;` to `lib.rs` on next regen

**Comment by EPashkin** [comment]
IMHO it need inner `<array zero-terminated="0" c:type="guint" fixed-size="7">` around `type` node

**Comment by bochecha** [comment]
@sdroege yes, I wanted to report the issue to gobject-introspection after @EPashkin's first comment, which is why I asked what he thought would be the correct gir. (I had a feeling it would be something like what they suggested, but didn't want to make an uninformed guess)

I have just done that now: https://gitlab.gnome.org/GNOME/gobject-introspection/issues/255

---

Also, I have just tried fixing the gir manually as suggested, then the generated Rust code becomes:

```rust
pub struct IBusKeymap {
    pub parent: IBusObject,
    pub name: *mut c_char,
    pub keymap: [[c_uint; 7]; 256],
}
```

And the layout test passes this time.

So I guess everything is fine with regards to the gir tool, it really only is a bug in gobject-introspection.

Thanks for your help in diagnosing this. :slightly_smiling_face:

(I think I won't bother with a manual binding because I personally only need the parts of IBus necessary to write an engine, and this will be fixed in GI eventually anyway, leading to `IBusKeymap` support automatically as soon as I grab the new gir file)
