### ISSUE TITLE
-sys/-ffi module names confusion

### ISSUE THREAD

**Issue by bochecha** [gtk-rs/gir#685]
The generated code for the safe crate will have lines like:

```rust
use glib_ffi;
```

After looking at other crates, I eventually figured out that this was about the glib-sys crate, so I simply added the following to my `src/lib.rs`:

```rust
extern crate glib_sys as glib_ffi;
```

This seems entirely unnecessary, and is not obvious at all for a newcomer.

Any reason the generated code can't just use the `*_sys` name?

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege Any cons for removing name "xx_ffi" and always use "xx_sys" in code?

**Comment by GuillaumeGomez** [comment]
Sounds good to me.

**Comment by sdroege** [comment]
Fine with me, this annoyed me too

**Comment by GuillaumeGomez** [comment]
If that annoyed everyone, then why did we add it? XD

**Comment by sdroege** [comment]
I don't know, that's how I found it :) Why was it done?

**Comment by GuillaumeGomez** [comment]
No clue either. Maybe @EPashkin knows about it?

**Comment by EPashkin** [comment]
At minimum I don't remember why 😢

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege All main crates updated and linked here

**Comment by GuillaumeGomez** [comment]
Perfect, that makes things easier. :)

**Comment by sdroege** [comment]
This can be closed now or not?

**Comment by EPashkin** [comment]
Webkit still not processed

**Comment by EPashkin** [comment]
Webkit will be done as part https://github.com/gtk-rs/webkit2gtk-rs/issues/48

**Comment by EPashkin** [comment]
Now issue solved
