### ISSUE TITLE
Some callbacks are misgenerated

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#712]
See https://github.com/gtk-rs/gtk/pull/770#issuecomment-458495560 and comments on the specific code with explanations right below.

@GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Problem comes from bad interpretation of `<type name="GObject.Object" c:type="gpointer"/>` for `GtkFlowBoxCreateWidgetFunc`. We should do like we do in `sys` (just like @sdroege said).
