### ISSUE TITLE
Into<Option<_>> considered harmful

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#713]
For closures this requires type annotations everywhere to make the compiler happy and we should really remove it there to make those functions easy to use for the user. Adding a `Some()` around the closure is easy, annotating everything correctly not so much.

IMHO we should get rid of this in general also for other parameter types but that probably needs some wider discussion first. Apart from annotation mess (but less likely) it also makes it much harder for users to discover that they can also pass `None` (common question by people) and the type signature is harder to read.

**Comment by sdroege** [comment]
CC @EPashkin @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'll remove them for user callbacks. Until rust compiler becomes more intelligent at least. :)

**Comment by sdroege** [comment]
https://github.com/gtk-rs/gir/pull/714#issuecomment-458612568 has one example of what happens if we do the `Into<Option<_>>` stuff btw

**Comment by sdroege** [comment]
Oh! The signature for the closures is wrong!

```
R: for<'r> Fn(&'r glib::Object) -> Widget + 'static
```

that should work too. All reference parameters would need to get that lifetime.

**Comment by sdroege** [comment]
So, question is whether we need the `for<'r>`, we need to drop the `Into<Option<_>>`, or we need to do both. Can you try that @EPashkin, which of the combinations would work? I'm currently not a computer where I can test that :)

**Comment by EPashkin** [comment]
Ok, I check today

**Comment by EPashkin** [comment]
```
fn bind_model<'a, P: IsA<gio::ListModel> + 'a, Q: Into<Option<&'a P>>, R: for<'r> Fn(&'r glib::Object)
-> Widget + 'static, S: Into<Option<R>>>(&self, model: Q, create_widget_func: S);
```
builds fine: but problem still same as for current code.
listbox_model cases
clone! - no parameter type - E0282 (type annotations needed) on macro
no clone - no type - E0282 on parameter
no clone - type - ok
no clone - some - no type - E0282 on parameter
no clone - some - type - E0282 on bind_model

**Comment by EPashkin** [comment]
```
fn bind_model<'a, P: IsA<gio::ListModel> + 'a, Q: Into<Option<&'a P>>,
R: Fn(&glib::Object) -> Widget + 'static>(&self, model: Q, create_widget_func: Option<R>) {
```
without one create_widget_func.into():
clone! - no parameter type - E0282 (type annotations needed) on macro
no clone - some - no type - E0282 on parameter
no clone - some - type - ok

without both .into():
clone! - no parameter type - E0282 (type annotations needed) on macro
no clone - some - no type - E0282 on parameter
no clone - some - type - ok

```
fn bind_model<'a, P: IsA<gio::ListModel> + 'a, Q: Into<Option<&'a P>>,
R: for<'r> Fn(&'r glib::Object) -> Widget + 'static>(&self, model: Q, create_widget_func: Option<R>);
```
same as without for<'r>

**Comment by EPashkin** [comment]
Previous comment is same as result current #715

**Comment by EPashkin** [comment]
Playground without 715 https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9ae1420d808d1814453b0201e166438b

**Comment by EPashkin** [comment]
Other playground, I don't understand why functions `b2` and even `b2_5` don't work while `b1` works fine :cry:

**Comment by EPashkin** [comment]
Forgot link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c2ef60965d3f1def8ca77352a102ff96

**Comment by sdroege** [comment]
Oh now I remember why I did https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/blob/1adb063fbc4370edb80016532d0c79ca1b87bde2/gstreamer/src/bus.rs#L126-142 ! You simply can't create a `None` variant of `Option<Fn()>` because the `Fn` type is anonymous.

We can't use an `Option<_>` here but would need a second function for using `None`.

**Comment by EPashkin** [comment]
So current solution - just remove `Into<Option` for functions now and add `None` case later?

**Comment by sdroege** [comment]
The problem is that you need to be able to use the functions with a `None` closure in some cases, see my example above where I added an `unset()` function in addition.

Maybe we should ignore `nullable` for now, generate without `Option<_>` but instead print a warning that this tells the user that this is not properly supported right now and they should add a `None` variant of the function manually?

FWIW, another place where I had such a problem I solved it with the `Builder` pattern: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/blob/1adb063fbc4370edb80016532d0c79ca1b87bde2/gstreamer-app/src/app_sink.rs#L50 (Note that `Option<Box<Fn()>>` is fine as the type is fixed and nameable, it's always a trait object)

**Comment by sdroege** [comment]
For example, for the `bind_model()` functions we probably want a `unset_model()` function for the time being to be able to set `None`.

**Comment by sdroege** [comment]
Another thing I just discussed with @GuillaumeGomez would be to use trait objects in the signatures if it's nullable. I.e.

`fn foo(func: Option<&dyn Fn()>)` for `scope call` and `fn foo(func: Option<Box<dyn Fn()>>)` for the other cases. This requires the user to box things already and it requires code to be generated differently for these cases wherever the closure is involved.

**Comment by sdroege** [comment]
```rust
fn foo(func: Option<&mut dyn FnMut()>) {
    if let Some(func) = func {
        func();
    }
}

fn bar(func: Option<Box<dyn FnMut()>>) {
    if let Some(mut func) = func {
        func();
    }
}

fn main() {
    foo(Some(&mut || println!("meh")));
    bar(Some(Box::new(|| println!("meh"))));
    foo(None);
    bar(None);
}
```
for an example.

This does not work for `FnOnce` and for `Fn` we don't need the `mut`.

Note that `Option<&dyn Fn()>` is two pointers big, as is the boxed variant. It needs another `&` to pass it to C as a single pointer (and two dereferences), and another `Box` in the other case.

**Comment by sdroege** [comment]
For `FnOnce` in the boxed case we can use https://crates.io/crates/boxfnonce in theory, or some other hack. Let's see if I can come up with a hack for the boxed case.

**Comment by sdroege** [comment]
Ok, plan now is
* Keep non-nullable things as-is
* `Fn` and `FnMut` nullable cases as above via trait objects (boxed or not)
* `FnOnce` nullable case commented out for the time being (I'm not aware of any such function anyway)

@EPashkin what do you think?

**Comment by EPashkin** [comment]
Lets try this approach. @sdroege, @GuillaumeGomez Thanks for finding solution.
