### ISSUE TITLE
Improve `Display` implementations

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#725]
As said in https://github.com/gtk-rs/gtk/pull/789, current `Display` implementations aren't very nice. However, making something working in all cases seems close to impossible. However, some improvements can still be made!

**Comment by bilelmoussaoui** [comment]
With https://github.com/gtk-rs/gir/pull/1502, we will fully drop the current Display implementation and let the bindings maintainers implement Display where it makes sense.
