### ISSUE TITLE
crate_name vs package_name problem

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#731]
Currently we have packages on https://crates.io with names like "gtk-sys",
but it include in lib.rs file as `extern crate glib_sys`,
this cause some obscurity for me especially in "codegen/sys/".
I propose fixate these name as next terms:
- `package_name` - name with `-` as in crates.io,
- `crate_name` - name with underscores as in code,

and change Gir codebase accordingly.

IMHO this better done before related issue #685

**Comment by sdroege** [comment]
On crates.io it should be with `-` and in code it should be with `_`, simply by converting all dashes to underscore when generating code.

Not sure what the problem here is exactly?

**Comment by EPashkin** [comment]
Problem that it both types used in generation code and IMHO sometimes with same/wrong name.
Ex. crate_name usually '_' but sometimes it '-' (or vice versa).
So I propose fixate variable names and add comments for function like 'get_crate_name`.
As alternative we can not allow '_' go out function and exchange only with '-'-containing variables,
but this need constant string replacing on use.

**Comment by sdroege** [comment]
I'd always use the version with `-` in the code, and only in the places where it has to be converted (when writing actual code files), convert it.

**Comment by EPashkin** [comment]
Ok, then after `Into` removed,
I will add `nameutil::underscored_crate_name(crate_name: &str)` and recheck all "- vs _"-replacing.

**Comment by EPashkin** [comment]
@sdroege Situation inversed: '-' used only in `cargo.toml` generation, so main will be underscored version.

**Comment by sdroege** [comment]
Ok, I thought the `-` would be more like the "main" one as that's the actual name of the crate.
