### ISSUE TITLE
Adds unused glib::GString imports

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#735]
E.g. here
```
warning: unused import: `glib::GString`
  --> gstreamer-editing-services/src/auto/track_element.rs:14:5
   |
14 | use glib::GString;
   |     ^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

warning: unused import: `glib::GString`
  --> gstreamer-gl/src/auto/glsl_stage.rs:11:5
   |
11 | use glib::GString;
   |     ^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default
```

Code is [here](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/blob/631eee13da3322bb1d6d254c09e9e8a8941f093e/gstreamer-editing-services/src/auto/track_element.rs) and [here](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/blob/631eee13da3322bb1d6d254c09e9e8a8941f093e/gstreamer-gl/src/auto/glsl_stage.rs).

CC @philn

**Comment by sdroege** [comment]
It's probably from the `&[&str]` parameters?

**Comment by philn** [comment]
Most likely :(
