### ISSUE TITLE
Add support for defining alignment of FFI structs

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#736]
This would mean adding `#[repr(align(XXX))]` to the struct definitions, e.g.

```rust
#[repr(C)]
#[repr(align(16))]
struct Foo {
    x: u8,
}
```

Currently this would have to be done via configuration, but ideally there would be a gobject-introspection annotation for that.

@EPashkin Can we do per-type configuration in -sys mode right now?

**Comment by EPashkin** [comment]
At minimum we can ignore, same type `config::GObject` used

**Comment by sdroege** [comment]
Ok, so let's add a `align` configuration and only use that in `-sys` mode to generate the corresponding attribute?

**Comment by EPashkin** [comment]
Yes
