### ISSUE TITLE
Rust 2018 support

### ISSUE THREAD

**Issue by a1ien** [gtk-rs/gir#746]
Can we add rust 2018 edition support? For now gir generate only 2015 version code.

**Comment by sdroege** [comment]
That would be great indeed. I believe @heftig was looking into this at some point?

**Comment by heftig** [comment]
I got stuck trying to disentangle the import (`use`) handling so it would create 2018-style statements.

**Comment by Boiethios** [comment]
Is there anything new about this? I'd like to use `async`/`.await` in the crate, but I cannot without the crate being in 2018 edition.

About the imports, a solution would be to use systematically the full path: either `crate::full::absolute::path` or `self::full::relative::path`, so it shouldn't be a problem.

**Comment by sdroege** [comment]
No news here but you can use the gtk-rs crates in 2018 crates, there's no problem with that. I have some async/await code using gtk-rs (and there's also https://github.com/gtk-rs/examples/blob/pending/src/bin/gio_futures_await.rs )

**Comment by Boiethios** [comment]
> No news here but you can use the gtk-rs crates in 2018 crates, there's no problem with that. I have some async/await code using gtk-rs (and there's also https://github.com/gtk-rs/examples/blob/pending/src/bin/gio_futures_await.rs )

I'm aware of that: that's the point of the editions. My purpose is to add some asynchronous functions beside the `auto` module containing the auto-generated code, though. Your solution would require to create another crate.

**Comment by sdroege** [comment]
> I'm aware of that: that's the point of the editions.

Well until the very latest glib release that was not possible for the macros :)



> My purpose is to add some asynchronous functions beside the `auto` module containing the auto-generated code, though. Your solution would require to create another crate.

Yes in that case the code generator needs to be updated to output 2018 code. Do you want to work on that?

**Comment by heftig** [comment]
> Yes in that case the code generator needs to be updated to output 2018 code. Do you want to work on that?

I've tried upgrading the code generator at the last Rust+GNOME hackfest, and the biggest stumbling block was the [`use` path change](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html#use-paths).

**Comment by Boiethios** [comment]
> Yes in that case the code generator needs to be updated to output 2018 code. Do you want to work on that?

Sure, I can give it a try!

> I've tried upgrading the code generator at the last Rust+GNOME hackfest, and the biggest stumbling block was the [`use` path change](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html#use-paths).

Did you try the [`cargo fix --edition` command](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html#updating-your-code-to-be-compatible-with-the-new-edition)? Did you put what you've done in a branch?

**Comment by heftig** [comment]
> Did you try the [`cargo fix --edition` command](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html#updating-your-code-to-be-compatible-with-the-new-edition)?

I don't think running `cargo fix --edition` after code generation is feasible.

> Did you put what you've done in a branch?

Yeah, my flailing around is here: https://github.com/heftig/gir/commit/1dceca9961045b58b753a4b0eed36cb76f884344 I gave up on it, though.

I did, however, port the generator itself to 2018 and this work is https://github.com/gtk-rs/gir/pull/759, which was already merged.
