### ISSUE TITLE
Erroneously Cannot Parse Array Fields Without c:type

### ISSUE THREAD

**Issue by BrainBlasted** [gtk-rs/gir#749]
Sometimes you may have a record like this:

```xml
    <record name="ListBoxClass"
            c:type="DzlListBoxClass"
            glib:is-gtype-struct-for="ListBox">
      <source-position filename="Projects/libdazzle/src/widgets/dzl-list-box.h"
                       line="39"/>
      <field name="parent_class">
        <type name="Gtk.ListBoxClass" c:type="GtkListBoxClass"/>
      </field>
      <field name="_reserved" readable="0" private="1">
        <array zero-terminated="0" fixed-size="4">
          <type name="gpointer" c:type="gpointer"/>
        </array>
      </field>
    </record>
```

Fields like _reserved that are missing the `c:type` attribute fail to parse, leading to this error:

```
[2019-04-24T19:44:19Z ERROR libgir::library_postprocessing] Field `ListBoxClass::_reserved` is missing c:type
```
In reality, these types were not supposed to have the `c:type` attribute: https://gitlab.gnome.org/GNOME/gobject-introspection/commit/1f0965e379035be51ae96d5761358ec088fb3421 and https://gitlab.gnome.org/GNOME/gobject-introspection/commit/58e97dc13e33fc4fdfe83090fbde8ecc40662386

**Comment by BrainBlasted** [comment]
I think the issue is this check right here: https://github.com/gtk-rs/gir/blob/master/src/library_postprocessing.rs#L314

**Comment by EPashkin** [comment]
@BrainBlasted #880 did not broke sys part of libdazzle-rs?

**Comment by BrainBlasted** [comment]
I will need to regen and check.
