### ISSUE TITLE
Use disguised="1" in gir files

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#760]
Before we don't use disguised flag because it was in many wrong places
```
        // Currently g-ir-scanner is too eager to mark all typedef to non-complete
        // types as disguised, so we limit this behaviour to the two most common cases.
        // https://gitlab.gnome.org/GNOME/gobject-introspection/issues/101
        let disguised = c_type == "GdkAtom" || c_type == "GIConv";
```
Seems problem fixed now and we can start of using this flag.

I created this PR as linking place for all related PRs,
please don't merge its until we decide that all is good.

cc @GuillaumeGomez, @sdroege

**Comment by GuillaumeGomez** [comment]
Good finding. That's great if we can fix this bug!

**Comment by EPashkin** [comment]
Last only sourceview with StyleExt removed and pangocairo with change usage of pango::*,
I will add it after we decide that to do.

**Comment by EPashkin** [comment]
Not sys changes because new detection for final types:
disguised type is final if it don't have children

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege, @antoyo 
All related PR is done.
Builders added to gtk, gio, for others I don't see good candidates.
Half PR passed CI (as always gtk has one error in apveyor).

**Comment by EPashkin** [comment]
All related PR merged, so I close this
