### ISSUE TITLE
Builder generation configuration

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#763]
#757 added possibility to generate object builder if it added to Gir.toml
```toml
generate_builders = [
    "Gtk.WindowBuilder",
]
```
I don't like this configuration method because it add new items to `GObjects`,
and its names theoretically can conflict with real objects.

I prefer this way
```
[[object]]
name = "Gtk.Window"
status = "generate"
generate_builder = true
```

@GuillaumeGomez, @sdroege , @antoyo  What you think about this?

PS. ~Current version also cause warning due misnaming~
```
warning: variant `Generate_Builders` should have an upper camel case name
  --> src\config\gobjects.rs:23:5
   |
23 |     Generate_Builders,
   |     ^^^^^^^^^^^^^^^^^ help: convert the identifier to upper camel case: `GenerateBuilders`
   |
   = note: #[warn(non_camel_case_types)] on by default
```

PPS. Not related to this issue, but GStatus.Comment also not used

**Comment by antoyo** [comment]
Would storing the objects in another vector be good enough?

**Comment by GuillaumeGomez** [comment]
I like the `generate_builder` option. In addition to this, why not having a vector (called "builders" for example?) where you could also declare them?

**Comment by EPashkin** [comment]
Storing object names for generate is better that current version,
but IMHO using names as flags is not good idea due typos etc.

**Comment by EPashkin** [comment]
Ok, lets leave current method for selecting builders,
listing is much simpler that add new [[object]] table.
@sdroege, @antoyo You don't mind renaming an array just to "builders"?

**Comment by sdroege** [comment]
What are the two options exactly? Can you give a short example? :) I don't understand

**Comment by EPashkin** [comment]
```diff
-generate_builders = [
+builders = [
     "Gtk.AboutDialogBuilder",
     "Gtk.AccelLabelBuilder",
     "Gtk.ActionBarBuilder",
```

**Comment by sdroege** [comment]
Works for me. But why not a property for the individual objects like we usually do for configuring things per object?

**Comment by EPashkin** [comment]
This thought was exactly reason why I created this issue,
but after adding builders to gtk I changed my mind

**Comment by sdroege** [comment]
>  but after adding builders to gtk I changed my mind

Why? Simplicity (separate array) winning against consistency (config inside the object array)? :)

**Comment by EPashkin** [comment]
Yes. "listing is much simpler that add new [[object]] table."

**Comment by GuillaumeGomez** [comment]
As long as we allow both, I'm fine (the list and adding a builder in a new `[[object]]` table).

**Comment by EPashkin** [comment]
@GuillaumeGomez for in object configuration `generate_builder = true` fits or do you prefer something shorter?

**Comment by GuillaumeGomez** [comment]
I think "generate_builder" is better in this case. More easy to read.

**Comment by EPashkin** [comment]
Ok, I will add this option
