### ISSUE TITLE
Use MaybeUninit instead of mem::unitialized

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#770]
The latter causes UB very easily, and e.g. the following already is UB from what I understand

```rust
let mut x = mem::uninitialized();
foo_sys::blabla(&mut x);
```

https://doc.rust-lang.org/std/mem/union.MaybeUninit.html

`MaybeUninit` is just being stabilized now: https://github.com/rust-lang/rust/pull/60445

**Comment by sdroege** [comment]
See https://gankro.github.io/blah/initialize-me-maybe/ for some more rationale for this change

**Comment by EPashkin** [comment]
As `mem::uninitialized` was deprecated in same PR seems we need increase minimum version too when time come

**Comment by GuillaumeGomez** [comment]
I'll do it in the next days I think. :)
