### ISSUE TITLE
Collision between generated type and glib helper type

### ISSUE THREAD

**Issue by fkrull** [gtk-rs/gir#772]
Since updating gir and glib on my project ([bindings for libostree](fkrull/ostree-rs)), it has started importing `glib::object::ObjectType` in at least one generated file. Unfortunately, libostree has a type `OSTree.ObjectType` which also gets imported into the same generated file. As you can probably imagine, [this breaks rather noisily](https://gitlab.com/fkrull/ostree-rs/-/jobs/214727451).

From my scan of the readme, I couldn't see an obvious way to rename an entire type. Even if there was, that's a solution I'd like to avoid. I didn't try setting `ObjectType` to manual either, but thinking about it, I guess that wouldn't work because the problem is in a file referencing the type.

**Comment by cgwalters** [comment]
Hm, in the general case maybe the generated code needs to avoid any "shorthand" imports at all and always do fully qualified names.

**Comment by EPashkin** [comment]
Its trait https://gtk-rs.org/docs/glib/object/trait.ObjectType.html, so it need be imported.
Only solution I see is renaming "OSTree.ObjectType" in .gir file,
but IMHO its not good.

**Comment by fkrull** [comment]
I agree that the only general solution is for the generated code to use absolute paths always. Looking at the codebase, that seems like a major undertaking though. It would also make the generated code less readable.

As for traits, you can do `use Trait as _` to get the trait into scope without colliding with other names: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=abdecf380c774a8ae21ecc306e746127

**Comment by EPashkin** [comment]
@fkrull Feel free to reopen issue if fix is not enough
