### ISSUE TITLE
Gir ignoring the sys [lib] name when generating API

### ISSUE THREAD

**Issue by BrainBlasted** [gtk-rs/gir#801]
When generating with https://github.com/gtk-rs/gir/commit/20feecf4fe8b4f3524715a0d4111f8c279666324 I came across this issue. The name designated in the [lib] section of the sys crate is ignored in favor of a generated name, meaning that the API bindings will not compile because they are looking for the wrong crate.

For example, I chose this name:

```toml
[lib]
name = "libhandy_sys"
```

But the API bindings generate with `handy_sys`:

```rust
error[E0432]: unresolved import `handy_sys`
  --> libhandy/src/auto/dialer_button.rs:15:5
   |
15 | use handy_sys;
   |     ^^^^^^^^^ no `handy_sys` in the root
```

**Comment by EPashkin** [comment]
Gir read only on .gir files and its config and ignores all others.
Usually we just import sys crate with right name https://github.com/gtk-rs/webkit2gtk-rs/blob/master/src/lib.rs#L23 or use `use libhandy_sys as handy_sys;`

**Comment by bilelmoussaoui** [comment]
@BrainBlasted Is this still an issue btw? I don't think so
