### ISSUE TITLE
Use function and objects `cfg_condition` in `use`

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#807]
Currently it not used if import added from function
```
use std::boxed::Box as Box_;

impl SubprocessLauncher {
    #[cfg(any(unix, feature = "dox"))]
    pub fn set_child_setup<P: Fn() + 'static>(&self, child_setup: P) {
        let child_setup_data: Box_<P> = Box::new(child_setup);
    }
}
```
Currently not generated objects `UnixMountEntry` and `UnixMountPoint` also imports without "cfg(unix)" so build fail on windows too (https://github.com/gtk-rs/gio/pull/227/files/d1f950cdf6ba97b43b2c9d5e8b19c1c24cfb62a0#diff-7c1fd3202079472b52d83736a5157c94)

**Comment by EPashkin** [comment]
Related issue: callback/async functions need always use `Box_` instead `Box`,
but direct fixing cause problem in `gtk::IconInfo` that have 
```
#[cfg(feature = "futures")]
use std::boxed::Box as Box_;
```
and many async functions.

Or maybe we better try to rename `gtk::Box` to `gtk::Box_` again?
cc @GuillaumeGomez, @sdroege

**Comment by GuillaumeGomez** [comment]
Strange, I thought this aliasing was done only on the std type, which would make more sense. Why did we add an alias on the gtk type?

**Comment by EPashkin** [comment]
Problem that async functions use `std::boxed::Box` without aliasing and we missed that because it auto-used.

**Comment by GuillaumeGomez** [comment]
Then let's just update how we import and use `std::boxed::Box` and we should be fine?

**Comment by EPashkin** [comment]
Yes, current issue about `update how we import`: it works strange and as result we can't simply replace "Box" to "Box_" in async functions.

**Comment by GuillaumeGomez** [comment]
This could be the start of the rewriting we're all hoping for. :D

**Comment by EPashkin** [comment]
Fixed https://github.com/gtk-rs/gio/pull/232#discussion_r312704883 and updated all related PRs.
Still in WIP due possible conflicts with https://github.com/gtk-rs/glib/pull/513

**Comment by EPashkin** [comment]
I close this as all related PRs are merged
