### ISSUE TITLE
Switch from mem::zeroed() to mem::MaybeUninit::zeroed() where it makes sense

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#811]
Same story as with `mem::uninitialized()` but less likely that we do it wrong somewhere currently.

@GuillaumeGomez Do you want to look into this? Should be basically the same change as you did before with uninitialized.

**Comment by GuillaumeGomez** [comment]
I guess I'll take a look at it. :)

**Comment by sdroege** [comment]
All done and can be closed :)
