### ISSUE TITLE
Get the signature of the "finish" methods from the gir file

### ISSUE THREAD

**Issue by Boiethios** [gtk-rs/gir#813]
The signature of the "finish" methods (to finish an asynchronous call) is usually the same, and gir is based on that standard. However, sometimes, that standard is not respected, for example in libgoa: https://github.com/nemequ/vala-girs/blob/eef9b2f23eccce46af487e23888268cbfd6c6284/gir-1.0/Goa-1.0.gir#L698

In this situation, the generated code cannot compile because the parameters are swapped. Is it possible to generate this kind of code by following the declaration in the gir files?

**Comment by GuillaumeGomez** [comment]
I'll take a look in the next days.
