### ISSUE TITLE
Extend docs-rs disabling libs linkage to dox feature?

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#821]
I just realised that it'd make sense to prevent libs linkage for the `dox` feature as well.

What do you think about it @sdroege @EPashkin ?

**Comment by EPashkin** [comment]
I agree, even IMHO not "as well" but "instead"

**Comment by GuillaumeGomez** [comment]
So just removing `docs-rs` and replace it with the `dox` one? I thought about it first but not sure if it's what we'd want. But the more I think about it, the more I think it is.

**Comment by EPashkin** [comment]
Yes. I'm talking about replacing

**Comment by EPashkin** [comment]
@Boiethios you don't have problem, if gir use only "dox" feature?

**Comment by Boiethios** [comment]
@EPashkin I've no problem with that, as long as there is the way to build the doc without the native library being installed.

**Comment by GuillaumeGomez** [comment]
Ok, I'll make the changes tomorrow.
