### ISSUE TITLE
Add doc aliases

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#824]
Some objects have to get their crate's name prepended so they don't get confused with the type from another crate (like `GtkApplication` for example). Maybe adding a `#[doc(alias = "Application")]` for these types would help the search in the docs?

**Comment by EPashkin** [comment]
IMHO this is good idea

**Comment by GuillaumeGomez** [comment]
We could add a new key with `doc_alias = "Something"`. However, I didn't stabilize the doc alias feature in rustdoc yet (the PR is open though: https://github.com/rust-lang/rust/pull/63236).

**Comment by sdroege** [comment]
@GuillaumeGomez This is fixed or not?

**Comment by GuillaumeGomez** [comment]
Oh right, `#[doc(alias = "...")]` is stable now. I should do that. :)

**Comment by sdroege** [comment]
@GuillaumeGomez That's https://github.com/gtk-rs/gir/pull/1014 or not?

**Comment by GuillaumeGomez** [comment]
No, not exactly. Here it's about adding the possibility to have an alias over a type. For example, we renamed `gtk::Application` to `gtk::GtkApplication`.
