### ISSUE TITLE
GIR doesn't seem to handle allow-none

### ISSUE THREAD

**Issue by Cogitri** [gtk-rs/gir#832]
Maybe I just don't understand that parameter correctly, but it seems to me that we should return an Option, e.g. in https://gtk-rs.org/docs/pango/struct.Layout.html#method.get_pixel_extents

**Comment by sdroege** [comment]
How would that work? While it's allowed to pass `NULL` as `out` pointers in C there, this only has the effect that the corresponding value would not be returned there. If we provide a non-`NULL` pointer then we'll always get a value (and in this case there is not even a possible `NULL` value that could be returned).

**Comment by Cogitri** [comment]
Alrighty then, there was some misunderstanding about this in IRC then, thanks for clearing this up.
