### ISSUE TITLE
Getters are expecting then unwrapping

### ISSUE THREAD

**Issue by etrombly** [gtk-rs/gir#834]
Commit #825 added an expect to the getters, but left the unwrap generated by nullable. This makes the getter try to unwrap the value twice.

**Comment by EPashkin** [comment]
Strange that wrong code passed type checker.
@etrombly can you show any wrongly generated getter?

cc @fengalin just in case

**Comment by EPashkin** [comment]
@etrombly Maybe you forgot to update glib?
This code compiled fine in gtk
```
    fn get_property_register_session(&self) -> bool {
        unsafe {
            let mut value = Value::from_type(<bool as StaticType>::static_type());
            gobject_sys::g_object_get_property(self.to_glib_none().0 as *mut gobject_sys::GObject, b"register-session\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().expect("Return Value for property `register-session` getter").unwrap()
        }
    }

```

**Comment by EPashkin** [comment]
If you use glib as package then you mostly need to use gir with same version.

**Comment by EPashkin** [comment]
Glib 0.8.1
`Generated by gir (https://github.com/gtk-rs/gir @ 7d51043)`
