### ISSUE TITLE
Handle dox feature like non-sys crates?

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#844]
Currently, non-sys crate's `dox` feature includes the highest version and other features. It'd be nice if the sys crates did the same so we don't have to include more than the `dox` feature when building on `docs.rs` ([example](https://github.com/gtk-rs/sys/blob/master/gdk-sys/Cargo.toml#L53)).

**Comment by EPashkin** [comment]
We have something other that version in sys crate?
IMHO versions always covered by "dox" so I don't see what we can do more.

**Comment by GuillaumeGomez** [comment]
No, what I meant is that it should be like this:

```
[features]
v1_35 = []
dox = ["v1_35"]

# docs.rs
features = ["dox"]
```

Instead of:

```
[features]
v1_35 = []
dox = []

# docs.rs
features = ["dox", "v1_35"]
```

It'd be more coherent with the other crates. If you think it's not worth it then I'll just close the issue and we're done. :)

**Comment by EPashkin** [comment]
As we always write version with "dox", we can just remove version for docs.rs (
I 👍 for this change
```
[features]
v1_33 = []
v1_35 = ["v1_33"]
dox = []

# docs.rs
features = ["dox"]
```

**Comment by GuillaumeGomez** [comment]
Let's go for it then!
