### ISSUE TITLE
Misgenerates -sys structs with fixed-size, non-pointer arrays

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#880]
The .gir file changed like this with the latest version of `gobject-introspection`.

```diff
       <field name="kv_data" writable="1">
-        <doc xml:space="preserve">key validity data</doc>
-        <array zero-terminated="0" c:type="guint8" fixed-size="2">
+        <doc xml:space="preserve"
+             filename="gstmikey.h"
+             line="512">key validity data</doc>
+        <array zero-terminated="0" fixed-size="2">
           <type name="guint8" c:type="guint8*"/>
         </array>
       </field>
```

This causes the generated struct to change like this
```diff
-    pub kv_data: [*mut u8; 2],
+    pub kv_data: *mut [*mut u8; 2],
```

The old version was correct. The C header looks like this

```c
  guint8  *kv_data[2];
```

@EPashkin Any ideas how we can handle this correctly again?

**Comment by sdroege** [comment]
A similar thing happens with

```diff
       <field name="language" writable="1">
-        <array zero-terminated="0" c:type="gchar" fixed-size="64">
+        <array zero-terminated="0" fixed-size="64">
           <type name="utf8" c:type="gchar*"/>
         </array>
       </field>
```
```diff
-    pub language: [*mut c_char; 64],
+    pub language: *mut [*mut c_char; 64],
```

```c
  gchar                    *language[64];
```

**Comment by sdroege** [comment]
Note that the problem is only the XML change, gir itself handles it still fine if the `c:type` attribute is still there.

**Comment by EPashkin** [comment]
It affect only sys struct or other places (functions?) or normal crates too?
I will check this today.

**Comment by EPashkin** [comment]
We have some of it in gtk from https://github.com/gtk-rs/sys/pull/138 too 😢 
https://github.com/gtk-rs/sys/pull/138/files#diff-5204882f9a7598022c4a99c55aa7f835R1308

**Comment by sdroege** [comment]
> It affect only sys struct or other places (functions?) or normal crates too?

Only sys struct fields from what I can see

**Comment by EPashkin** [comment]
Related issue #749, fix #752 add unchanged type

**Comment by sdroege** [comment]
@GuillaumeGomez Should probably also do a sys bugfix release for this. I wonder why this didn't show up with the tests in sys here? Also I saw these when reviewing but I thought you checked all the changes to see if they make sense :) Whenever regenerating, be very careful what changes/additions are included there.

**Comment by sdroege** [comment]
3 wrong cases in that PR, see https://github.com/gtk-rs/sys/pull/138#pullrequestreview-332266745 and following

**Comment by EPashkin** [comment]
Thanks for rechecking, then seems we can just set any string without "*" for FixedArrays in preprocess

**Comment by EPashkin** [comment]
or removing last "*" from inner c_type
