### ISSUE TITLE
Signal handler trampoline casts can cause crashes

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#901]
See https://github.com/gtk-rs/gir/pull/896#issuecomment-612642197 and following.

Unclear what exactly happens there. In this specific code, no cast at all is needed. My guess is that the two wildcard casts are happening to convert it to something else in the middle than what is needed.

**Comment by sdroege** [comment]
Another case (`gstreamer-app/src/app_sink.rs`):

```rust
            connect_raw(
                self.as_ptr() as *mut _,
                b"new-sample\0".as_ptr() as *const _,
                Some(*(&new_sample_trampoline::<F> as *const _ as *const _)),
                Box_::into_raw(f),
            )
```

For testing purposes I've added a lot of debug output:

```rust
        unsafe {
            let f: Box_<F> = Box_::new(f);
            let t = new_sample_trampoline::<F> as *const unsafe extern "C" fn(*mut gst_app_sys::GstAppSink, *mut libc::c_void) -> i32;
            dbg!(t);
            let t = t as *const unsafe extern "C" fn();
            dbg!(t);
            dbg!(*t);
            let t = new_sample_trampoline::<F> as unsafe extern "C" fn(*mut gst_app_sys::GstAppSink, *mut libc::c_void) -> i32;
            dbg!(t);
            let mut t = std::mem::transmute(t);
            dbg!(t);
            let u = &new_sample_trampoline::<F> as *const _ as *const _;
            dbg!(u);
            t = *u;
            dbg!(t);
            connect_raw(
                self.as_ptr() as *mut _,
                b"new-sample\0".as_ptr() as *const _,
                Some(t),
                Box_::into_raw(f),
            )
        }
```

This prints

```
[/home/slomo/Projects/rust/gstreamer-rs/gstreamer-app/src/app_sink.rs:295] t = 0x00005603710fe920
[/home/slomo/Projects/rust/gstreamer-rs/gstreamer-app/src/app_sink.rs:297] t = 0x00005603710fe920
[/home/slomo/Projects/rust/gstreamer-rs/gstreamer-app/src/app_sink.rs:298] *t = 0x247c894858ec8348
[/home/slomo/Projects/rust/gstreamer-rs/gstreamer-app/src/app_sink.rs:300] t = 0x00005603710fe920
[/home/slomo/Projects/rust/gstreamer-rs/gstreamer-app/src/app_sink.rs:302] t = 0x00005603710fe920
[/home/slomo/Projects/rust/gstreamer-rs/gstreamer-app/src/app_sink.rs:304] u = 0x000056037139a8fa
[/home/slomo/Projects/rust/gstreamer-rs/gstreamer-app/src/app_sink.rs:306] t = 0x6d61732d77656e75
```

The correct pointer that actually would work is `0x00005603710fe920`. `mem::transmute(trampoline as usize)` also gives that.

I don't see how we can get between functions pointers of different signatures without a `transmute`.

But the wildcard casts are definitely wrong and giving us random results.

**Comment by sdroege** [comment]
So this is what I gather:
- `new_sample_trampoline::<F>` gives us a zero-sized type that is specific for this very function
- `new_sample_trampoline::<F> as unsafe extern "C" fn ...` gives us an actual function pointer to that function, one that is not nullable. I can't figure out how to convert that to a different signature without transmute, but this one works fine with transmute
- `new_sample_trampoline::<F> as *const unsafe extern "C" fn ...` gives us an actual function pointer to that function, nullable. This can be casted to function pointers of different signatures, and can be transmuted to a `unsafe extern "C" fn ...` that works fine. Dereferencing this doesn't give us anything meaningful although it is actually of type `unsafe extern "C" fn ...`, which is confusing.
- `new_sample_trampoline::<F> as usize` also gives us a function pointer, but as integer. Can also be transmuted fine, this seems equivalent to the `*const unsafe extern "C" fn ...` case.
- `&new_sample_trampoline::<F>` gives us a reference to the above zero sized type and then the wildcard casts do random things, but in any case dereferencing this gives us garbage

**Comment by sdroege** [comment]
Some more data points (all the `*const fn()` cases work the same with `usize`)

```rust
fn foo() {
    println!("bla");
}

fn main() {
    unsafe {
        // Works
        let f = foo as fn();
        f();

        // Works
        let f = foo as *const fn();
        let f = std::mem::transmute::<_, fn()>(f);
        f();

        // Crashes
        let f = &foo as *const _ as *const fn();
        (*f)(); 
        
        // Crashes
        let f = &foo as *const _ as *const fn();
        let f = std::mem::transmute::<_, fn()>(f);
        f();        
        
        // Crashes
        let f = foo as *const fn();
        (*f)();
    }
}
```

**Comment by sdroege** [comment]
So I guess my remaining question is why any signal handler works at all currently. And the answer is that they don't.

@GuillaumeGomez did you run anything with those casts changed? :D All the examples are crashing for example (from the `activate` signal of `GApplication`).

**Comment by sdroege** [comment]
I think we should revert https://github.com/gtk-rs/gir/commit/5ca26d9e8400e8fa904f23c9dc8597241a7ba1d0 and then regenerate everything again, and also fix the manual code again. I don't think we can get things working without `transmute` in this case, and the way how things are not it will just crash instead.

**Comment by sdroege** [comment]
@EPashkin What do you think?

**Comment by GuillaumeGomez** [comment]
No I didn't, I thought it was included in gir CI... We should maybe worry about this. :-/

**Comment by sdroege** [comment]
We should add some tests making use of signal handlers, yes. gstreamer CI has those, but only for the plugins... so it only started falling apart once the gstreamer-rs changes were also merged.

**Comment by sdroege** [comment]
You prepare PRs for gir to revert that commit, and then to everything else to revert that broken part of the changes? I'll then update gstreamer-rs accordingly.

**Comment by EPashkin** [comment]
Yes, seems we need revert gir and others :(

**Comment by sdroege** [comment]
@EPashkin You revert and then once @GuillaumeGomez 's other PR is in things can be regenerated?

**Comment by sdroege** [comment]
Taken care of now
