### ISSUE TITLE
new_from_XXX() constructors should be generated as from_XXX()

### ISSUE THREAD

**Issue by gdesmott** [gtk-rs/gir#905]
The idiomatic way for Rust constructors is to be named `from_XXX()` instead of `new_from_XXX()`, see discussion on https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/459#note_470007

**Comment by sdroege** [comment]
Also `with_XXX()` instead of `new_with_XXX()`

**Comment by EPashkin** [comment]
IMHO its good idea, but problematic from doc's side

**Comment by sdroege** [comment]
Why? That could use the same rename rules

**Comment by gdesmott** [comment]
Something like this https://github.com/gtk-rs/gir/pull/929 ?

**Comment by sdroege** [comment]
Looks good to me, if it works :)

**Comment by gdesmott** [comment]
Tested with `gstreamer-rs`, looks like it does :)
