### ISSUE TITLE
Fix pango parsing (must be done in gir-files)

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#908]
New Pango (https://github.com/gtk-rs/gir-files/pull/52#issuecomment-619510085) add to gir use pointers without names and with defining actual types/
`<type c:type="hb_font_t*"/>`
```
<array length="1" zero-terminated="0" c:type="hb_feature_t*">
              <type c:type="hb_feature_t"/>
            </array>
```
We can treat `hb_font_t*` as `gconstpointer` with same name ,
but I can't find `hb_feature_t` definition https://gitlab.gnome.org/GNOME/pango,
so no idea what do with it.

cc @GuillaumeGomez , @sdroege 

https://gitlab.gnome.org/GNOME/pango/-/issues/458
https://gitlab.gnome.org/GNOME/pango/-/issues/467

**Comment by EPashkin** [comment]
https://harfbuzz.github.io/harfbuzz-hb-common.html#hb-feature-t-struct

`hb_feature_t` is non-primitive type so I have no idea what we can do with it at all.
My first idea was just remove functions with it, but there is field with it, so it need fix it too
```diff
<record name="FontClass" c:type="PangoFontClass" glib:is-gtype-struct-for="Font">
...
        </callback>
      </field>
-      <field name="_pango_reserved1" introspectable="0">
-        <callback name="_pango_reserved1">
+      <field name="get_features" introspectable="0">
+        <callback name="get_features" introspectable="0">
...
+ <field name="get_features" introspectable="0">
+        <callback name="get_features" introspectable="0">
```

**Comment by sdroege** [comment]
> `hb_feature_t` is non-primitive type,

It's only used as a pointer or not? Where is it not used as a pointer?

**Comment by EPashkin** [comment]
In first comment, it array of non-pointer elements.

**Comment by EPashkin** [comment]
Yes, it actually pointer, but it need be changed in gir-files, though it will be tricky.

**Comment by sdroege** [comment]
It's a pointer because it's an array, but the array contains non-pointer elements (the struct itself). We can replace the array with a plain `*const c_void`.

**Comment by EPashkin** [comment]
Agree, I but prefer constpointer as it have name.
`<type c:type="gconstpointer" name="gconstpointer"/>`

**Comment by sdroege** [comment]
Sure, that also works

**Comment by bilelmoussaoui** [comment]
This can be closed now as the upstream issue has been fixed
