### ISSUE TITLE
Generate doc aliases to C equivalents

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#909]
`rustdoc` has the `doc_alias` feature that you can see in action [here](https://doc.rust-lang.org/nightly/src/core/ops/bit.rs.html#113) (the two first items are aliases).

Considering that most examples for GNOME libraries are in C, I assumed that users could be looking for the C function in our doc. By adding aliases on our items, we would also return the rust one.

**Comment by fengalin** [comment]
Just to let you know, I've already done (at least part of) this for https://github.com/gtk-rs/gir/issues/963. Will post a PR this we hopefully.

**Comment by GuillaumeGomez** [comment]
I think it can be closed now.
