### ISSUE TITLE
Support adding versions in sys mode

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#916]
https://github.com/gtk-rs/gir/pull/915#issuecomment-623887761
> In gstreamer-sys I'm currently editing the generated build.rs for the version part specifically to add missing versions for making user's lives a bit easier: if no new API was added between GStreamer 1.14 and 1.16 in one library there would still be a v1_16 feature so that users can simply select v1_16 for all libraries without having to check for each of them if the feature actually exists. Or maybe for that I instead want a configuration option add_empty_major_versions to automate it?

or https://github.com/gtk-rs/gir/pull/915#issuecomment-623890033
> Maybe it better be include_versions_by_step="0.2"

in both cases we seems have problem if part not have elements with maximum version.

cc @sdroege , @GuillaumeGomez

**Comment by EPashkin** [comment]
@sdroege How many of these missed versions?
Maybe simpler just 
```
extra_versions = [
 "1.2",
"1.6",
]
```

**Comment by sdroege** [comment]
> `extra_versions = [`

That works for me too. Now to make it perfect, can we also extend this configuration so I can configure that version `1.18` only checks `pkg-config` for e.g. version `1.17.2`? This would also be useful for gtk-rs if we ever have the resources to track development versions of GLib (e.g. `2.66` would currently require `2.65.1`).

**Comment by EPashkin** [comment]
For this case we need separate option as IMHO it poorly written in TOML
```
[[lib_version_override]]
cfg="2.66"
lib="2.65.1"
```

**Comment by sdroege** [comment]
That would make sense to me. It's not beautiful but works. Both things together would remove all reasons why I currently have to manually edit things in the -sys crates.

**Comment by EPashkin** [comment]
Is `lib_version_override` or analog needed currently in gstreamer?

**Comment by sdroege** [comment]
> Is `lib_version_override` or analog needed currently in gstreamer?

Yes: Version `1.18` would have to cause a dependency on `1.17.1` currently.

**Comment by EPashkin** [comment]
Ok, I will do both

**Comment by sdroege** [comment]
Great, thanks :)
