### ISSUE TITLE
glib-sys dependencies broken

### ISSUE THREAD

**Issue by pwil3058** [gtk-rs/gir#921]
After doing a "rustup update", all of my gtk-rs dependent code stopped building with the message:

error: failed to run custom build command for `glib-sys v0.9.1`

Caused by:
  process didn't exit successfully: `/home/peter/SRC/GITHUB/RUST/CRATES/rs_pw_gix.git/target/debug/build/glib-sys-2f10ca1925245890/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.42"` did not exit successfully: exit code: 1
--- stderr
Requested 'glib-2.0 >= 2.42' but version of GLib is 2.34.3

As part of tracking down the cause of this I've found that the error message can be triggered by putting:

[dependencies.gtk]
version = "0.8.1"
features = ["v3_16"]

in the Cargo.toml file of an otherwise empty rust crate.

**Comment by sdroege** [comment]
The latest version of the glib-sys crate requires GLib 2.42 or newer, as written in the output above. There's no bug here, you only have to update the version on your system.

**Comment by pwil3058** [comment]
That statement doesn't make sense to me. What version of what? I did a "cargo update" after the "rustup update".

**Comment by pwil3058** [comment]
If you mean the C code, according to synaptic, I have GLib 2.56.4 installed.

**Comment by pwil3058** [comment]
Problem solved (or, at least, deferred).  I have the sources for Windows version of GTK+ installed (trying to do cross compilation) and the problem only occurs if I have PKG_CONFIG_PATH pointing at that code.  This happens even though the build is normal and not a cross compilation.

Thanks for you help.

**Comment by sdroege** [comment]
glib-sys uses pkg-config to find the glib C dependency, so you have to set that up correctly.
