### ISSUE TITLE
new_from_XXX() / new_with_XXX() functions are not renamed in the docs

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#936]
Since https://github.com/gtk-rs/gir/pull/929 they are renamed to not have the `new` prefix anymore, but the renaming did not happen for the docs.

Should be fixed before the release :)

See https://gstreamer.pages.freedesktop.org/gstreamer-rs/gstreamer/struct.Pad.html#method.from_template for an example that has no docs anymore.

CC @EPashkin @GuillaumeGomez @gdesmott

**Comment by gdesmott** [comment]
IIRC my patch should use the same code paths as when user manually rename a function using the toml file. Was doc broken for those as well?

**Comment by sdroege** [comment]
I don't know, there are some normal renames in gtk and gio IIRC that you could use for testing

**Comment by gdesmott** [comment]
That's strange, `DBusInterfaceExt.get()` and `WidgetExt.set_widget_name()` both use `rename`. The former is not documented (but neither are the other functions in this trait) but the former is.

**Comment by sdroege** [comment]
Something for @GuillaumeGomez I guess :)

**Comment by GuillaumeGomez** [comment]
To be checked...

**Comment by sdroege** [comment]
@GuillaumeGomez You fixed this or not?

**Comment by bilelmoussaoui** [comment]
cc @fengalin
