### ISSUE TITLE
If all enums are behind a specific configuration there are unused imports in `src/auto/enums.rs`

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#947]
Same probably also for `flags.rs`. See below

```rust
use glib::translate::*;
use glib::value::FromValue;
use glib::value::FromValueOptional;
use glib::value::SetValue;
use glib::value::Value;
use glib::StaticType;
use glib::Type;
use gobject_sys;
use gst_base_sys;

#[cfg(any(feature = "v1_18", feature = "dox"))]
#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
pub enum AggregatorStartTimeSelection {
    ...
}
```

**Comment by sdroege** [comment]
@MarijnS95 You just fixed this :)

**Comment by MarijnS95** [comment]
Nice! Forgot to check open issues, should have added a `Fixes:`. For posterity, this was solved in #1043 :)

**Comment by MarijnS95** [comment]
There are still a few in `gtk-rs` though, particular around `StaticType`. `FromValue` stuff in enums/flags was fixed though.

**Comment by MarijnS95** [comment]
https://github.com/gtk-rs/gtk-rs/compare/master...MarijnS95:regen-cleanup Removed all `#[allow(unused_imports)]` on `mod auto;`, let's see what the CI thinks about that: https://github.com/MarijnS95/gtk-rs/runs/1798103223

**Comment by MarijnS95** [comment]
@sdroege You might want to reopen this and follow up on the remaining issues ;)

**Comment by bilelmoussaoui** [comment]
I believe this is fixed now that we go through prelude.
