### ISSUE TITLE
Gir tutorial: Explain setting features

### ISSUE THREAD

**Issue by grelltrier** [gtk-rs/gir#958]
It would be helpful to have further explanations on how you can create a wrapper that enables certain features by setting a features flag in the Cargo.toml. When I asked @GuillaumeGomez about this ([context](https://discourse.gnome.org/t/generate-rust-bindings-for-gtk-layer-shell-with-gir/4051/2))he told me this:

"if you always want to have this feature enabled, then yes, it’s the best way to do it. If it’s optional though, you’ll want to declare a feature on your crate which will also enable the gdk’s one:
```
[features]
my_feature_name = ["gdk/v3_22"]
```
So when you enable my_feature_name, you’ll also enable the feature v3_22 in gdk."

**Comment by sdroege** [comment]
Can you give an example of what you're trying to do here? Does your crate depend on GTK 3.22 at least, or ...?

**Comment by sdroege** [comment]
That's what I would understand from the context at least, in which case you would add `features = ["v3_22"]` directly to `gdk` in your dependencies list in `Cargo.toml`. Only if the API that requires newer GDK is conditionally enabled you would add a feature flag for it like above.

**Comment by grelltrier** [comment]
I fixed the troubles I had with it. I also added a [PR](https://github.com/gtk-rs/gtk-rs.github.io/pull/172) to append information about this to the tutorial. I am not really sure it is necessary since it is not that gir specific
