### ISSUE TITLE
Gir tutorial: [NOT GENERATED FUNCTION]

### ISSUE THREAD

**Issue by grelltrier** [gtk-rs/gir#960]
I followed the tutorial and when I tried generating bindings for gtk-layer-shell, I noticed a number of [NOT GENERATED FUNCTION] after running `gir -m not_bound`. The tutorial does not mention what you are supposed to do in this case. The README.md mentions how to deal with global functions though so I was able to resolve my issue. However I think it would be helpful to add something alike the following to the tutorial:

If you see [NOT GENERATED FUNCTION] when trying to generate bindings, then you have global functions in your project. To generate code for all global functions, add Gtk.* to the generate array. To re-export the functions you also need to add `pub use self::auto::functions::*;` to your lib.rs.

**Comment by sdroege** [comment]
It might also mean that you didn't configure the type in question in your `Gir.toml` AFAIK, but yes that would be useful to add indeed. Do you want to create a PR?

**Comment by grelltrier** [comment]
I just opened one.
Sorry for opening all those issues here. I didn't know the tutorial is in another repo. These are my first pull requests. Gotta start somewhere :)
https://github.com/gtk-rs/gtk-rs.github.io/pull/170
