### ISSUE TITLE
Gir tutorial: Publishing bindings to crates.io

### ISSUE THREAD

**Issue by grelltrier** [gtk-rs/gir#961]
The bindgen tutorial ends with the suggestion to add the generated bindings to crates.io so others don't have to generate them themselves. I think this would also be a good idea for the gir tutorial. Additionally it could be helpful to mention best practices for how to share them. What files should be included in the repository, should the sys folder be included or should it be a separate repo.
Most important I think would be a friendly reminder to share the code though since I assume most people are more experienced then me and know how to publish the results :)

**Comment by grelltrier** [comment]
Another nice thing to know would be if it is possible to specify the input for all the missing fields in the Cargo.toml for the -sys bindings to be able to publish the crate (description, license.. ) somewhere so that when running gir again they do not get overwritten.

**Comment by sdroege** [comment]
> What files should be included in the repository

I guess the question here is about the `src/auto` files? Those should be included as that gives a proper history of the changes that happened to the generated bindings and allows to spot mistakes when updating to newer versions of the `.gir` file or the `gir` code generator.

> should the sys folder be included or should it be a separate repo

It should be a separate crate but it can be in the same repository. Whatever is easier for you. `gtk-rs/sourceview` and `gtk-rs/cairo` have it in the same repository as a separate crate, for example.

> when running gir again they do not get overwritten.

Try adding them manually and re-rerun gir :) They're not overwritten fortunately.
