### ISSUE TITLE
Rename get/set_XXX_property() to get/set_XXX()

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#962]
Came up a while ago in some issue. This should make the API nicer in 99% of the cases (and we already don't create the property functions if there are normal getters/setters), and in the few cases where there would be conflicts this can be resolved via renaming.

@EPashkin @GuillaumeGomez What do you think?

**Comment by GuillaumeGomez** [comment]
It's nicer but also "harder" for people to use. Explanations: mostly functions discoverability, if the name is too different from the C one, it makes it harder to find or know it's the one to use.

So personally, I don't mind, but I think it was important to be noted.

**Comment by GuillaumeGomez** [comment]
PS: I intend to use "doc_alias" in docs to allow to search for C function names directly. :3

**Comment by sdroege** [comment]
> mostly functions discoverability, if the name is too different from the C one, it makes it harder to find or know it's the one to use.

These would only exist if there are no C functions, otherwise we use the C getter/setter anyway (we do already now and don't generate the `get/set_XXX_property()` then).

Other bindings are behaving exactly the same btw (without a `_property` prefix), so it would seem more consistent in that regard at least.

**Comment by sdroege** [comment]
This should be done together with https://github.com/gtk-rs/gir/issues/963

That other ticket makes things follow Rust code style better, this one removes duplication from the API and makes us behave like literally all other bindings.

@bilelmoussaoui What do you think?

**Comment by bilelmoussaoui** [comment]
This can be closed now
