### ISSUE TITLE
Rename `get_` methods

### ISSUE THREAD

**Issue by hyarsan** [gtk-rs/gir#963]
The `get_` methods should be renamed to fit the amazing [Rust API Guidelines].

This would apply to the other crates as well.
Yes, there are a lot of methods, but it would lead to nicer, more rusty code.

## Examples
`ButtonExt.get_text()` -> `ButtonExt.text()`
`LabelExt.get_angle()` -> `LabelExt.angle()`

Perhaps methods like the following could look different?
`ButtonExt.get_always_show_image()` -> `ButtonExt.always_shows_image()`
`ButtonExt.get_use_underline()` ->`ButtonExt.uses_underline()`
Ehh...probably not.... it's just something to consider.

[Rust API Guidelines]: https://rust-lang.github.io/api-guidelines/naming.html#c-getter

**Comment by sdroege** [comment]
So @fengalin created https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/639 and I think this improves the API a lot, making it more Rust-y.

I think we should do the same here for gtk-rs: *most* getters should have their `get_` prefix removed, very few should keep it and some need special handling: `get_is_foo` -> `is_foo`, and others where the second word is a verb. We can implement heuristics for that and the 5 cases not covered by one of the heuristics can be manually fixed via Gir.toml.

@bilelmoussaoui @GuillaumeGomez What do you think?

**Comment by sdroege** [comment]
Also this should be done together with https://github.com/gtk-rs/gir/issues/962

**Comment by bilelmoussaoui** [comment]
I totally agree on this on renaming both cases. Other language bindings do make the properties usage seamless, for example Python can lets you modify the properties using `object.props.some_prop = value`, the same +/- for GJS & Vala. It would be nice if we can do all the renaming changes once though to avoid having to re-update everything multiple times though.

See #936 #974 #905

**Comment by fengalin** [comment]
Based on my experience of doing that manually in `gstreamer-rs`, bedsides implementing this in `gir`, we also need an automatic process for manual code conversion. I'm not skilled at `batch` text processing at all, but I think that goes beyond its capabilities. If we all agree on this, I'll take a look at implementing a parser / filter for this where we could setup the heuristics. Maybe we could also fix the call places in the process. Hopefully, this parser / filter could be useful for other future changes.

**Comment by sdroege** [comment]
> we also need an automatic process for manual code conversion

What do you mean with that btw? I would've assumed that `sed -i 's;fn get_;fn ;g' **.rs` would done the majority of work for the manual code already, and then we're only left with the special cases.

**Comment by fengalin** [comment]
> What do you mean with that btw?

For tracing: see my response to your other comment [there](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/639#note_704298).

**Comment by GuillaumeGomez** [comment]
@fengalin You're my hero! \o/

And if that doesn't create conflicts, I completely approve.

**Comment by sdroege** [comment]
This is explicitly mentioned in the Rust style guidelines btw: https://doc.rust-lang.org/1.0.0/style/style/naming/README.html#getter/setter-methods-[rfc-344] .
