### ISSUE TITLE
Error enums: Use the error-quark correctly

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gir#969]
see the comments in https://github.com/gtk-rs/glib/pull/697#discussion_r502524870 for details

**Comment by sdroege** [comment]
So what we should do here is to use the `error-quark` as a string, because that's what it is. There is not necessarily a function for this.

This can then be placed in a `OnceCell<glib::Quark>`, for example.

**Comment by sdroege** [comment]
Should also revert https://github.com/gtk-rs/gir-files/pull/60 at that point

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gir/pull/972
