### ISSUE TITLE
In sys mode does not consider versions from Gir.toml for the creation of Cargo.toml

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gir#979]
See https://github.com/gtk-rs/gtk-rs/pull/6#discussion_r514110595

**Comment by bilelmoussaoui** [comment]
Actually it's not really an issue, it needed this https://github.com/gtk-rs/gtk-rs/pull/20/commits/055ed38805ba98232287d8878b507c6950ef1e54

**Comment by sdroege** [comment]
Indeed
