### ISSUE TITLE
sys: empty abi layout tests

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gir#993]
see https://github.com/gtk-rs/gtk-rs/pull/30#discussion_r525060701

> graphene-sys fails because the ABI tests don't generate any layout tests... which seems to be problematic

```
error: unused import: `graphene_sys::*`
 --> graphene/sys/tests/abi.rs:8:5
  |
8 | use graphene_sys::*;
  |     ^^^^^^^^^^^^^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`

error: unused imports: `align_of`, `size_of`
  --> graphene/sys/tests/abi.rs:11:16
   |
11 | use std::mem::{align_of, size_of};
   |                ^^^^^^^^  ^^^^^^^
```

**Comment by sdroege** [comment]
The problem here is less that it still has those imports... but that it doesn't actually create layout tests for any of the structs :)
